### ISSUE TITLE
Data export doesn't work/Android storage permission not being given

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1038]
## Describe the bug
When installing mSupply mobile, it appears that storage access isn't being given to the app.

### To reproduce
Steps to reproduce the behaviour:
1. Install mSupply mobile on a tablet (should prompt with permissions, should include storage)
2. Check app settings for permissions
3. Should have Storage permissions

### Expected behaviour
Should ask for storage permission. Should get storage permission

### Version and device info
 - App version: 2.3.4
 - Tablet model: Lenovo, techno (maybe Samsung?)
 - OS version: *

**Comment by raviSussol** [comment]
@Chris-Petty I was also thinking that it would've been great if the apk would let user to know that it requires certain access and permission at the time of installing but didn't see any thing like that while installing the apk on the IC's tablets. Also I found that the storage permission doesn't require to export data in the android version <6 but do require in the version >=6. And all the IC's Tecno tablet are in the android ver. 6 or higher (I think) and I tried a lot to export data from those tablet but couldn't success because of this.

**Comment by Chris-Petty** [comment]
@raviSussol 
[Android manifest in mobile](https://github.com/openmsupply/mobile/blob/master/android/app/src/main/AndroidManifest.xml) I think has it set correctly.
I think this is the only setting we need, [WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE)

**Comment by Chris-Petty** [comment]
Should probably investigate other settings, like connectivity related ones.

**Comment by joshxg** [comment]
Closed by #1070

**Comment by wlthomson** [comment]
## TESTS

- [x] Successfully grants permissions for API > 23.
- [x] Successfully grants permissions for API <= 22.

Tested build on emulators running Lollypop (API 22) and Pie (API 28).
