### ISSUE TITLE
Disable automatic capitalisation on authentication TextInputs

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1077]
## Is your feature request related to a problem? Please describe.

When entering fields for initialisation and for login, it can be very annoying when the input automatically capitalises, completes or adds punctuation to user input.

## Describe the solution you'd like

Particular fields throughout the app cause this headache, I'd like to see the props to TextInput changed to not do these things. Particularly all those on InitialisationPage and LoginModal.
https://facebook.github.io/react-native/docs/textinput#autocapitalize
https://facebook.github.io/react-native/docs/textinput#autocorrect

## Describe alternatives you've considered

You can turn them off for the entire device in the keyboard settings, but that adds setup over head to mass roll outs and may not be desired for literally every input in all apps on the device!

**Comment by andreievg** [comment]
@Chris-Petty, interesting enough, there are a few sites in Vanuatu that use this 'headache' to their advantage, as user names were set up with a capital

**Comment by Chris-Petty** [comment]
@andreievg I'm pretty sure user names are not case sensitive (nor are sync site names)? The most silly annoying one was auto complete adding a space to names 😄.

Auto capitalisation is a pain for the password.

**Comment by joshxg** [comment]
@andreievg @Chris-Petty since there's some disagreement here:

Seems mobile does respect capitilisation but desktop doesn't - Would need changes to the input and also to the query for the username. And without checking, I'd guess a little more to make sure usernames are case-insensitive-unique.. possibly migration code etc. Probably more time than originally thought/we have

Gonna move this out of 3.1 - let me know if this was wrong

**Comment by Chris-Petty** [comment]
@joshxg Thanks, and woo I'm wrong! I think it's pretty common for capitalisation to be ignored for usernames, but not really a big issue either way. This issue doesn't strictly resolve it and conflicts with Vanuatu usage soooo might just close it 🙂
