### ISSUE TITLE
Mismatched fields when syncing a customer requisition to desktop

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1325]
## Describe the bug

If a value is entered into the customer requisition column "Supply this invoice" on mobile, this value appears under the "Already issued" column when synced back to desktop.

### To reproduce

1. Create a new customer requisition and sync it to mobile.
2. On mobile, update "Supply this invoice" for any item.
3. Manually sync the requisition back to desktop.
4. Open the requisition on desktop (to do this, you'll have to disable sync or edit the method to remove the permission check).
5. See error.

### Expected behaviour

Customer requisition values entered on mobile should sync to the correct column on desktop.

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1244#issuecomment-537723537.

**Comment by joshxg** [comment]
@Chris-Petty do you happen to know anything about this? From what I can tell none of this logic was touched - so is this the correct desired behaviour or am I not seeing something?

**Comment by Chris-Petty** [comment]
Sounds wrong to me (this issue is valid), but having a glance at desktop it's hard to guess what is going on cause the `requisition_line` field names are insane

**Comment by joshxg** [comment]
Seems quite weird. When you sync it is the right field: `[requisition_line]actualQuan` - but this shows up in that already supplied column when you view it. If you edit the supply this invoice on desktop, it applies to `actualQuan`, but suppliy this invoice doesn't come from `actualQuan`? Something like that.. I just had a quick look and it's quite confusing. Needs further checking, but this is not a regression and I think we can move it to a lower priority

**Comment by andreievg** [comment]
This is expected behaviour (it's just how mSupply displays the columns)

In mobile customer invoice is created automatically for requisition, when quantity is entered in supply this invoice that quantity is transferred to the customer invoice, and you should see already issued column in desktop with that quantity.

Can also check invoices created tab in the requisitions, it should have that linked invoice there.

(btw that invoice will appear in customer invoices when requisition is finalised).

Also you can check requisition_lines in record browser (or ds etc..), and should see actual_quantity set
