### ISSUE TITLE
Changes to stocktake line reasons

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1336]
## Is your feature request related to a problem? Please describe.

Desktop has changed stocktake line reasons to be `positiveInventoryAdjustments` and `negativeInventoryAdjustments`

## Describe the solution you'd like

Change sync to accept these types. Since they don't sync out, just keep them as one type in mobile.

Will also need to adjust logic for applying reasons

## Describe alternatives you've considered

Use two different types. This is more convoluted and annoying logic.

## Additional context

Related desktop issue: https://github.com/sussol/msupply/pull/4347

Could be done in data table branch, better to do it after its merged, imo

**Comment by joshxg** [comment]
Cosed by #1346

**Comment by wlthomson** [comment]
Fixed by #1395.

**Comment by Rebecca367** [comment]
The test has been carried out and everything works fine.

![image](https://user-images.githubusercontent.com/57238075/70099677-685b3480-1694-11ea-9a0a-545d708b39d9.png)

**Comment by joshxg** [comment]
@Rebecca367 - You need to go to the test cases from the PR that fixed this issue #1395 - which is in the timeline in this issue as well as linked to you - take the test cases, exactly the same as the other issues you have tested.

**Comment by Rebecca367** [comment]
The testing results are as below:

## TESTS 

- [x] When changing the counted quantity on a stocktake item, a modal opens with negative reasons
- [x] When changing the counted quantity on a stocktake item, a modal opens with positive reasons
- [x] When changing the quantity to have no difference, reasons are removed from the line (and all batches which have no difference)
- [x] When applying a reason the reason is applied to each batch with the corresponding difference.

**Comment by Rebecca367** [comment]
@joshxg  It would be nice if there is a testing manual on hand so that I know where to get to Texting template for each issue. Thanks and forgive my lack of education on doing testing on github.
