### ISSUE TITLE
In-app Help documentation

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1388]
## Is your feature request related to a problem? Please describe.

Evident by things like un-finalised invoices/requisitions and by the need for user training - the app as simple as it may be, is still a little complicated.

## Describe the solution you'd like

In app help documentation to help users understand what is going on.

For example (very rough prototype), this could be on every page.. with page specific content:

![inappdocs](https://user-images.githubusercontent.com/35858975/66881260-d5523680-f022-11e9-801c-eb6807bd6eb7.gif)

- I think the easiest/quickest way to accomplish this is by just using pictures as above from documentation.. obviously tidier than above.
- Would make it mandatory to keep documentation up to date

It's not quite as easy of an implementation as just chucking some pictures in. Would require use of redux and possibly to tidy redux up (this would help with other issues also i.e. #1123 )

## Describe alternatives you've considered

Could also use https://github.com/react-native-community/react-native-webview to open up the wiki page.

Also somehow pull the wiki page and display it (not sure how yet) @wlthomson idea

## Additional context

I think this would be a good first start, but possibly insufficient for in-app documentation. But it would be better than nothing and wouldn't take too much time to implement. Also has cross over with existing issues in regards to possible changes to areas in the app to make further feature implementations easier

**Comment by wlthomson** [comment]
I like this. My only concern would be that we already spend quite a lot of time on user documentation, so we probably want to be careful with adding more docs. Off the top of my head I can think of two ways of doing this:

1. "Sync" with the user documentation by pulling in the .html (or whatever format is best) and storing locally. That way, maintain offline first capabilities but also keep up-to-date and only need to update one source of info.

2. Natively replicate the user docs (maybe only the subset that is relevant to mobile?). 

First way is the quickest, and probably the best for a quick prototype. Second way is probably nicer, but more work to make/maintain?

**Comment by wlthomson** [comment]
I like this and think it's actually a pretty important feature. It would make documentation significantly easier to access and navigate and could help reduce the load on the support team (I don't know, but I imagine a fair bit of the support team time could be saved by redirecting users to the user docs).

My only concern would be that we already spend quite a lot of time on maintaining and updating docs, so we probably want to be careful with this in order to avoid extra support overhead. Off the  top of my head, I can think of three ways of doing this 

1. Display the wiki page in a webview. 

2. "Sync" with the user documentation by pulling in the .html (or whatever format is best) and storing locally. That way, maintain offline first capabilities but also keep up-to-date and only need to update one source of info.

3. Natively replicate the user docs (maybe only the subset that is relevant to mobile?). 

First way is the quickest, and probably the best for a quick prototype. Third way is probably the best, but quite a lot of work to make/maintain? Second way seems like an OK balance?

**Comment by craigdrown** [comment]
We all think users use documentation- our field experience is that they don't. Documentation is used by consultants evaluating mSupply people who are working at a high level (like coordinating a roll-out in a country). It's a good idea, but lower priority than it appears on the surface (sorry!)
