### ISSUE TITLE
AutoCompleteSelector should use new SearchBar

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1404]
## Describe the bug

The widget `AutoCompleteSelector` uses the `SearchBar` from `react-native-components`. Using the internal `SearchBar` is better

### To reproduce

1. Go to CI, click create new customer invoice

### Expected behaviour

It would have a button for clearing the search term

### Version and device info

2.3.6 development

### Additional context

N/A

**Comment by Rebecca367** [comment]
@joshxg 
I am not sure about this issue and how to start with this one. I sit possible to shed some light on this one or suggest it to be done by person who has in-depth knowledge about code base?

**Comment by joshxg** [comment]
@Rebecca367 

- `AutocompleteSelector` component uses this component from this library: 
    - https://github.com/openmsupply/mobile/blob/master/src/widgets/AutocompleteSelector.js#L8
    - https://github.com/openmsupply/mobile/blob/c35dafd163f953a54d800421ba76470bb0df1a6f/src/widgets/AutocompleteSelector.js#L93-L102
- This issue is to remove this component and REPLACE it with this component https://github.com/openmsupply/mobile/blob/master/src/widgets/SearchBar.js which is an internal component in our repository

Is that helpful?

**Comment by joshxg** [comment]
Putting this in the backlog and moving out of 3.1.0 release

**Comment by joshxg** [comment]
Closed by #1667

**Comment by diegoevangelisti** [comment]
## Testing

- [x] go to customer invoice
- [x] click on "new invoice"
- [ ] search for customers

During testing in the tablet, I found the filter is not working properly (See that after typing `Baltimor` it doesn't filter other available options).

Also found an orange cancel icon on the right (see picture below) while I guess the expected one is white.

Tablet model Lenovo XB-X304L
Android version 7.1.1
APK: mSupplyMobile-3_2_0-rc1-universal-release.apk

Screenshot:
![Screenshot_2020-01-08-12-03-24-559](https://user-images.githubusercontent.com/32987464/71941952-774b7e80-3220-11ea-9cea-efbb2654a087.jpeg)

@joshxg @Rebecca367 Please let me know in case you consider I'm doing something wrong otherwise I'll create the issue. Thanks!

**Comment by Chris-Petty** [comment]
I think the cancel button is just red for the searchbar by default (and is red in the table pages), seems fine

**Comment by joshxg** [comment]
@diegoevangelisti 

Make an issue: https://github.com/openmsupply/mobile/blob/1223ef686342e963aadcc51fcb87d8ce3a593c9c/src/widgets/modalChildren/AutocompleteSelector.js#L34 this line is a problem. Should be:

`const inputValue => setQueryText(inputValue)`
