### ISSUE TITLE
Program requisition pricing not working

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1407]
## Describe the bug

The price column in a program supplier requisition is not working

### To reproduce

1. Create a Program where an item has a price on desktop, relate it to the mobile store
2. Create a program requisition on mobile
4. See the price does not show!

### Expected behaviour

The price should show!

### Version and device info

2.3.6 development

### Additional context

Current code:

```
    // Query string: Query for all MasterList.IDs related to this store and this item.
    const queryString = `${masterListIds
      .map(id => `masterList.id == '${id}'`)
      .join(' OR ')} AND item = $0`;

    // Return the maximum price of all MasterListItems.
    return UIDatabase.objects('MasterListItem')
      .filtered(queryString, this)
      .max('price');
  }
```

Need to change the line
```
.filtered(queryString, this)
```

To

```
.filtered(queryString, this.item)
```

**Comment by joshxg** [comment]
Fixed by #1416

**Comment by diegoevangelisti** [comment]
## Testing

- [ ] Create two masters lists for the mobile store. At least one should be a program. Add an item with different prices. Create a program requisition with the item. Price should be the max of those two prices.

When having two master lists related with a mobile store, it is taking the highest price as expect. But at the same time it is applying that max price to the rest of products in the ML.

Like in the following example:
![Screen Shot 2019-12-05 at 9 39 00 AM](https://user-images.githubusercontent.com/32987464/70179852-b2e7ba00-1743-11ea-83e4-000c853e9b25.png)

ITEM CODE 050457, Price: 30 -> Ok. Should be 30 because in the other ML it is 15.
ITEM CODE 047285, Price: 30 -> Wrong. Should be 20. This product only belongs to this ML and price is 20.

New Program and Test Program are the only two ML programs related with this mobile store.
![Screen Shot 2019-12-05 at 9 47 33 AM](https://user-images.githubusercontent.com/32987464/70180164-59cc5600-1744-11ea-8c71-a93872ccd419.png)

In New Program, Price of ITEM CODE 047285 is 20.
<img width="688" alt="Screen Shot 2019-12-05 at 9 38 07 AM" src="https://user-images.githubusercontent.com/32987464/70179961-e9253980-1743-11ea-8bc8-2d86358e5263.png">

And ITEM CODE 047285 doesn't belong to Test Program. (so it doesn't have a another price rather than 20)
<img width="661" alt="Screen Shot 2019-12-05 at 9 38 46 AM" src="https://user-images.githubusercontent.com/32987464/70180064-28ec2100-1744-11ea-8bcc-7c0cfe7be230.png">

I hope this is clear enough. @joshxg this test passes if you agree and I can create a new issue related with what I just mentioned.

**Comment by joshxg** [comment]
### To reproduce

Steps to reproduce the behavior:

- [x] Create two masters lists for the mobile store. At least one should be a program. Add an item with different prices. Create a program requisition with the item (ITEM 1) and add a different item (ITEM 2).
- [x] See that ITEM 2 is taking the price of ITEM 1.

beautiful, passed
