### ISSUE TITLE
ARM64 apk fails to install

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1435]
## Describe the bug

Installing mSupplyMobile-3_0_0-arm64-v8a-release.apk
from https://github.com/openmsupply/mobile/releases/tag/v3.0.0 fails to run on a Samsung TabA SM-T580

This should be the correct installer for the CPU (besides the universal one, which does work).

### To reproduce

1. copy mSupplyMobile-3_0_0-arm64-v8a-release.apk to tablet or run sureMDM job
2. Run it
3. "App not installed"

### Expected behaviour

Should successfully install mSupply mobile

### Version and device info

- App version: 3.0.0
- Tablet model: Samsung SM-T580
- OS version: Android something or another

**Comment by joshxg** [comment]
- Turns out the Samsung SM-T580 uses the armv7-a instruction set. Installing the v7a APK does install correctly on this device.
- Our Lenovo uses the ARMv8-A instruction set - the specific APK does install fine on that device also.

Without having x86 devices, those specific APK's can't really be checked 100%, but the apk's have the correct libraries after unpacking and surely if the ARM apks are working correctly, the x86 ones are also? 

Going to close this!
