### ISSUE TITLE
Add PropTypes to pages

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1439]
## Is your feature request related to a problem? Please describe.

We currently disable `react/forbid-prop-types` for all pages. Using proper PropTypes is a good idea for helping catch errors at run-time.

## Describe the solution you'd like

Update PropTypes using `instanceOf` and `shape` instead of `object`. We can then remove the disabling of `react/forbid-prop-types`.

## Describe alternatives you've considered

Leaving as is, or disabling for all files. Although this is a quick solution, I don't think it's a good idea as enforcing types only takes a small amount of work and is a good way to reduce errors and likely more than pay for itself in the long run.

## Additional context

See #845.

**Comment by joshxg** [comment]
Closed by #1448

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Navigating to customer invoices in development mode does not show any props errors.
- [x] Opening a customer invoice in development mode does not show any props errors.
- [x] Navigating to customer requisitions in development mode does not show any props errors.
- [x] Opening a customer requisition in development mode does not show any props errors.
- [x] Navigating to supplier requisitions in development mode does not show any props errors.
- [x] Opening a supplier requisition in development mode does not show any props errors.
- [x] Navigating to stock in development mode does not show any props errors.
- [x] Navigating to stocktakes in development mode does not show any props errors.
- [x] Editing a stocktake in development mode does not show any props errors.

**Success** All tested and working well.
