### ISSUE TITLE
AutocompleteSelector should use Hooks API

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1540]
## The suggestion

AutocompleteSelector should use Hooks API rather than React Class API

**Why?**
Consistency and https://github.com/openmsupply/mobile/issues/1092

## Describe alternatives you've considered

Doing nothing.

**Comment by joshxg** [comment]
Closed by #1704

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [X] Pages using `AutocompleteSelector` should work properly.
- [X] Pages using `MultiSelectList` (Master-list selection) should work properly.
- [X] Rest of the interface should be same. This is code refactor.

**Success** Tried to play around as much as possible based on these test cases and it's working well.
