### ISSUE TITLE
Scripts for exporting json to csv and back to js for localization files

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#1608]
Related with issue #484 

By now, all localization strings are hard-coded in js files, which makes it difficult and time consuming when sending for translation.

The final purpose of this feature is to create a script that export JSON localization files to CSV, ready to send for translation. Once translated, strings are imported as JSON again and placed in the corresponding localization file.

## Implementation

- Replace all `js` files under /localization for `JSON` files
- Modify /localization/index.js to import those new `JSON` files and export its corresponding LocalizedStrings
- Create`convertJsonToCsv.js` to do the exporting json to csv and add a script in package.json to run this feature in the command line. Something like: `yarn json-to-csv [selectedLangague]`
- Create`convertCsvToJson.js` to do the exporting csv to json and add a script in package.json to run this feature in the command line. Something like: `yarn csv-to-json [selectedLangague]`
- Create a doc explaining main details of this feature, installation and usage.

**Comment by Chris-Petty** [comment]
@diegoevangelisti @Rebecca367 generally we use assignment on issues to indicate who is actually taking an issue on and doing the code. Typically actively, that is to say don't assign yourself or anyone if you're not starting on it within the next week. Do assign yourself if you're starting the actual design/development as your focus.

I'm going to un-assign myself and Andrei 'cause we're not actually working on this issue, but that's not to say we won't be available help/discuss though! (Well Andrei is on holiday but you know what I mean).

**Comment by joshxg** [comment]
@diegoevangelisti if you have time, are you able to help @Rebecca367 setup for testing this issue before you go away?

**Comment by diegoevangelisti** [comment]
> @diegoevangelisti if you have time, are you able to help @Rebecca367 setup for testing this issue before you go away?

Sure, I will do it tomorrow. Good you thought about that. Cheers!

**Comment by Rebecca367** [comment]
Hi Diego:
Let's set up a time to do it today. What time is good for you?

**Comment by diegoevangelisti** [comment]
> Hi Diego:
> Let's set up a time to do it today. What time is good for you?

Great. All the tests and explanation are here: #1661 
Would be great if you can take a look and start working on those test. Then please let me know in case something is not clear so I can work on that today (the sooner the better I reckon). I am at the office so feel free to contact me when needed (Telegram or here) regarding this :-)
Thanks btw!

**Comment by Rebecca367** [comment]
fr translation file is done.
<img width="1440" alt="Screen Shot 2019-12-20 at 9 25 08 AM" src="https://user-images.githubusercontent.com/57238075/71208526-09d9bb80-230e-11ea-81e8-05d143a1b8ae.png">
<img width="1440" alt="Screen Shot 2019-12-20 at 9 47 46 AM" src="https://user-images.githubusercontent.com/57238075/71208530-0ba37f00-230e-11ea-9c32-fd8a9bfb8b53.png">


## Testing

Steps to reproduce or otherwise test the changes of this PR:

#### Step 1
- [x] Type: `yarn translation export fr` in the command line. A file named fr.csv should be generated in `src/localization/translations`
- [x] Open the generated csv file in [Google sheets](https://www.google.com/sheets/about/)
- [x] Columns from left to right should show the corresponding files name, keys in english, values in english and values in selectedLanguage (in french for this example).

#### Step 2
- [x] Add a translation for a string that it does not has a value in french. Like in the example, add `THIS IS AN EXAMPLE` as a value for `repeat_password` in french.
<img width="535" alt="Screen Shot 2019-12-17 at 12 38 43 PM" src="https://user-images.githubusercontent.com/32987464/70952106-2eddec80-20ca-11ea-8026-d938dced3a54.png">

- [x] Save the file as `tsv` (tab separated values) and name it as `fr.tsv`
- [x] Place `fr.tsv` in `src/localization/translations`

#### Step 3
- [x] Type: `yarn translation import fr` in the command line.
- [x] Check successful message in the console
- [x] In `src/localization/authStrings.json` check that the added value must exist and it should be the same as the one added.

Repeat that process with the rest of the languages: tl, la, gil.

**Comment by diegoevangelisti** [comment]
The second screen shot shows a `fr.tsv` file but what you have there is a csv with a different extension. Wonder if you are saving the file as tsv in Google sheets this way?

<img width="915" alt="Screen Shot 2019-12-20 at 9 57 24 AM" src="https://user-images.githubusercontent.com/32987464/71209079-6093c500-230f-11ea-9d72-c384b161240a.png">

Otherwise the importing it is not going to work (it is expecting tab separated values).
Something like this:

![Screen Shot 2019-12-20 at 10 00 38 AM](https://user-images.githubusercontent.com/32987464/71209156-9d5fbc00-230f-11ea-88b6-df47f0ae7f59.png)
Let me know please, thanks!

**Comment by diegoevangelisti** [comment]
I just added more clarification on the testing section based on your feedback @Rebecca367 
Thank you for that! Highly appreciated

**Comment by Rebecca367** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:
<img width="679" alt="Screen Shot 2019-12-20 at 3 59 44 PM" src="https://user-images.githubusercontent.com/57238075/71226739-d022a800-2341-11ea-9aa4-151a8b3ac616.png">


#### Step 1
- [x] Type: `yarn translation export fr` in the command line. A file named fr.csv should be generated in `src/localization/translations`
- [x] Open the generated csv file in [Google sheets](https://www.google.com/sheets/about/)
- [x] Columns from left to right should show the corresponding files name, keys in english, values in english and values in selectedLanguage (in french for this example).

#### Step 2
- [x] Add a translation for a string that it does not has a value in french. Like in the example, add `THIS IS AN EXAMPLE` as a value for `repeat_password` in french.
<img width="535" alt="Screen Shot 2019-12-17 at 12 38 43 PM" src="https://user-images.githubusercontent.com/32987464/70952106-2eddec80-20ca-11ea-8026-d938dced3a54.png">

- [x] Save the file as `tsv` (tab separated values) and name it as `fr.tsv`
- [x] Place `fr.tsv` in `src/localization/translations`

#### Step 3
- [x] Type: `yarn translation import fr` in the command line.
- [x] Check successful message in the console
- [x] In `src/localization/authStrings.json` check that the added value must exist and it should be the same as the one added.

Repeat that process with the rest of the languages: tl, la, gil.

fr,tl.la and gil translation files were tested and look good.

fr.csv
<img width="638" alt="Screen Shot 2019-12-20 at 3 52 53 PM" src="https://user-images.githubusercontent.com/57238075/71226488-dd8b6280-2340-11ea-9135-dce0d70b14c5.png">

fr.tsv
<img width="615" alt="Screen Shot 2019-12-20 at 3 55 16 PM" src="https://user-images.githubusercontent.com/57238075/71226581-34913780-2341-11ea-9966-d061597741d4.png">

tl.csv
<img width="679" alt="Screen Shot 2019-12-20 at 3 59 44 PM" src="https://user-images.githubusercontent.com/57238075/71226742-d44ec580-2341-11ea-9bb1-b199a07ce65c.png">

tl.tsv
<img width="776" alt="Screen Shot 2019-12-20 at 4 01 48 PM" src="https://user-images.githubusercontent.com/57238075/71226812-17109d80-2342-11ea-85ae-cb7a6f8cca67.png">

la.csv
<img width="547" alt="Screen Shot 2019-12-20 at 4 06 13 PM" src="https://user-images.githubusercontent.com/57238075/71227012-bd5ca300-2342-11ea-8b8f-4b42787a42e4.png">

la.tsv
<img width="841" alt="Screen Shot 2019-12-20 at 4 08 32 PM" src="https://user-images.githubusercontent.com/57238075/71227123-12001e00-2343-11ea-8c93-66d64981a5d3.png">

gil.csv
<img width="603" alt="Screen Shot 2019-12-20 at 4 15 15 PM" src="https://user-images.githubusercontent.com/57238075/71227418-019c7300-2344-11ea-868f-e44220964697.png">


gil.tsv
<img width="566" alt="Screen Shot 2019-12-20 at 4 11 01 PM" src="https://user-images.githubusercontent.com/57238075/71227235-60152180-2343-11ea-9637-2e6c8886136f.png">

**Comment by joshxg** [comment]
@diegoevangelisti @Rebecca367  -- just wondering what happens when we try to break it.. for example, we remove some lines, or we have a KEY with no VALUE .. or a VALUE with no KEY etc..

**Comment by Rebecca367** [comment]
OK, let me try to break it!!

**Comment by Rebecca367** [comment]
@joshxg @diegoevangelisti 
I have broken fr.csv as below: 

<img width="777" alt="Screen Shot 2019-12-20 at 4 43 34 PM" src="https://user-images.githubusercontent.com/57238075/71228739-e92e5780-2347-11ea-8309-34347aa29fe5.png">

It doesn't affect fr.tsv and the program is still running 
<img width="830" alt="Screen Shot 2019-12-20 at 4 45 05 PM" src="https://user-images.githubusercontent.com/57238075/71228795-28f53f00-2348-11ea-9e03-2e4b98ccef42.png">

Running translation export fr in command line
<img width="541" alt="Screen Shot 2019-12-20 at 4 47 12 PM" src="https://user-images.githubusercontent.com/57238075/71228875-75d91580-2348-11ea-97df-5b937ce67a29.png">
original fr.csv file has came back
<img width="568" alt="Screen Shot 2019-12-20 at 4 48 30 PM" src="https://user-images.githubusercontent.com/57238075/71228927-9dc87900-2348-11ea-84fc-2c8ee4fe6259.png">

**Comment by diegoevangelisti** [comment]
> @diegoevangelisti @Rebecca367 -- just wondering what happens when we try to break it.. for example, we remove some lines, or we have a KEY with no VALUE .. or a VALUE with no KEY etc..

I am going to add test cases to check that (Step 4 and so). Those cases were taken into consideration and it all should be ok.

**Comment by joshxg** [comment]
sorry @Rebecca367 can  you be explicit in writing about what you have broken and how you broke it.. that way we can decide if it is a bad enough problem to warrant an issue being created for that

**Comment by joshxg** [comment]
> sorry @Rebecca367 can you be explicit in writing about what you have broken and how you broke it.. that way we can decide if it is a bad enough problem to warrant an issue being created for that

I will expand: Just because diego and andrei are going away, it is hard for me who doesn't really know too much about the feature to know what is going on!

**Comment by diegoevangelisti** [comment]
> @joshxg @diegoevangelisti
> I have broken fr.csv as below:

This is fine, but it makes sense because basically what you are doing is generating another file that is replacing the previous `fr.csv`.

What you should check in that case is trying to break it and open that "broken" one on Google sheet and check if it's showing the correct values. I hope this can help! 

Anyway I will add more test cases so maybe you both (@Rebecca367, @joshxg ) can check all cases together and make sure all works good.

Thanks for this btw :-)

**Comment by Rebecca367** [comment]
@joshxg @diegoevangelisti 
The thing is this is the only way I know of how to break files as @joshxg  mentioned as for how and explicitly on how correctly to break it as josh wished is probably only the person who designed it knows the best. Hope this explanation helps josh to understand the concept!

**Comment by joshxg** [comment]
@Rebecca367 I meant the steps that YOU took in order to break it :)

**Comment by Rebecca367** [comment]
ok, I only deleted some keys in some lines and keys in other lines and delete other lines in the file. The broken csv files doesn't affect tsv file, so translators still able to translate it to tsv file. I didn't break tsv file which I should do in the first place.
I will do more tests after Diego creates relevant test cases. 
BTW, I will start my leave one day after Diego is gone and end two days before he comes back. I don't think these tests will cause me bother you too much, so don't worry!

**Comment by joshxg** [comment]
@Rebecca367 

No worries. Thanks so much :) 🥇 

I'm sure there is plenty of information here and we can leave this now until everyone is back 

🎉 🎉 🎉

**Comment by Rebecca367** [comment]
### Breaking Test 1
- [x] Delete a complete row (or more than one) from the file `fr.csv`.
- [x] Open the file in Google sheets and download it as `tsv`. Then rename it as `fr.tsv`.
- [x] Place `fr.tsv` in `src/localization/translations`
- [x] Run `yarn translation import fr` 
- [FAILED ] Check that the deleted values are still in the corresponding localization file.

### Breaking Test 2
- [x] Delete a key value (situated on the 2nd column or column B) from the file `fr.csv` (for example `repeat_password`).
- [x] Open the file in Google sheets and download it as `tsv`. Then rename it as `fr.tsv`. 
- [x] Place that `fr.tsv` file in `src/localization/translations`
- [x] Run `yarn translation import fr` 
- [x] Check that the deleted values are still in the corresponding localization file. (e.g. check that `repeat_password` and its values in english and french are still in `authStrings.json`).

Repeat that process with the rest of the languages: tl, la, gil.

**Comment by Rebecca367** [comment]
@diegoevangelisti  
All good!
