### ISSUE TITLE
3.1.0 Release

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1671]
## Release Version

3.1.0

## Summary

Main features being introduced are badges, selecting master lists and a settings page. There are also various bug fixes and refactors. The release has not been specifically aimed at any large feature or client.

### Features
#1513
#1504
#1454
#1426
#1212
#879
#507
#1557 

### Refactors
#1663
#1575
#1574
#1560
#1555
#1526
#1491
#1487
#1486
#1482
#1380
#1289
#1169

### Bugs
#1666
#1647
#1645
#1640
#1626
#1621
#1611
#1580
#1573
#1536
#1533
#1519
#1518
#1515
#1490
#1479
#1450
#1440
#1207
#1100

## Documentation

Required documentation:

- [ ] #1513
    - Draft: https://docs.google.com/document/d/1QSRoUR0WSm3EMvtOh5GyZFn5mdIfDUBofdTB2D9BGZ8/edit?usp=sharing
    - Final: 
- [ ] #1504
    - Draft: https://docs.google.com/document/d/1t7g9rImrupVpz3qBfUnM1tzXgWWsfGUuA6GrkKzPE5Q/edit?usp=sharing
    - Final: 
- [ ] #1212
    - Draft: https://docs.google.com/document/d/1ipFkttGDUeGw_8X8XQGTKT89koFGQiKITBwdI3mhiYc/edit?usp=sharing
    - Final: 
- [ ] #507
    - Draft: https://docs.google.com/document/d/10e_NhIpzzBfFC2zbVnh244rwBi_6UsdmxyV0SCM3AT8/edit?usp=sharing
    - Final: 
- [ ] #1557 
    - Draft: https://docs.google.com/document/d/1tXnPVSi42fbuhwu58oRph5ZzjHOa5STPL28Uwd0bo0E/edit?usp=sharing
    - Final:

**Comment by emilyporrello** [comment]
Docs completed:

#1513: Added screenshots showing what happens when you search for an item when creating Customer Invoices and Supplier Requisitions https://docs.msupply.foundation/en:mobile:user_guide:customer_inv
https://docs.msupply.foundation/en:mobile:user_guide:supplier_requisitions

#1212: Added screenshots for adding items from a master list in Customer Invoices and Supplier Requisitions
https://docs.msupply.foundation/en:mobile:user_guide:customer_inv
https://docs.msupply.foundation/en:mobile:user_guide:supplier_requisitions

#1557: Updated screenshot and added definition of 'max lines' in Supplier Requisitions (Programs); also updated desktop user guide for program configuration
https://docs.msupply.foundation/en:mobile:user_guide:supplier_requisitions_program 
https://docs.msupply.org.nz/items:programs#creating_a_program

#507:  Badges explained in Getting Started page (with updated screenshots of main screen)
https://docs.msupply.foundation/en:mobile:user_guide:getting_started

#1504: Settings button explained in Getting Started page (with updated screenshots of main screen); details outlined in new Mobile Settings page
https://docs.msupply.foundation/en:mobile:user_guide:getting_started
https://docs.msupply.foundation/en:mobile:user_guide:mobile_settings

**Comment by joshxg** [comment]
@emilyporrello amazing 🎉
