### ISSUE TITLE
Bugsnag upload should automatically fetch the version number

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1674]
## Is your feature request related to a problem? Please describe.

In the script `upload.sh` the version number is hardcoded. This is likely to cause user errors in the future.

## Describe the solution you'd like

Automatically fetch the version number from `package.json` from the `version` field.

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

@wlthomson easy?

**Comment by Rebecca367** [comment]
@andreievg 
This issue is to catch version number from package.js and embed it into upload.sh as explained yesterday, so what I would do is to get APP_Version by using `grep` to grab version number from package.js then embed it into upload.sh in dev.script. 
Regarding for testing, I think I will use command line to check on version number in upload.sh.
Is the explanation clear or I need to do anything else?

**Comment by andreievg** [comment]
@Rebecca367, sound like a reasonable solution.
> I think I will use command line to check on version number in upload.sh.

What do you mean by this ?

I think, as per discussion design, if you can make a sh script, in the same location as upload.sh, which will get version number from package json, store it in a variable then echo that variable, that would be the first step.
Then we can use the same code in upload.sh, and remove the testing script

**Comment by Rebecca367** [comment]
@andreievg 
>I think I will use command line to check on version number in upload.sh.

What do you mean by this ?
As for testing. Testers should be able to use app_version(whatever we call it) to check on version numbers in terminal.
Cheers, since you are happy with the logic and design,I will proceed it tomorrow. Thanks

**Comment by andreievg** [comment]
Sorry I am not understand, you've said Testers should be able to use app_version(whatever we cal it)

 What is 'it' in the context ?

**Comment by Rebecca367** [comment]
@andreievg 
Testers should be able to use App_Version in terminal to extract app version from package.js.
Is it clear enough?

**Comment by Rebecca367** [comment]
@andreievg 
<img width="639" alt="Screen Shot 2020-02-19 at 7 55 57 PM" src="https://user-images.githubusercontent.com/57238075/74811734-ffac5b80-5356-11ea-824c-7e96c61fc007.png">

Regarding to testing : Testers need to be in mobile directory to run `bash ./version.sh` to get version number. 
<img width="442" alt="Screen Shot 2020-02-19 at 8 56 57 PM" src="https://user-images.githubusercontent.com/57238075/74814436-24570200-535c-11ea-82a7-969f154a730b.png">

**Comment by joshxg** [comment]
@Rebecca367 looks like @andreievg got this covered! :) 1 thing is - it looks like you are on `master` - make sure to branch off `develop` for the PR 👍 

But looks like nice code!!!

**Comment by Rebecca367** [comment]
@andreievg 
Should I proceed with code and git stuff today?

**Comment by andreievg** [comment]
@Rebecca367, that's a good solution, but was wondering if it can be simplified. Instead of using 3 command lines operations and piping result to each one of the, how about using inline node scripts (as most of us would be more familiar with node:
`node -e "console.log(require('./package.json').version)"` <- can you use this one please and show the result

**Comment by Rebecca367** [comment]
@andreievg 
It runs as expected 
` echo $(node -e "console.log(require('./package.json').version)")`
result: 3.2.4 
Thanks

**Comment by joshxg** [comment]
Closed by #2363

**Comment by wlthomson** [comment]
Confirmed working in latest `develop` (`v5.0.0-rc3`).
