### ISSUE TITLE
Create a StocktakeBatch when creating a StocktakeItem

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#1680]
## Describe the bug
Related to #673 

App does not sync uncounted stocktake lines, then on initialisation they are gone burgers.

### To reproduce

1. Create a stocktake with items
![Screen Shot 2019-12-13 at 11 23 33](https://user-images.githubusercontent.com/7684221/70755204-15713380-1d9e-11ea-98bf-dd032cc990c6.png)
2. Count a couple lines
![Screen Shot 2019-12-13 at 11 24 04](https://user-images.githubusercontent.com/7684221/70755205-1609ca00-1d9e-11ea-9b9c-4aef8d524b11.png)
3. Sync the stocktake (note there should be far more records pending)
![Screen Shot 2019-12-13 at 11 24 15](https://user-images.githubusercontent.com/7684221/70755206-1609ca00-1d9e-11ea-8410-0a8b9d0a1345.png)
4. Wow sync is done
![Screen Shot 2019-12-13 at 11 24 33](https://user-images.githubusercontent.com/7684221/70755207-16a26080-1d9e-11ea-9dae-f6c493a8b99f.png)
5. Clear app data and resync the app
6. Witness that all lines except those that were counted have vanished.
![Screen Shot 2019-12-13 at 11 26 05](https://user-images.githubusercontent.com/7684221/70755208-16a26080-1d9e-11ea-8020-8cdb40ddbc50.png)

### Expected behaviour

That the lines in the original stocktake are persisted on the server through sync

### Proposed Solution

I suspect this occurs if the site synced has no stock, so when adding `StocktakeItems` no `StocktakeBatches` are created. The server only keeps track of the latter, but we're only sending the former... I think. If this is correct, one solution would be to make at least 1 `StocktakeBatch` when creating a `StocktakeItem` if none already exist.

Doing it server side is fraught with issues due to sync.

### Version and device info

- App version: 3.2.0
- Tablet model: emulator
- OS version: android 9

**Comment by Rebecca367** [comment]
Somehow I couldn't replicate what Chris mentioned above that items with 0 stocks on hand vanish after sync with server. 
<img width="858" alt="Screen Shot 2020-03-24 at 9 02 04 PM" src="https://user-images.githubusercontent.com/57238075/77402289-4dfbc100-6e13-11ea-9fcc-cbf18cd71b01.png">


After stocktake synced to desktop, mobile stocktake still shows items with 0 stock in stocktake that has't been finalised in mobile, so I think this issue somehow might be fixed in some ways along with other new features. I will close it right now, reopen it if this issue still exist.

**Comment by joshxg** [comment]
this is viewing a stock take after re-initializing. This bug still occurs
