### ISSUE TITLE
ReportChart component

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1713]
## Is your feature request related to a problem? Please describe.

Need a chart component for displaying charts/graphs for the mobile dashboard 

## Describe the solution you'd like

A component similar to https://github.com/openmsupply/mobile/blob/49d8ab764c85ec5e35699661da92aad8c3e1b03a/src/widgets/ReportChart.js

However, I *think* a better implementation would be to separate out the different charts - pie/line/bar into their own components, rather than having a single component.

## Implementation

As above. Whoever the implementer is can decide or we can discuss in the issue whether individual components or a single component is best.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by diegoevangelisti** [comment]
@joshxg 
So based on your thoughts the idea is to create, for example, `PieChart`, `LineChart`, `BarChart` components to manage them separately, right? I agree it is a good idea to keep neat components. Even if they have a **similar** skeleton they come with native props related with their purpose. 
In order to proceed do we need to split this issue into three?

**Comment by joshxg** [comment]
I think three components is the better way. I also think three issues is three issues better way!

**Comment by diegoevangelisti** [comment]
Great, I will do that then, and start working on it. Thanks!

**Comment by joshxg** [comment]
It may even work out that creating 4 components is nice - one for each chart, and then a single component which does the delegation to the correct chart. But go with three for now! 🤣
