### ISSUE TITLE
Replace "posigitive" to "positive" on select-a-reason modal and stocktake editing page

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#1771]
## Describe the bug
Wrong spelling of "positive" on select-a-reason modal and stocktake editing page

### To reproduce

1. Go to '...Menu page'
2. Click on 'Stocktake icon' ->  one of un-finalized stocktake item -> type a quantity on actual quantity column that is larger than it is on snapshot quantity -> also see "posigtive" error/wrong spelling on select-a-reason modal when it pops-up

<img width="776" alt="Screen Shot 2019-12-23 at 3 29 25 PM" src="https://user-images.githubusercontent.com/57238075/71337296-e2098280-25af-11ea-9f3a-ccbb997f6f37.png">
<img width="800" alt="Screen Shot 2019-12-23 at 3 28 58 PM" src="https://user-images.githubusercontent.com/57238075/71337311-ec2b8100-25af-11ea-9986-7010ca6690bb.png">

### Expected behaviour
See right spelling of positive across pages

### Proposed Solution
Replace spelling of "posigtive" with "positive" in string files that contain the word "posigtive". 

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by joshxg** [comment]
hi @Rebecca367 this is synced from your server. This is an Option:

![image](https://user-images.githubusercontent.com/35858975/71382592-81288b80-263d-11ea-8eac-02f83b1abc86.png)


In order to fix the spelling here just double click on the option and change the name here. This is a data file issue, rather than a code base issue! :)

**Comment by Rebecca367** [comment]
Thank you for being prompt on solving the issue.
