### ISSUE TITLE
Add indicator toggle logic

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1829]
## Is your feature request related to a problem? Please describe.

Add actions/reducers for managing items/indicators toggle state.

## Describe the solution you'd like

See above.

## Implementation

Add page actions/reducers, following existing design pattern.

## Describe alternatives you've considered

EDIT: scope of this issue has been updated, but leaving discussion for reference.

Thoughts would be that it would be nice to make a hierarchy of actions separated by "domains" which are a bit more fine grained than page, e.g. `actions/pages/requisition/indicators`. Understand that current implemented was chosen as pages share a lot of common logic (could also have `actions/pages/general` for this?).

@joshxg You know more than me re. current flux pattern? What do you think? What's the pattern you're going for in the dispensing feature?

## Additional context

See epic #1685.

**Comment by joshxg** [comment]
This is part of a wider discussion needed, I'll try keep it brief:

- Yes, all/most pages share nearly all logic. This simply makes it difficult because if you have `SupplierRequisition` reducer and actions, then it is difficult to share logic, as your action type is "sort" and each reducer in `SupplierRequisition`, `SupplierInvoice` etc, have a case for 'sort'. Since we can have multiple pages rendered at one time, this will cause issues.

In general the whole shape should possibly change: rather than page reducers, have a `SearchTermReducer` - and make the domains of each reducer far smaller. This was attempts with the cell/row/table etc etc. but that still doesn't solve the case where multiple pages are controlled by the `SearchTermReducer` for their filtering and both re-rendering!

----

As for this specific issue:

I really only see 1? maybe a couple more actions being needed, so I think just using `CellActions` is fine.

**Comment by wlthomson** [comment]
> This is part of a wider discussion needed, I'll try keep it brief:
> 
>     * Yes, all/most pages share nearly all logic. This simply makes it difficult because if you have `SupplierRequisition` reducer and actions, then it is difficult to share logic, as your action type is "sort" and each reducer in `SupplierRequisition`, `SupplierInvoice` etc, have a case for 'sort'. Since we can have multiple pages rendered at one time, this will cause issues.
> 
> 
> In general the whole shape should possibly change: rather than page reducers, have a `SearchTermReducer` - and make the domains of each reducer far smaller. This was attempts with the cell/row/table etc etc. but that still doesn't solve the case where multiple pages are controlled by the `SearchTermReducer` for their filtering and both re-rendering!
> 
> As for this specific issue:
> 
> I really only see 1? maybe a couple more actions being needed, so I think just using `CellActions` is fine.

Yeah, have thought about it some more and mostly agree.

I think the idea I'm going for would to extract out the data table logic, which is currently quite closely linked with the general page etc. logic. I can't think of a pattern right now, but a way of splitting common actions/reducers for functionality from common actions/reducers for data table manipulation (e.g. editing cells) is the kind of thing I am thinking. It definitely does require a wider discussion, though.

**Comment by wlthomson** [comment]
Fixed by #1841.
