### ISSUE TITLE
TESTING: Indicators 

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#1935]
# Indicator tests

## Setup

To set up indicators on desktop, follow the instructions for setting up programs [here](https://docs.msupply.org.nz/items:programs). To generate HIV indicators, click the “HIV program” checkbox and click OK (regimen indicators are generated automatically).

To create indicator values for the mobile store, login to another store on desktop and create an internal order for the mobile store (i.e. set the mobile store as the supplier). Navigate to the indicators tab and update some values. Finalising the requisition will trigger the creation of indicator values for the mobile store.

### Performance

Note: due to the amount of values being rendered when viewing indicators, performance can sometimes be slow (and occasionally React may even crash). If anything is very slow or crashes occur more than once, fail the respective issues below:

- [ ] Indicators performance is notably slow.
- [ ] Indicators are crashing.

### Requisitions

- [ ] Supplier requisitions for programs with indicator data create successfully.
- [ ] Supplier requisitions for programs without indicator data create successfully.
- [ ] Supplier requisitions without programs ("general") create successfully.

### Viewing indicator data

- [ ] The indicator toggle correctly toggles between item and indicator data.
- [ ] The indicator dropdown correctly toggles between different sets of indicator data.
- [ ] Indicator rows cannot be reordered.
- [ ] New HIV indicator values default to `0`.
- [ ] New regimen indicator values default to `""` (i.e. empty).

### Editing indicator data

- [ ] Clicking on an indicator value cell allows that value to be edited.
- [ ] After editing a value, the value is retained in the cell.
- [ ] After toggling between different indicators, previously entered values are retained.
- [ ] After toggling between indicators and items, previously entered values are retained.
- [ ] After closing and reopening a requisition, previously entered values are retained.

### Syncing indicator data

NOTE: synced data can be viewed in the data explorer. 

- [ ] Indicators sync to mobile.
- [ ] Indicator attributes sync to mobile.
- [ ] Indicator values sync to mobile (see setup).

**Comment by diegoevangelisti** [comment]
# Indicator tests

## Setup

To set up indicators on desktop, follow the instructions for setting up programs [here](https://docs.msupply.org.nz/items:programs). To generate HIV indicators, click the “HIV program” checkbox and click OK (regimen indicators are generated automatically).

To create indicator values for the mobile store, login to another store on desktop and create an internal order for the mobile store (i.e. set the mobile store as the supplier). Navigate to the indicators tab and update some values. Finalising the requisition will trigger the creation of indicator values for the mobile store.

## Test cases

### Performance

Note: due to the amount of values being rendered when viewing indicators, performance can sometimes be slow (and occasionally React may even crash). If anything is very slow or crashes occur more than once, fail the respective issues below:

- [x] Indicators performance is notably slow.
- [x] Indicators are crashing.

### Requisitions

- [x] Supplier requisitions for programs with indicator data create successfully.
- [ ] Supplier requisitions for programs without indicator data create successfully.
- [ ] Supplier requisitions without programs ("general") create successfully.
**Failed** It's not creating a General Program requisition properly. It _seems_ to have no problems at the very beginning, but after creating one, instead of opening the new requisition page it's directing me to the Suppliers Requisition page and showing up an error.
![Indicators1](https://user-images.githubusercontent.com/32987464/72566001-e3f90400-3917-11ea-8dc9-5b5e3260402c.gif)
 
See errors here:


### Viewing indicator data

- [ ] The indicator toggle correctly toggles between item and indicator data.
- [ ] The indicator dropdown correctly toggles between different sets of indicator data.
- [ ] Indicator rows cannot be reordered.
- [ ] New HIV indicator values default to `0`.
- [ ] New regimen indicator values default to `""` (i.e. empty).

### Editing indicator data

- [ ] Clicking on an indicator value cell allows that value to be edited.
- [ ] After editing a value, the value is retained in the cell.
- [ ] After toggling between different indicators, previously entered values are retained.
- [ ] After toggling between indicators and items, previously entered values are retained.
- [ ] After closing and reopening a requisition, previously entered values are retained.

### Syncing indicator data

NOTE: synced data can be viewed in the data explorer. 

- [ ] Indicators sync to mobile.
- [ ] Indicator attributes sync to mobile.
- [ ] Indicator values sync to mobile (see setup).

**Comment by diegoevangelisti** [comment]
@wlthomson 
These are the issues created regarding failed tests:
#1951 (Thanks @joshxg) 
#1953
#1954

**Comment by wlthomson** [comment]
> @wlthomson
> These are the issues created regarding failed tests:
> #1951 (Thanks @joshxg)
> #1953
> #1954

Awesome! Thanks @diegoevangelisti and @joshxg. Will get on them now. Guesstimate is to have them all done by end of the day, will keep the release discussion updated.

**Comment by wlthomson** [comment]
Closing as this round of testing is completed.

**Comment by wlthomson** [comment]
Updated for `v5.0.0`.

**Comment by diegoevangelisti** [comment]
**Testing in progress**

## Test cases

### Performance

Note: due to the amount of values being rendered when viewing indicators, performance can sometimes be slow (and occasionally React may even crash). If anything is very slow or crashes occur more than once, fail the respective issues below:

- [ ] Indicators performance is notably slow.
- [ ] Indicators are crashing.

### Requisitions

- [ ] Supplier requisitions for programs with indicator data create successfully.
- [ ] Supplier requisitions for programs without indicator data create successfully.
- [ ] Supplier requisitions without programs ("general") create successfully.

### Viewing indicator data

- [ ] The indicator toggle correctly toggles between item and indicator data.
- [ ] The indicator dropdown correctly toggles between different sets of indicator data.
- [ ] Indicator rows cannot be reordered.
- [ ] New HIV indicator values default to `0`.
- [ ] New regimen indicator values default to `""` (i.e. empty).

### Editing indicator data

- [ ] Clicking on an indicator value cell allows that value to be edited.
- [ ] After editing a value, the value is retained in the cell.
- [ ] After toggling between different indicators, previously entered values are retained.
- [ ] After toggling between indicators and items, previously entered values are retained.
- [ ] After closing and reopening a requisition, previously entered values are retained.

### Syncing indicator data

NOTE: synced data can be viewed in the data explorer. 

- [ ] Indicators sync to mobile.
- [ ] Indicator attributes sync to mobile.
- [ ] Indicator values sync to mobile (see setup).

**Comment by joshxg** [comment]
@wlthomson 

Hey are you able to take a look at this one - I created a supplier requisition and was playing around and had some values in the indicator table, then when I created a new customer requisition the values were populated with those from the supplier requisition 🤔

**Comment by wlthomson** [comment]
> 
> 
> @wlthomson
> 
> Hey are you able to take a look at this one - I created a supplier requisition and was playing around and had some values in the indicator table, then when I created a new customer requisition the values were populated with those from the supplier requisition 🤔

Keeping this open to be revisited after `v7` release.

**Comment by nishaSussol** [comment]
# Indicator tests
Tested in v8.0.0.RC2

## Setup
To set up indicators on desktop, follow the instructions for setting up programs [here](https://docs.msupply.org.nz/items:programs). To generate HIV indicators, click the “HIV program” checkbox and click OK (regimen indicators are generated automatically).

To create indicator values for the mobile store, login to another store on desktop and create an internal order for the mobile store (i.e. set the mobile store as the supplier). Navigate to the indicators tab and update some values. Finalising the requisition will trigger the creation of indicator values for the mobile store.

## Test cases
### Performance
Note: due to the amount of values being rendered when viewing indicators, performance can sometimes be slow (and occasionally React may even crash). If anything is very slow or crashes occur more than once, fail the respective issues below:
- [x] Indicators performance is notably slow.
- [x] Indicators are crashing.

### Requisitions
- [ ] Supplier requisitions for programs with indicator data create successfully.
Hi @joshxg @wlthomson 
1. Here's a screenshot of a supplier requisition created from mobile with some indicator values:
![Screenshot_2021-03-22-13-02-57-671](https://user-images.githubusercontent.com/59193490/111954373-18fe7900-8b10-11eb-8dbc-852f75dfb94a.jpeg)

And, below is the customer requisition received in desktop site:
![Screen Shot 2021-03-22 at 1 09 30 PM](https://user-images.githubusercontent.com/59193490/111954412-2c114900-8b10-11eb-8847-ccbf0a02f2dc.png)

Notice that the different values there in same corresponding requisitions?

2. 
>
>To create indicator values for the mobile store, login to another store on desktop and create an internal order for the mobile store (i.e. set the mobile store as the supplier). Navigate to the indicators tab and update some values. Finalising the requisition will trigger the creation of indicator values for the mobile store.
> 
Following this setup, Created a IO from desktop site to mobile (mobile being the supplier). In mobile, while checking that customer requisition, the toggle for `Customer Data` and `Supply Data` is shown under `Indicators`, which basically does nothing. Check it [here](https://user-images.githubusercontent.com/59193490/111955794-14d35b00-8b12-11eb-9c2e-1f0aef913cf0.mp4)
Shouldn't those (`Customer Data` and `Supply Data` toggles) be hidden when `Indicators` is selected?


- [ ] Supplier requisitions for programs without indicator data create successfully.
- [ ] Supplier requisitions without programs ("general") create successfully.

### Viewing indicator data

- [ ] The indicator toggle correctly toggles between item and indicator data.
- [ ] The indicator dropdown correctly toggles between different sets of indicator data.
- [ ] Indicator rows cannot be reordered.
- [ ] New HIV indicator values default to `0`.
- [ ] New regimen indicator values default to `""` (i.e. empty).

### Editing indicator data

- [ ] Clicking on an indicator value cell allows that value to be edited.
- [ ] After editing a value, the value is retained in the cell.
- [ ] After toggling between different indicators, previously entered values are retained.
- [ ] After toggling between indicators and items, previously entered values are retained.
- [ ] After closing and reopening a requisition, previously entered values are retained.

### Syncing indicator data

NOTE: synced data can be viewed in the data explorer. 

- [ ] Indicators sync to mobile.
- [ ] Indicator attributes sync to mobile.
- [ ] Indicator values sync to mobile (see setup).

**Comment by joshxg** [comment]
Thanks a lot @nishaSussol !

@wlthomson do you have time to take a look at this ?
