### ISSUE TITLE
Add cash register reducer for modal state

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2022]
## Is your feature request related to a problem? Please describe.

Currently cash register state is managed with a combination of memoisation and `useState`. This is a bit messy and could be improved with a dedicated cash register reducer and `useReducer`.

## Describe the solution you'd like

Add cash register reducer and refactor state management to use `useReducer` hook.

## Implementation

See above. 

## Describe alternatives you've considered

N/A.

## Additional context

See epic #1917.

**Comment by wlthomson** [comment]
This one is my fault, for never getting around to tidying up cash register! Prioritising this for `5.1`.

**Comment by wlthomson** [comment]
Fixed by #2867.

**Comment by ArpitaSussol** [comment]
Tested in 5.1.1

## Testing

- [ ] On "New Transaction", cash transaction modal is displayed.
  - [ ] Toggle is set to "Cash In"
  - [ ] All fields display placeholder text.
- [ ] Can toggle between cash in and cash out.
  - [ ] When toggling between cash in and cash out, fields are persisted (i.e. not reset). 
- [ ] Transaction constraints are correctly enforced.
  - [ ] Confirm button is DISABLED for any cash IN transaction without a name, positive amount, payment type.
  - [ ] Confirm button is DISABLED for any cash OUT transaction without a name, positive amount, payment type.
  - [ ] Confirm button is NOT DISABLED for an otherwise valid cash IN transaction without a reason.
  - [ ] Confirm button is DISABLED for an otherwise valid cash OUT transaction without a reason.
  - [ ] Confirm button is ENABLED and CAN make a cash IN transaction for more than current cash balance.
  - [ ] Confirm button is ENABLED but CAN NOT make a cash OUT transaction for more than current cash balance. 
- [ ] Can create cash transactions.
  - [ ] When cash in transaction is created, it appears under receipts.
  - [ ] When cash out transaction is created, it appears under payments.
