### ISSUE TITLE
Portugese language support

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2115]
## Is your feature request related to a problem? Please describe.

We don't currently support portugese

## Describe the solution you'd like

To support portugese

## Implementation

This can probably be split over a few issues!

- Add a portugese language code, flag and add it to the modal selection for languages on the login page.
- Add the portugese code to all the `JSON` files
- export the localization files, add the translations and reimport!

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2337

**Comment by Rebecca367** [comment]
## Testing

Sync window shows sync manual which is in English. 
Google translation shows 
<img width="668" alt="Screen Shot 2020-03-16 at 10 45 32 AM" src="https://user-images.githubusercontent.com/57238075/76711311-b42d7780-6773-11ea-9087-51a4aa9f9cdd.png">

<img width="668" alt="Screen Shot 2020-03-16 at 10 45 32 AM" src="https://user-images.githubusercontent.com/57238075/76711305-9e1fb700-6773-11ea-8af3-f095d48f1f14.png">

Steps to reproduce or otherwise test the changes of this PR:

- [x] Check that "Português" can be selected in the languages menu
- Check that Portuguese strings are not being cut in:
  - [ ] Initial setup (to select which store to sync) window
=> Is it needed to be tested in Mobile or desktop?

  - [x] Main window buttons
  - [FAILED ] Sync window
  - [x] Login window
  - [x] Stocktakes list window
  - [x] New Stocktake window
  - [x] Customer Invoices list window
  - [x] New Customer Invoice window
  - [x] Customer Requisitions list window
  - [x] New Customer Requisition window
  - [x] Supplier Invoices list window
  - [x] New Supplier Invoice window
  - [x] Supplier Requisitions list window
  - [x] New Supplier Requisition window
Not able to produce for some set-up reasons.
Good hard work on translation @nmadruga, this test item is mostly done since no special representation required by modules setting.

  - [ ] Dashboard(?)
  - [ ] Dispensary patients list window
  - [ ] Dispensary prescriptions list window
  - [ ] Dispensary New patients window
  - [ ] Dispensary New prescription window
  - [ ] Any other places?

**Comment by nmadruga** [comment]
Hi @Rebecca367 Thank you for testing all of this.

>  Initial setup (to select which store to sync) window
  => Is it needed to be tested in Mobile or desktop?
For Mobile

> Manual de sincronização
That Google is not a very good translator yet... The meaning of that is 'User guide of sync'. Which is not a good translation for 'Sync Manual' hahah I'm pretty sure I've translated that string. I'll find out in the code now. But if it's not translating it should be something on the code where is in use.

**Comment by nmadruga** [comment]
Here it is:
[manual_sync: Sync Manual](https://github.com/openmsupply/mobile/pull/2337/files#diff-571a63ad2a8bcc0ce8cecd49d5d9c8d5R65)

I have decided to use the short version of 'Sync' for Portuguese since it's reasonable comprehensive from the user point, imo. And you might thing it's odd that the order is inverted: `Manual Sync` to `Sync Manual` but that's what happen in a lot of Portuguese sentences compared to English. : )

Please check on the code where the sync_manual string is in use to see why it might not be using the correct translation. Or perhaps it is! You might have though that `Sync Manual` was in English, but that's the correct Portuguese translation.

**Comment by Rebecca367** [comment]
@nmadruga 
I believe google translator still needs to be modified..
Google translator misled me ..err..
