### ISSUE TITLE
There are item quantity present 0 in SupplyInvoicePage after invoices being finalized.  

### ISSUE THREAD

**Issue by Rebecca367** [openmsupply/mobile#2286]
## The suggestion
There are items with 0 quantity left on SupplierInvoicePage after it is been finalized, so it's better to waive items those items that present 0 from the invoice as what users might expect.

**Why?**
It is better to leave items that don't have any quantity out of invoice for other items with quantities on the invoice as expected behaviour.

## Describe alternatives you've considered
none

## Additional context

none

**Comment by joshxg** [comment]
@Rebecca367 

With these lines:

https://github.com/openmsupply/mobile/blob/6e8136fab35bc8c94b46b56e4b0e1d75db60db5a/src/database/DataTypes/Transaction.js#L437-L439

- We can see we only prune (remove 0 quantity lines) if the invoice is not an internal order.
- This is because one person is saying "I sent you X amount" on the customer invoice on one store.
- The supplier invoice on the mobile store is confirming that X was sent.
- So, if one side is saying "I sent X", but actually the mobile store received X-Y, we have to record that. Even if X == Y - so that we can record that none were received.

Hope that makes sense

**Comment by Rebecca367** [comment]
@joshxg 
got it! OK.
