### ISSUE TITLE
Stock line expiry date can set to old year date

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#2301]
## Describe the bug

Found this while testing with this mobile version: v4.00.rc7  where you can set expiry date to old year date (2004) which it should not be possible as it will look like - Issuing out an expired item to patient.

### To reproduce

1. Mobile version v4.00.rc7 
2. Add a stock line
3. Type expiry date as : 31/04

### Expected behaviour

It should not allow setting the old year date

### Proposed Solution

Don't allow 

### Version and device info

- App version: v4.00.rc7 
- Tablet model: Samsung 4.4.4
- OS version: Andriod

### Additional context

This needs discussion whether it is OK to set or not

![photo_2020-02-13_14-12-22](https://user-images.githubusercontent.com/13144882/74415480-8cdd4500-4e6b-11ea-958c-d51cdf404bd0.jpg)

**Comment by joshxg** [comment]
Because this is also possible in desktop I'm not sure if we should restrict this in mobile 

![image](https://user-images.githubusercontent.com/35858975/74581949-affa2700-501a-11ea-89dc-dc006e0d0dcf.png)

![image](https://user-images.githubusercontent.com/35858975/74582022-4fb7b500-501b-11ea-81c2-21ba39de418b.png)

except the date picker only has later years...

![image](https://user-images.githubusercontent.com/35858975/74582031-5d6d3a80-501b-11ea-9310-82c8340520d0.png)

I think we might leave this on second thought @bijaySussol ?

Not sure who would have an idea about this.. probably bossman @craigdrown

**Comment by craigdrown** [comment]
@joshxg  @bijaySussol  - you should be able to set an expired date (you can in desktop). If you receive expired stock or stocktake expired stock, you have to be able to enter the date. Can close.
