### ISSUE TITLE
Limitations when interacting with an incompatible server

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2380]
## Is your feature request related to a problem? Please describe.

Some versions of mobile are incompatible with older versions.

1. *Incompatible schemas*: For example if there exists a table `[X]` on desktop V5.0 - and in a new version of desktop V5.1 introduces field `[X]fieldn` and a mobile site tries to send this record with the `[X]fieldn` (undefined, or defined) - the record will be rejected. Since push occurs first - sync then stops.
2. *Differences in values / general backwards incompatibilities*: For example - if `[transact]total` starts to get calculated differently in a new V5.1 than V5.0 - then the versions are not compatible.

note: As we use semantic versioning, this means a major version pump

## Describe the solution you'd like

Ideally: Shouldn't even be able to install the new mobile version.
Practically: Stop sync from working if the server is not compatible. Bug snag then error.

## Implementation

1. Send a field in responses from the server for example [here](https://github.com/sussol/msupply/blob/18548c9f92a6ae7d859cc1aa142de60fc8c0018f/vc_methods/REST_get_records.txt#L2235-L2236) which gives the servers version. The mobile version then sets a flag - allowing/disallowing sync to occur.
    - Pros:
        - Simple to implement
    - Cons:
        - Not a very nice solution!
        - Adds overhead to all(?) fetches [for example: if you only do it on login - you might not be connected to the internet when logging in]

2. Create an endpoint(s) `/version` which could tell you the servers version, incompatibilities, compatible versions etc (I dunno)
    - Pros:
        - Very extensible
        - Could use to query all servers on a server so we can get an up-to-date picture etc
    - Cons:
        - Not too quick
        - Possibly functionality that nicole's hub would be doing?

3. Bump the rest api end point
    - Pros:
        - RESTful! - semantically correct
        - Don't need to send an auth request on every request
    - Cons:
        - Time [Will this actually take extra time?]

4. Mobile sends it's version - server validates
    - Pros:
        - Fast to implement
        - Reduce the number of queries
    - Cons:
        - Desktop tracks what versions of other applications it is compatible with

## Alternatives

- Make the sync API (either mobile or desktop) more backwards compatible. It might be easier for desktop to just integrate a record which has 'extra' fields. However this still doesn't solve the case of 'general' backwards incompatibilities.

## Additional context

Specifically, this is for mobile version `4.0.0` being incompatible with `<4.09` on desktop. So, if any desktop work needs to be done, it would need to be done very quickly.

**Comment by joshxg** [comment]
- Personally I prefer option 1 for right now as it is a simpler solution.
- Option 2 I think would be a better end point on nicoles hub(?)

**Comment by craigdrown** [comment]
I vote for i, but with proviso that the code grabs the version from storage rather than making another maintenance point in the code (with some thought to performance if it's called a lot)

**Comment by joshxg** [comment]
Following from @craigdrown 

When do we get the version from the server? Send a message on upgrading. The message could be in the already-implemented mobile-upgrade`[Message]` which tells the server to send the version. 
How do we receive the version? In another message. But we push before pull - so we could start pushing records before stopping sync.

Am I not thinking this through?

**Comment by nmadruga** [comment]
The mSupply Hub is meant to be a server that has it's own API and that many mSupply servers sends data to it. So no new endpoints on the mSupply sever are going to be added. mSupply will run schedulers to push the data periodically (daily) and more often when that server is presenting important errors that we will have to log and then it should be sent immediately to the mSupply Hub server. So not exactly the same as the option 2.

**Comment by joshxg** [comment]
@nmadruga I meant that there could be an endpoint on your hub which mobile could query for the server version - instead of putting an end point on the mSupply server itself. It seems to make more sense to me? But that would def be too much work - more that if we are going to do an endpoint it seems to make more sense there - so lets do the easy option now hehe

**Comment by nmadruga** [comment]
I think it's wise to have implemented in mSupply

> desktop to just integrate a record which has 'extra' fields

 to allow more flexibility between mSupply mobile and Desktop versions. That a very likely possibility since we can't upgrade all Mobile sites and Desktop at the same time (specially in countries using Satellite sites). And it's wiser than to have a special order to do those upgrades.

But for now, because version 4.09 is on it's way probably just working on Option 1 on Mobile. Adding a message about what `Sync error` that happened.

**Comment by nmadruga** [comment]
> @nmadruga I meant that there could be an endpoint on your hub which mobile could query for the server version - instead of putting an end point on the mSupply server itself. 

That's a possibility, let's think more about it for the future.

**Comment by wlthomson** [comment]
As I understand it, the general way for handling backwards incompatibility is to use semantic versioning (which I believe we use for mobile and are moving towards using on desktop)? I.e. if any changes are made to the schema or API that make desktop incompatible with an existing or previous version of mobile, the major version is bumped. 

As I understand it we already use some sort of versioning for our api endpoints? I think a common solution is to also "bump" the API endpoints when major versions are released. 

E.g. currently all mobile versions use `sync/v3` as their endpoint. For future, it might be a good idea to start incrementing endpoints for new versions of mobile? That way each mobile version will query its compatible API and the compatibility logic can be handled by mSupply consistently?

I think the second option is closest to this, and I think it would be the least work in the long term to maintain. The reason I like versioning APIs is that it is consistent with the specification that REST services should be stateless (i.e. the semantics of a request should have nothing to do with something returned by another request), so you technically shouldn't be setting a flag on mobile, but should be querying the endpoint or header/payload every time. I think this is why the general approach is to version the API (or use something like GraphQL! 😃 ).

Also, by making API bumping part of the major version bump process (e.g. we already do this for migration code) we would be putting in place a process which is a lot more robust and extensible. 

Just my 2c, but I don't think either option has major flaws.

**Comment by andreievg** [comment]
@wlthomson we talking about server not being upgraded (in most other systems, server is the first thing to get updated, we don't have control over that because we are not dealing with one central server). 

@joshxg 
With 1, I think the server would need to add version to at least:
* initial auth (happens before on initial authorisations, before asking server to create sync outs for the whole site):`sync/v3/site` 
* when pushing records `POST` to `/sync/v3/queued_records/`

I think existing error handlers in mobile would handle this correctly (on initialisation should show error at the bottom, and show the sync error in the manual sync modal)

Quick way for option 2 is to introduce new route in V4 api. But would still require mobile changes.

Since minimum changes come from version 1, I vote for that one

**Comment by andreievg** [comment]
As for overhead, it's minimum (bandwidth wise, http already has plenty of overhead, new header wont' really affect it) and setting and checking version on both sides in also minimum (compared to other operations we perform).

**Comment by wlthomson** [comment]
@andreievg 

I don't understand. The order of upgrade doesn't matter? If mobile gets bumped and is backwards incompatible, you surely can't release it if there are no versions of desktop that are compatible? When the desktop version that is compatible is released, you bump the API and set that as the API mobile has to use. 

If mobile queries that API and gets no response, it knows it can't use that version of mSupply? 

My main point is that neither of the proposed options are RESTful or will require a constant overhead on every request. Mobile code will also have to be maintained, as mobile will need to know what versions of mSupply it is compatible with? 

My other point was we already have `4` API versions, so shouldn't we commit to our existing architecture rather than breaking the RESTfulness of our endpoints with a (bit of a messy) workaround?

**Comment by andreievg** [comment]
Oops just realised option 1 has potential of trying to integrate records that are incompatible.
Soo looks like option 2 is safer.
* Add api call for version in v4
* If API call fails or version is incompatible
  * During initial auth, show on log in page that it's incompatible 
  * During synchroniser push or pull, make sure error is displayed in manual push window
  * Would be great to have exclamation mark on the sync icon, not sure if this is within scope though

**Comment by joshxg** [comment]
> Oops just realised option 1 has potential of trying to integrate records that are incompatible.
Soo looks like option 2 is safer.

can you elaborate?

**Comment by mark-prins** [comment]
I'd vote (1) because it is quick and simple and does the job.

Not a final solution - as it would be good to have it more flexible, something like the `/version` or a `/capabilities` endpoint ( one which tells the client what the server supports ) so that some sync records could make it through rather than blocking sync entirely.

**Comment by andreievg** [comment]
@joshxg sorry should have been more specific

Desktop serve is not on 409
Mobile has just been upgraded

* User logs in (off line) after upgrade
* Connection is resumed
* Sync starts to happen
* Mobile tries to push, and desktop tries to integrate records, which fails with an error code
* Mobile can still show it as an error because of incompatibility issue, we just beed to check the header in both the error catch and on success (in Synchroniser.js), I guess it's not a biggy, but it's not that clean.

**Comment by joshxg** [comment]
Hve updated with option 3 - bumping the api version.

Ah right. So what was listed in the cons of option1, sorry - yes using either option 1 or 2 will require either sending essentially an auth request first. 

Option 4. Mobile sends it's version as a custom header and the server decides if it's OK or not. Won't require an initial auth request first.

- Option 1 [server replies with it's version] is fastest and definitely not clean nor a complete solution.
- Option 2 [New end point on msupply server] Is fast (?) but I personally don't think it's very clean either nor a complete solution
- Option 3 [Bump API version] I think this is a complete solution (Can integrate some records and make it so that there is backwards compatibility in a lot of cases) and clean. I also think this shouldn't take very long - for now we could just route the requests to the existing methods, no?
- Option 4 [Mobile sends version and server validates] I think this is as fast as option 1, just as dirty and just as incomplete. Pro of not needing an extra request. Con of having desktop keep a track of all applications it is compatible with..


Option 1 and 4 are the simple solutions if option 2 and 3 are too big to do - tempted to say option 4

I think Option 3 is the long term solution- @andreievg how much work is re-routing the requests..? It doesn't seem like much work? Then, Mobile could just get a 404 and when it does - says not compatible?

Option 2 seems like just as much work to me as option 3? But not as nice?

**Comment by nmadruga** [comment]
For me Option 3 is the one that seems to be the best. If well thought might be safe to be done still in time. So to clarify... If we bump API version to a new route v4, does that means that all mobile API calls would be re-routed to that one or they would be still using v3? For example, a mSupply Desktop gets updated to v4.09, but mobile sites are still using v2.1 mSupply Mobile. So those requests are still going to be using v3 route? What about the incompatibility with table fields:
> _Differences in values / general backwards incompatibilities_

**Comment by andreievg** [comment]
This is getting a bit out of hand, in terms of volume of discussion. 

Option 3, is a lot of work have a look at route_oldRouter.
Option 4, doesn't solve this issue (when server is lower than 409 and mobile on new dispensing version).

To avoid taking further time from anyone, 10minutes meeting pls, i'll telegram

**Comment by joshxg** [comment]
for the record, I prefer this discussion format.

- Oops you're right - I guess we can rule option 4 out.
- I asked how much work option 3 would be since you know that code well. If it's too much work for right now, feel free to let us know! However it is surely still the most complete solution for the long term? If so - the question becomes: should we go with option 1 or option 2 as the simpler, short term solution? We seem split :)

**Comment by andreievg** [comment]
Sweet, option 1, but we re-authenticate before every synchronisation

**Comment by andreievg** [comment]
and for anyone that's interested, check out rest_get_record and rest_put_record in desktop

**Comment by joshxg** [comment]
For some info and to make sure I understand:

- Option 1: Seems I wasn't quite clear sorry! Suggestion was meant to be to send some sort of `authentication` request where the server returns the servers version which would be sent before `push()`. This seems like the easiest solution so we're gonna go with that. Using `initial auth`
- Option 2: Just as good as option 1, just maybe slightly more work.
- Option 3: Apparently 2 weeks work minimum. I think we all agree that this is the best solution though!
- Option 4: Doesn't work !!

**Comment by joshxg** [comment]
Just went to implement this and of course there's an unexpected problem :) 

When hitting the initial auth end point the server version is only returned when successfully auth'd - which means having the user enter the password as the server expects it in plain text.

So:
- Return the server version in the user authentication body/headers
- Use option 2

**Comment by joshxg** [comment]
Closed by #2407
