### ISSUE TITLE
 Add a Programme column in the following list displays: Requisition, Invoices, Stocktakes

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/mobile#2386]
## Is your feature request related to a problem? Please describe.

Place holder issue for Emily's comments from Super User Training from GTT:
Add a Programme column in the following list displays: Requisition, Invoices, Stocktakes

**Comment by mark-prins** [comment]
Let's do it - with the condition that the program column only shows for clients that are using program functionality

**Comment by Rebecca367** [comment]
@DhanyaHerath 
Have a look at it. There are already program inquiry in [stock_take]input.
<img width="616" alt="Screen Shot 2020-03-18 at 3 30 29 PM" src="https://user-images.githubusercontent.com/57238075/76919619-4c6f5c00-692e-11ea-986a-1cdd6c1b4b75.png">
There are program searching mechanism to search for program in requisition.
<img width="1028" alt="Screen Shot 2020-03-18 at 3 31 53 PM" src="https://user-images.githubusercontent.com/57238075/76919703-84769f00-692e-11ea-82cf-984132f182b8.png">
Where to put program in customer and supplier invoice? as one of columns?
<img width="1028" alt="Screen Shot 2020-03-18 at 3 33 27 PM" src="https://user-images.githubusercontent.com/57238075/76919765-b12ab680-692e-11ea-88ef-e77291780190.png">
<img width="956" alt="Screen Shot 2020-03-18 at 3 34 07 PM" src="https://user-images.githubusercontent.com/57238075/76919778-bee03c00-692e-11ea-85a8-2f765275504c.png">
Maybe to clarify these questions with Emily first before working on it?

**Comment by joshxg** [comment]
@Rebecca367 wrong repo

**Comment by DhanyaHerath** [comment]
@Rebecca367 Hi Rebecca, those screenshots are from desktop, you would want to check mobile (note the repository that this issue is in)

**Comment by Rebecca367** [comment]
Oh man, so confusing

**Comment by wlthomson** [comment]
Fixed by #2695.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Customer requisitions page includes program column if at least one current or past requisition has an associated program. **--PASSES--** 
- [x] Supplier requisitions page includes program column if at least one current or past requisition has an associated program. **--PASSES--** 
- [x] Stocktakes page includes program column if at least one stocktake has an associated program. **--PASSES--** 
- [x] Customer invoices page includes program column if at least one current or past invoice has an associated program. **--PASSES--** 
- [x] Supplier invoices page includes program column if at least one current or past invoice has an associated program. **--PASSES--**
