### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2449]
## Describe the bug

The label for the settings button is not translated

### To reproduce

Internal code error: https://github.com/openmsupply/mobile/blob/f33d9d04b4680f3b1a89c5d1c56c3595892c49bd/src/pages/MenuPage.js#L161

### Expected behaviour

Should be translated

### Proposed Solution

Create a string in `buttonStrings.json` - then use that string in the menu page as linked above.

### Version and device info

- App version: 3.2+
- Tablet model: All
- OS version: All

### Additional context

N/A

**Comment by joshxg** [comment]
Closed by #2450

**Comment by Rebecca367** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

Change to French before logging in.
- [ ] Dispense, get to the item selection screen and check the label of the **Directions** entry
=> Where is this **Directions** entry?

- [x] Create or edit a *Factures réquisition* and check the text of the toggle to show all items
- [ ] Grant your user admin rights in mSupply and login. Check the button text for **Settings**. Should be correct in English
=> Have no idea how to grant mu user admin right in mSupply in mobile? Where is  **Settings** sorry?
- [ ] And *RÉGLAGES* in French
=>Sorry, Where do I expect to see this?

**Comment by mark-prins** [comment]
I responded too late. for the next tester:
- Directions entry is show in the [Dispensing to a patient](https://docs.msupply.foundation/fr:mobile:user_guide:dispensing#dispensing_to_a_patient) section
- [Granting admin rights](https://docs.msupply.foundation/en:mobile:user_guide:mobile_settings#permission_to_edit_mobile_settings)
- Réglages is in the [Settings](https://docs.msupply.foundation/fr:mobile:user_guide:mobile_settings) section

**Comment by ArpitaSussol** [comment]
Tested in 5.0.0 rc1

## Testing

Change to French before logging in.
- [ ] Dispense, get to the item selection screen and check the label of the **Directions** entry - **PASS**
- [ ] Create or edit a *Factures réquisition* and check the text of the toggle to show all items - **PASS**
- [ ] Grant your user admin rights in mSupply and login. Check the button text for **Settings**. Should be correct in English - **PASS**
- [ ] And *RÉGLAGES* in French - **PASS**

**Comment by nishaSussol** [comment]
## TESTING
Tested in mobile v5.0.0RC1

### Tests
- Grant your user admin rights in mSupply and login.
- [x] Check the button text for Settings. Should be correct in English **-PASS-**
- [x] And RÉGLAGES in French **-PASS-**
