### ISSUE TITLE
Add Spanish language and translate all strings

### ISSUE THREAD

**Issue by diegoevangelisti** [openmsupply/mobile#2464]
## Is your feature request related to a problem? Please describe.

Translate all English strings into Spanish and then add the language to the possible selectable choices in the Mobile version.

## Describe the solution you'd like

Translate all actual english strings (total number is 374), using the excel sheet provided by the export/import script.

## Implementation

- As mentioned, translate all strings.
- Add an empty object in all localization files: `"es": { }`
- Add `SPANISH` to `LANGUAGE_CODES`, `LANGUAGE_NAMES` and `LANGUAGE_CHOICE`
- Add the Spanish flag.
<img width="249" alt="Screen Shot 2020-03-04 at 4 42 57 PM" src="https://user-images.githubusercontent.com/32987464/75843157-414d0400-5e37-11ea-8ee4-66ecaab58998.png">

- Check other needed code changes.

## Describe alternatives you've considered

Doing nothing (no way)

## Additional context

The idea is to take advantage of many words that have been already translated for Desktop (take them from there) and keep consistency between both translations (Desktop and Mobile).

**Comment by joshxg** [comment]
Closed by #2480

**Comment by Rebecca367** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

To perform a complete testing, add all possible modules (Dashboard, Dispensary, etc.) before starting.

- [x] Go to Login page -> Language
- [x] Check that `Spanish` in among possible selectable options.
- [x] The flag of Spain is included and the option is selectable. 
![Screen Shot 2020-03-05 at 3 36 46 PM](https://user-images.githubusercontent.com/32987464/75942395-25109c00-5ef7-11ea-9ff0-21732d30a823.png)

- [x] Select Spanish, then see that the language changed as expected.
- [  ] Go through all pages and check there is no English words (all strings should be translated to Spanish).
There are quite a lot of  **REMOVER** in different pages? Google translates it to : 
**agente de mudanzas** in Spanish, other than that they all look not English to me.

![Screen Shot 2020-03-12 at 10 04 02 AM](https://user-images.githubusercontent.com/57238075/76463766-e3c54280-6448-11ea-919b-824d4c6a97b3.png)
![Screen Shot 2020-03-12 at 10 21 32 AM](https://user-images.githubusercontent.com/57238075/76465920-74048700-644b-11ea-9469-e327263dbb32.png)
![Screen Shot 2020-03-12 at 10 21 17 AM](https://user-images.githubusercontent.com/57238075/76465925-7830a480-644b-11ea-8516-f65e9bb07756.png)

**Comment by diegoevangelisti** [comment]
>   There are quite a lot of  **REMOVER** in different pages? Google translates it to :
>   **agente de mudanzas** in Spanish, other than that they all look not English to me.

Hey @Rebecca367 thanks for testing this one!
Remover (in Spanish) means remove (in English) 
I _reckon_, just guessing, you are translating `remover` from English into Spanish instead of Spanish into English

**Comment by Rebecca367** [comment]
@diegoevangelisti 
cool
