### ISSUE TITLE
Patient name with long text overlap with Title 

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#2467]
## Describe the bug

Patient name overlap with title with very long firstname/lastname

### To reproduce

1. Create a patient with a very long name
2. Click on Dispense
3. See error

![Screenshot_2020-03-04-11-23-34](https://user-images.githubusercontent.com/58979436/75850210-d2f44b80-5e0e-11ea-95c0-e667ff62f7de.png)
![Screenshot_2020-03-04-11-24-08](https://user-images.githubusercontent.com/58979436/75850216-d8519600-5e0e-11ea-80fb-15ab4bc24822.png)

### Expected behaviour

Patient name should be shown clearly without any overlap

### Version and device info

- App version: 4.0.0
- Tablet model:
- OS version:

### Additional context

raise while testing #2428

**Comment by joshxg** [comment]
Perfect! thanks @ArpitaSussol  :)!

**Comment by diegoevangelisti** [comment]
@joshxg 
Since the problem here is that there's not enough space for a long name that takes 2 lines, I purpose to change `numberOfLines={2}` to `numberOfLines={textLines}`and pass `textLines = {2}` for this Patient Name text. (and set `textLines: 2` as default)
Otherwise, If we still want to show 2 lines, I reckon a smaller fontSize can be used when the no. of chars exceeds 1 line (not the solution I like).

This is how they looks like:

- `textLines = {2}`

![Screen Shot 2020-03-06 at 12 48 14 PM](https://user-images.githubusercontent.com/32987464/76036420-e9cea580-5fa8-11ea-9e3e-f261c7fb4d81.png)

- `textLines = {1}` (solution)

![Screen Shot 2020-03-06 at 12 48 25 PM](https://user-images.githubusercontent.com/32987464/76036422-eb986900-5fa8-11ea-9f59-9837cca5ace4.png)

**Comment by joshxg** [comment]
Another alternative: use `elipsizeMode="tail"` and just truncate the name. You chose the patient, so you probably know who they are, pretty much. Worst case, you can click the pencil and see their full name there.

I'd rather not take up even more vertical space by having 2 lines, personally

Thoughts?

**Comment by diegoevangelisti** [comment]
Yep, yours it's an easier solution! But since `ellipsizeMode ` works together with `numberOfLines`, if this number is not reduced from 2 to 1, even truncating the text(something like `text.length > 45 ? text.substring(0, 45) : text`) we can't see those ellipses because there is still space to grow. 
This is the case when truncating when `numberOfLines = {2}`. What do you think?

![Screen Shot 2020-03-06 at 2 20 02 PM](https://user-images.githubusercontent.com/32987464/76040915-9dd62d80-5fb5-11ea-8f4f-259c231ea445.png)

**Comment by joshxg** [comment]
ohh yup

Just add `SimpleLabel` prop `numberOfLines` - and then use `SimpleLabel.defaultProps = { numberOfLines: 2 }` - then the behaviour is the same for everything, but you can override it ! I should have done this originally !

**Comment by joshxg** [comment]
Closed by #2493

**Comment by Rebecca367** [comment]
- [x ] Go to `Dispensary`
- [x ] Create a new patient with a long name  (at least greater than 50 chars in total)
- [ x] Click on Dispense option for that patient
- [FAILED ] See that the name fits in one line, it has ellipses at the end and it is not overlapping with the title: `Patient`.
=> The name is overlapping patient on my machine.
<img width="807" alt="Screen Shot 2020-03-24 at 1 47 59 PM" src="https://user-images.githubusercontent.com/57238075/77376913-77e2c280-6dd6-11ea-8830-ab760509c9a7.png">

- [x ] Click on ✏️ (Edit) icon and check that First Name and Last Name didn't change.

**Comment by diegoevangelisti** [comment]
@Rebecca367 Thanks for testing this one!
I will take a look and double check in my emulator before creating a new issue :-)

**Comment by Rebecca367** [comment]
@diegoevangelisti 
Great! I was thinking of creating a new issue for it, too but to the same thing might be better just to check on the same issue.

**Comment by ArpitaSussol** [comment]
Tested with 5.0.0-rc1

## Testing

- [ ] Go to `Dispensary` - **PASS**
- [ ] Create a new patient with a long name  (at least greater than 50 chars in total) - **PASS**
- [ ] Click on Dispense option for that patient - **PASS**
- [ ] See that the name fits in one line, it has ellipses at the end and it is not overlapping with the title: `Patient`. - **PASS**
- [ ] Click on ✏️ (Edit) icon and check that First Name and Last Name didn't change. - **PASS**
