### ISSUE TITLE
Patients don't get synced from the primary server

### ISSUE THREAD

**Issue by raviSussol** [openmsupply/mobile#2472]
## Describe the bug
Patients don't get synced from the primary server after checking `Resync patient records when store is saved` checkbox in the store > synchronisation tab and force sync from the mobile. Not sure but still anything missing??

### To reproduce
Log in to a dispensary store in the primary server
1. Go to a `Synchronisation` tab and unlock it
2. Check `Resync patient records when store is saved` checkbox to resync all existing patients from the primary server to the mobile
3. Now in the mobile, tab a force sync button and wait for a moment till sync completed
4. Open a dispensary and see no any patients have been synced yet

### Expected behaviour
All existing patients should get synced to the mobile

### Proposed Solution
It seems that mobile app does receives all existing patients from the primary server though but they all are hidden for some reason and get hidden while opening the dispensary in the mobile
See image attached:
![Screen Shot 2020-03-04 at 3 52 12 PM](https://user-images.githubusercontent.com/13145522/75877478-f4b9f680-5e3f-11ea-8a62-c6ea1b9f2f94.png)

### Version and device info

- App version: 4.0.0

**Comment by anildahalsussol** [comment]
@raviSussol : Hmm it can be due to name.supplying_store_id. Can you check once the supplying store id of those patients.

**Comment by raviSussol** [comment]
@anildahalsussol Not sure what you mean but I just checked their supplying store id and few of them have assigned to some random stores and rest are assigned to "".

**Comment by joshxg** [comment]
@anildahalsussol @raviSussol 

Only patients whose `supplying_store_id` is the store you are on should show. This is a middle step - We only want to issue to a patient in one store, because: 
- a patients credit - we don't want to have the credit used in many places.. then we can't track that properly. 
- Patient history: We don't want to have `Transaction` records syncing so much right now .. it is a lot of records and always mobile is assuming it only has the mobile `Transaction` records (1 store per 1 mobile site).. so it is a lot more changes to have other `Transaction`.
- #2446 - this is a issue to make a Patient Lookup API on desktop and have mobile send a request to that, to ask special permission to have a patient record from another store

sorry if this wasn't clear!!

**Comment by raviSussol** [comment]
@joshxg Ah sounds clear now... Also I just updated the `name.supplying_store_id` field of one of the mobile store (the one that Im using for testing) to its own logged in store id and force sync in the mobile. Now it shows all existing patients there... Thanks for the info bro! 👍

**Comment by raviSussol** [comment]
So @joshxg should I close this one or leave it till there is way come up in the mobile and the api is added in the desktop mSupply? Or I'll leave it to you for this one :-)

**Comment by joshxg** [comment]
Ah ... umm.. lets close it! thanks bro!
