### ISSUE TITLE
French wording changes

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2479]
## Is your feature request related to a problem? Please describe.

A few changes to the French translations and wording

- The language button should read `LANGUE` not `Langage`
- The button string for `all_items_selected` needs a line break before *sélectionnés*
- The button string for `hide_stockouts` requires a line break before *de stocks*
- The sync string for `sync_enabled` should be UPPERCASE - `SYNC ACTIVÉ`
- The settings save button is hard coded to `Save Changes` and needs translating

## Describe the solution you'd like

Some changes

**Comment by joshxg** [comment]
I just put the target as 4.1 but could just as easily go into 4.0.1 if needed?

**Comment by mark-prins** [comment]
not bothered which one it goes in. I've done the changes already - because I needed the screenshots. which branch do I branch from for 4.1??

**Comment by joshxg** [comment]
@mark-prins develop

**Comment by joshxg** [comment]
Closed by #2487

**Comment by Rebecca367** [comment]
They all look pretty french to me.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Change the language to French and check the language button. Expected result: should read `LANGUE`

For the following, change to *French* prior to logging in:

- [x] Create or edit a general stocktake (ou relevés d'inventaire). Expected result: the text on the button `Cacher les ruptures de stocks` should be centered nicely
- [x] Create or edit a general stocktake (ou relevés d'inventaire). Expected result: the text on the button `Tout les articles sélectionnés` should be centered nicely
- [x] on pretty much any screen, look at the top line: Expected result: `SYNC ACTIVÉ` should be uppercase
- [x] Go to the settings page and check that the settings save button text is translated

![Screen Shot 2020-03-10 at 4 53 28 PM](https://user-images.githubusercontent.com/57238075/76278455-8ddd8700-62f0-11ea-94f7-a19d0d7c079f.png)
![Uploading Screen Shot 2020-03-10 at 4.57.01 PM.png…]()
![Uploading Screen Shot 2020-03-10 at 4.57.56 PM.png…]()

**Comment by Rebecca367** [comment]
They all look pretty french to me.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Change the language to French and check the language button. Expected result: should read `LANGUE`

For the following, change to *French* prior to logging in:

- [x] Create or edit a general stocktake (ou relevés d'inventaire). Expected result: the text on the button `Cacher les ruptures de stocks` should be centered nicely
- [x] Create or edit a general stocktake (ou relevés d'inventaire). Expected result: the text on the button `Tout les articles sélectionnés` should be centered nicely
- [x] on pretty much any screen, look at the top line: Expected result: `SYNC ACTIVÉ` should be uppercase
- [x] Go to the settings page and check that the settings save button text is translated

![Screen Shot 2020-03-10 at 4 53 28 PM](https://user-images.githubusercontent.com/57238075/76278455-8ddd8700-62f0-11ea-94f7-a19d0d7c079f.png)
![Screen Shot 2020-03-10 at 4 57 01 PM](https://user-images.githubusercontent.com/57238075/76278573-c2e9d980-62f0-11ea-857f-3b40dcfca46a.png)
![Screen Shot 2020-03-10 at 4 57 56 PM](https://user-images.githubusercontent.com/57238075/76278574-c2e9d980-62f0-11ea-94fa-b906972ce603.png)
