### ISSUE TITLE
Program name not showing on program based stocktakes

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2490]
## Describe the bug

According to the pictures in the user guide the name of the program was shown on program based stocktakes. 
It isn't now. I believe it should

### To reproduce

1. Go to Stocktakes
2. Create one for a program
3. Observe the page info section. Stocktake name is show along with comment.

### Expected behaviour

Display program name, if this is a program based stocktake.

### Screenshots
Current behaviour:
![Screen Shot 2020-03-06 at 1 06 22 PM](https://user-images.githubusercontent.com/9192912/76037255-4df26900-5fab-11ea-9df8-74e4f16ebfab.png)

From the user guide:

![Screen Shot 2020-03-06 at 1 07 24 PM](https://user-images.githubusercontent.com/9192912/76037305-74180900-5fab-11ea-8d5f-6a51c338a791.png)

**Comment by wlthomson** [comment]
@mark-prins Seems suitable for a patch? Have added to the `v4.0.1` list.

**Comment by wlthomson** [comment]
Fixed by #2490.

**Comment by nishaSussol** [comment]
Tested in mobile version 4.0.1

## Tests
Steps to reproduce or otherwise test the changes of this PR:
- [x] Create or find a program based stocktake. Observe the program name is shown when editing **-PASS-**
- [x] Create or find a non-program based stocktake: this should load correctly and display as now **-PASS-**
- [x] Check other pages, esp. the program based supplier requisitions **-PASS-**
