### ISSUE TITLE
Add patient lookup UI to dispensing page

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2540]
## Is your feature request related to a problem? Please describe.

As part of the patient API, a `"Lookup patient"` button (or similar widget) needs to be added to the dispensing page.

## Describe the solution you'd like

Two options here:

1. Add `"Lookup patient"` button next to `"New patient"` button in top-right of dispensing page. Trade-off here is some real-estate in the searchbar.
2. Add `"Lookup patient"` button or widget at bottom of dispensing page (below list of patients). Spares some real-estate, but feels a bit incongruous?

## Implementation

- Add button or other widget (existing components for this).
- Add localisation.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #2446.

**Comment by Rebecca367** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] When toggling patient/prescriber datasets, the lookup button updates correctly (`"Lookup patient/Lookup prescriber"`).
- [x] When the `"Lookup patient"` button is pressed, an empty modal is opened with the same title.
- [x] When the `"Lookup prescriber"` button is pressed, an empty modal is opened with the same title.
- [x] When the modal is closed, the user is returned to the dispensary page without any change to the previous state.

**Comment by wlthomson** [comment]
Fixed by #2566.

**Comment by diegoevangelisti** [comment]
**Testing in progress**

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] When toggling patient/prescriber datasets, the lookup button updates correctly (`"Lookup patient/Lookup prescriber"`).
- [ ] When the `"Lookup patient"` button is pressed, an empty modal is opened with the same title.
- [ ] When the `"Lookup prescriber"` button is pressed, an empty modal is opened with the same title.
- [ ] When the modal is closed, the user is returned to the dispensary page without any change to the previous state.
