### ISSUE TITLE
Add Placeholder text in Search Bar 

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#264]
Suggestion for placeholder text in Searchbar, for instance in stocktakes. Should tell the user what field they are sorting by i.e. "Search ITEM NAME".

**Comment by Rebecca367** [comment]
This feature affect user's experience using portable device. It seems to be a good feature to add on.

**Comment by Rebecca367** [comment]
@Chris-Petty @andreievg @joshxg @edmofro @diegoevangelisti 
Is it better to create a file/ component called searchBarText as a component to export to pages that require it? It is my thought so far. Please feel free to comment on it.

**Comment by Chris-Petty** [comment]
@Rebecca367  Definitely shouldn't be a component but it's a good point that there should be a source of truth, localised in fact! 

In each page there is a SearchBar:
![image](https://user-images.githubusercontent.com/7684221/71787023-1896d100-3077-11ea-9310-24ca4a312e22.png)
Here you can use the `placeholder` prop to provide the text to show as a placeholder. You can use the existing localisations for column names. Something like:

```jsx
placeholder={`${ourStrings.search} ${ourTableStrings.item_name}`}
```

**Comment by Rebecca367** [comment]
@Chris-Petty 
Thanks for the input!

**Comment by Rebecca367** [comment]
@Chris-Petty @andreievg @joshxg @edmofro @diegoevangelisti
Would like to make sure I am on the right path before moving on to find those Strings are.
This is the placeholder that I embed in search bar :
<img width="624" alt="Screen Shot 2020-01-06 at 3 13 39 PM" src="https://user-images.githubusercontent.com/57238075/71790831-60c5eb80-3097-11ea-9c7d-c5ad1726027d.png">

**Comment by edmofro** [comment]
@Rebecca367 just fyi I don't work at mSupply any more, so no need to @ me :-)

**Comment by Rebecca367** [comment]
OK. Cheers!

**Comment by Chris-Petty** [comment]
> @Chris-Petty @andreievg @joshxg @edmofro @diegoevangelisti
> Would like to make sure I am on the right path before moving on to find those Strings are.
> This is the placeholder that I embed in search bar :
> <img alt="Screen Shot 2020-01-06 at 3 13 39 PM" width="624" src="https://user-images.githubusercontent.com/57238075/71790831-60c5eb80-3097-11ea-9c7d-c5ad1726027d.png">

Where you've put it would be a child to the `View`, not a prop for SearchBar.

![image](https://user-images.githubusercontent.com/7684221/71793720-eac78180-30a2-11ea-8041-102f9ec42a27.png)

It's also occurred to me that it appears you've added a new `View` for some reason?

**Comment by Rebecca367** [comment]
@Chris-Petty @andreievg @joshxg @diegoevangelisti
All pages require search bar component were added sorting term accordingly as below:
<img width="622" alt="Screen Shot 2020-01-07 at 2 11 38 PM" src="https://user-images.githubusercontent.com/57238075/71860414-a944de00-3157-11ea-8d8c-7013944fcacf.png">
Filtering terms are different in each page such as stocktakeeditpage is sorted by item _name but others can be sorted by item_code or both.
It can be confusing if pages can be sorted by both. Regarding to one issue about consistent filtering terms between data table pages #1235  might mean that we need to make it consistent sorting all pages.
@Chris-Petty Thanks for Chris's time and input. Much appreciated!!

**Comment by Rebecca367** [comment]
@Chris-Petty thanks for reminding about rebase. It's good to make it as a habit to do it all the time...just sometimes..often forget...

**Comment by Chris-Petty** [comment]
Yea I just did it again, but on mSupply it's really obvious hahaha

![image](https://user-images.githubusercontent.com/7684221/71865733-9ab2f280-3168-11ea-8edc-e09d6592d2e6.png)

(Actual changes are about 11 lines diff)

**Comment by Rebecca367** [comment]
@Chris-Petty 
have no clue on how msupply reminds people when they forget to rebase it, power of msupply I guess. We all need reminders after all. poor human brain need to remember too many things at once, so need to be reminded..hehe

**Comment by Chris-Petty** [comment]
It's just that I see a PR code diff of over 10k which just about should never be the case

**Comment by Rebecca367** [comment]
How to reduce it in this issue? Refactoring in the future? Or change another way to add this feature?

**Comment by Chris-Petty** [comment]
Ah I already fixed it on this PR (actually this discussion is in the issue now for some reason), but in the future if you need to change the base on an existing PR, you can do so by hitting the edit button by the PR title:
![image](https://user-images.githubusercontent.com/7684221/71868152-d1413b00-3171-11ea-89dd-dfb52a7ea144.png)

**Comment by Rebecca367** [comment]
@Chris-Petty  Cool, thank you for letting me know about this.

**Comment by Rebecca367** [comment]
@Chris-Petty 
I think it's a good idea to change font color or size in search bar. I will make a new issue after this to avoid confusion. Thanks

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] click on customer invoice page with search bar and filter item name/item code to see if it is working.
-  [x] click on customer invoices page with search bar and filter item name/item code to see if it is working.
-  [x] click on customer requisition page with search bar and filter item name/item code to see if it is working.
-  [x] click on customer requisitions page with search bar and filter item name/item code to see if it is working.
- [x] click on supplier invoice page with search bar and filter item name/item code to see if it is working.
- [x] click on supplier invoices page with search bar and filter item name/item code to see if it is working.
-  [x] click on supplier requisition page with search bar and filter item name/item code to see if it is working.
-  [x] click on supplier requisitions page with search bar and filter item name/item code to see if it is working.
-  [x] click on stocktake page with search bar and filter item name/item code to see if it is working.
-  [x] click on stocktakeEdit page page with search bar and filter item name/item code to see if it is working.
-  [x] click on stocktakeManage page with search bar and filter item name/item code to see if it is working.

**Success**
