### ISSUE TITLE
 Add lookup API insurance policy creation logic thunks

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2678]
## Is your feature request related to a problem? Please describe.

Move lookup API insurance policy creation logic to thunks.

## Describe the solution you'd like

See above.

## Implementation

See #2674.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

**Comment by wlthomson** [comment]
Fixed by #2679.

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Insurance policies are created without error. **--PASS--**

- [x] Insurance policies are edited without error.  
(**NOTE:** Only editable fields are Active Y/N and Discount rate) **--PASS--**

- [x] Insurance policies are added on patient lookup (after adding patient via lookup API, dispense to that patient and check insurance policies appear in dropdown).  **--PASS--**

**NOTE**: @wlthomson. Policies appear in dropdown but can't be found in patient lookup. More details here: #2749
