### ISSUE TITLE
Add response code handling to API network helpers

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2681]
## Is your feature request related to a problem? Please describe.

The lookup API does not currently handle response codes.

## Describe the solution you'd like

Add logic for handling response codes.

## Implementation

Update lookup API helpers to handle response codes.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #2446.

**Comment by wlthomson** [comment]
Fixed by #2684.

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] When a user searches for a patient on an offline server, a confirm modal displays the error: `"Unable to connect"`. -> Response `Network request failed`. (I take is as a pass, but please this one @wlthomson in case I'm wrong) **-PASS-**
- [ ] When a user searches for a non-existent patient, a confirm modal displays the error `"No matching records found"`. **-FAILED**- There is no message showing up. Issue: #2744
- [ ] When a user searches for a patient using invalid/expired credentials, a confirm modal displays the error: `"Invalid username or password"`. 
- [ ] When a user searches for a patient but no response is received in 10 seconds, a confirm modal displays the error: `"Unable to connect"`.
- [ ] When a user searches for a prescriber on an offline server, a confirm modal displays the error: `"Unable to connect"`.
- [ ] When a user searches for a prescriber using invalid/expired credentials, a confirm modal displays the error: `"Invalid username or password"`.
- [ ] When a user searches for a prescriber but no response is received in 10 seconds, a confirm modal displays the error: `"Unable to connect"`.
- [ ] When a user searches for a non-existent prescriber, a confirm modal displays the error `"No matching records found"`.
