### ISSUE TITLE
Read-only constraints not being consistently applied

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2689]
## Is your feature request related to a problem? Please describe.

A few problems/inconsistencies with dispensing for non-local patients:

- the `supplyingStoreId` field is not being correctly set for patients created via the lookup API. 
- the `storeId` field is not being correctly set for patients created via the lookup API. 
- non-local patients/prescribers cannot be edited, but the edit form can still be accessed and the icon is not disabled as it is for policies.

## Describe the solution you'd like

- correctly set supplying store fields for patients/prescribers.
- disable edit icon in the dispensing window for non-local patients/prescribers

## Implementation

- update `PatientActions.patientUpdate`.
- update `PrescriberActions.updatePrescriber`
- update `PrescriptionInfo` component.

## Describe alternatives you've considered

N/A.

## Additional context

See epic #2446.

**Comment by wlthomson** [comment]
Fixed by #2690.

**Comment by diegoevangelisti** [comment]
**NOTE**: Testing in progress

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Remote patients "edit" icon is a book in the dispensary page patient list. 
- [ ] Remote prescribers "edit" icon is a book in the dispensary page prescriber list.
- [ ] Remote patients "edit" icon is a book in the prescription wizard.
- [ ] Remote prescribers "edit" icon is a book in the prescription wizard.
- [ ] Policies belonging to remote patients "edit" icon is a bookin the prescription wizard.
