### ISSUE TITLE
Dispensary record lookup form should add wildcards by default

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2713]
## Is your feature request related to a problem? Please describe.

Wildcards should be added by default to the lookup form parameters (@Gwalior-84).

## Describe the solution you'd like

Prepend/append wildcards to each query param.

## Implementation

If done mobile side, just update the lookup thunks to wrap each query parameter in `@` literals.

## Describe alternatives you've considered

Could be done mobile side or desktop side. My initial thinking is that wildcards might not always be desirable, so I'm not sure it's a good idea to bake them into the API itself (but if this is how the search always works then maybe that's the way to go?). 

Thoughts?

## Additional context

@Gwalior-84 Feedback from dispensary demo (17/04/20).

**Comment by joshxg** [comment]
👍

**Comment by nmadruga** [comment]
I agree that adding that by default is more desirable. If the user would like to restrict the search to only **match whole word** they can come back to us and a new preference can be added to the search. As it's done in VS code for example:
![Screen Shot 2020-04-23 at 12 16 47 PM](https://user-images.githubusercontent.com/16461988/80045803-a92cea80-855c-11ea-83d5-ea9d9795b806.png)

**Comment by wlthomson** [comment]
>  If the user would like to restrict the search to only match whole word they can come back to us and a new preference can be added to the search.

Nice! A bit of a "nice to have", but definitely a good idea.

**Comment by wlthomson** [comment]
Fixed by #2776.

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Each patient record returned by a lookup query satisfies the following property: for all input fields with a value, that record field either matches that value, **or contains it**. 
- [ ] All patient records not returned by a lookup query satisfy the following property: for at least one input field with a value, that record does not match that value **and does not contain it**.
- [ ] Each prescriber record returned by a lookup query satisfies the following property: for all input fields with a value, that record field either matches that value, **or contains it**. 
- [ ] All prescriber records not returned by a lookup query satisfy the following property: for at least one input field with a value, that record does not match that value **and does not contain it**.

@wlthomson: I am not getting a Patient with both `First Name` and `Last name` contained in the search. 
For instance, I searched for 'Dan' and I am being retrieved with a list of patients' names that contains it. That is ok, but when added a Last Name filter, 'Kou', no records are found, even if there is a match that contains both words ('Dan' and 'Kou'). As far as I understand, the filter should match or contain _all_ input fields. Is that correct or this condition works only for one input field at a time? Thanks

Example below:

<img width="1149" alt="Screen Shot 2020-05-06 at 9 28 39 AM" src="https://user-images.githubusercontent.com/32987464/81118897-d1194680-8f7d-11ea-82da-0313ebd1c52a.png">

![notFound](https://user-images.githubusercontent.com/32987464/81118921-dececc00-8f7d-11ea-8d4e-e22dcb9ce375.gif)

**Comment by Gwalior-84** [comment]
> As far as I understand, the filter should match or contain _all_ input fields. Is that correct or this condition works only for one input field at a time? Thanks

Yes @diegoevangelisti , I would expect that entry to come up when both fields 'match'.

**Comment by wlthomson** [comment]
Hmm. The wildcards are pre- and appended to all fields. The intended behaviour is for the top record to appear. Will open an issue.

**Comment by wlthomson** [comment]
Going to mark this as done as failed tests covered by #2818.
