### ISSUE TITLE
Cannot cancel when confirming an insurance policy for a non-local patient

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2717]
## Describe the bug

When confirming a prescription for a non-local patient, the user cannot cancel and return to editing.

### To reproduce

1. Lookup a non-local patient using the lookup modal.
2. Dispense to the patient.
3. Create an insurance policy at the payment step.
4. Save the insurance policy.
5. See error.

### Expected behaviour

The modal should include a cancel button (or pressable`X` in the top right).

### Proposed Solution

Add a cancel button to the popup confirm modal.

### Version and device info

- App version: `feature/patient-api` branch.
- Tablet model: Emulator (Nexus 10).
- OS version: API29.

### Additional context

Found during dispensary demo (17/04/20).

**Comment by joshxg** [comment]
The `ConfirmForm` component has an optional cancel button that can show up

**Comment by wlthomson** [comment]
Fixed by #2729.

**Comment by diegoevangelisti** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] When saving an insurance policy for a non-local patient, a confirmation modal is displayed. **-PASS-**
- [x] When the confirmation modal is cancelled, the modal is hidden and the insurance policy details are NOT reset. **-PASS-**
- [x] When the confirmation modal is confirmed, the modal and form are closed and the insurance policy saved and selected. **-PASS-**
