### ISSUE TITLE
Requisition toggle overstocked title is too big

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2826]
## Describe the bug

When viewing a supplier requisition, the `"Hide/Show over stocked"` toggle looks like this:

<img width="1147" alt="Screen Shot 2020-05-07 at 3 10 40 PM" src="https://user-images.githubusercontent.com/32987464/81251090-9cd58100-9076-11ea-83cf-55bc34b5057b.png">

### To reproduce

1. Open an existing supplier requisition.
2. See error.

### Expected behaviour

Toggle title should be smaller. 

### Proposed Solution

Revert whichever style changes @wlthomson broke!

### Version and device info

- App version: `v5.0.0-rc3`
- Tablet model: Android emulator (Nexus 10)
- OS version: API 28

### Additional context

Raised by @diegoevangelisti

**Comment by wlthomson** [comment]
Fixed by #2828.

**Comment by diegoevangelisti** [comment]
Tested in v5.0.0-rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] When viewing a supplier requisition, the `"Show/Hide over stocked"` toggle button text is not too large. **--PASS
- [x] When updating a supplier requisition months of stock, `"1 2 ... 6"` toggle bar text is not too small. **--PASS
