### ISSUE TITLE
Payment Type shows Placeholder

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#2860]
## Describe the bug

Created a new store and user on the `demoivory.msupply.org` store and synchronised that to a tablet.

When making a prescription payment or cash register transaction the payment type of `PlaceholderDescription` shows.

### To reproduce

Steps to reproduce the behaviour:

1. Create a site on a CI datafile
2. Create a sync site and user
3. Initialise a tablet
4. Create a cash register transaction

### Expected behaviour

Should only see the defined payment types.
In my scenario there were four in the mSupply server, but five show on the tablet.

### Version and device info

- App version: 5.0.2
- Tablet model: Lenovo

### Additional context

![image](https://user-images.githubusercontent.com/9192912/82849879-1661e000-9f4e-11ea-9e80-706b11d58a25.png)

**Comment by mark-prins** [comment]
There was also an issue (probably) with the migration code. The payment types were all duplicated 4 times. These were manually deleted on the server and the tablet re-initialised.

**Comment by joshxg** [comment]
A possible explanation would be if there were any FK references to the deleted payment types, then when sent to mobile, the sync logic will create a placeholder record [assumes it will receive the record eventually and update the placeholder], so that there is "some" relational integrity.

**Comment by wlthomson** [comment]
Oops, thought I replied to this :fearful:!

Following from @joshxg comment, placeholders are created by `getOrCreate` when mobile needs to link some records but only has a FK to go on. The only way payment types are created via a foreign relation is when a transaction is synced from desktop.

So,  I think the only way this can occur is if desktop had a sync out queue which contained transactions with references to either deleted payment types or payment types which failed to sync. This would make sense in the context of the deleted duplicate payment types... perhaps there were one or more transactions which referenced the payment types which were deleted before re-initialisation?

**Comment by wlthomson** [comment]
Oops, thought I replied to this :fearful:!

Following from @joshxg comment, I believe placeholders are only created by mobile via the "create" part of `getOrCreate`, i.e. when mobile needs to link some records but only has a FK to go on. From a quick global find on the repo, it looks like the only way payment types are created via a foreign relation is when a transaction is synced from desktop.

So... I think the only way this can occur is if desktop had a sync out queue which contained transactions with references to either deleted payment types or payment types which failed to sync. This would make sense in the context of the deleted duplicate payment types... perhaps there were one or more transactions which referenced the payment types which were deleted before re-initialisation?

**Comment by wlthomson** [comment]
Update: @JonnaQuismundo also experienced this issue and can confirm that the duplicates were on the desktop side. Looks like this is probably a desktop problem (@JonnaQuismundo is making an issue for it).

**Comment by mark-prins** [comment]
so... we close this issue? as a non-issue?
Your arguments sound convincing to me

**Comment by wlthomson** [comment]
I'm just waiting for the desktop issue to be made so I can link to it, then I'll close :smile:.

**Comment by JonnaQuismundo** [comment]
@wlthomson @mark-prins yes the duplicates are from the desktop side. I guess that's just on my IC data file where it went through migration a couple of times.
I tried to replicate the issue in an old restored IC data file and the payment type duplication is not happening anymore.

**Comment by wlthomson** [comment]
@JonnaQuismundo did you end up making a desktop issue for this (if so, could you link it to this one)? It also occurred for @mark-prins, so looks like it might be something to look into?

**Comment by JonnaQuismundo** [comment]
@wlthomson No, I did not. I believed the bug I've encountered was because of my own data file was not a good test datafile to begin with since I'm playing with it a lot. But I tried a bunch of scenarios to replicate it using a fresh IC data file and the payment type duplication is not happening anymore. So I guess it's not an issue? 
@mark-prins Is it still happening on your end?

**Comment by mark-prins** [comment]
I have `PlaceholderDescription`  showing as one of the options for the demo tablet which is running off the `demoivory` server. That one is running against a newly created store, which would have no transactions and the tablet has be re-initialised.

I've checked that there are currently no transactions relating to missing `paymentType`s on either my datafile or the demoivory one. 🤷‍♂️

**Comment by JonnaQuismundo** [comment]
Could be a different issue/scenario? @mark-prins @wlthomson 
I'm just using emulator though not demo tablet.

**Comment by joshxg** [comment]
What a roller coaster.

Possibly: Marks payment type does not have a description? The default is then `placeholderDescription`

**Comment by JonnaQuismundo** [comment]
But I saw the `placeholderDescription` when I deleted some of the `payment type`  in desktop then sync again. 
![IMAGE 2020-06-10 16:44:18](https://user-images.githubusercontent.com/61759124/84227864-a0f33380-ab39-11ea-8785-800fcabbfd02.jpg)

**Comment by mark-prins** [comment]
The payment types have descriptions. Are you saying that you don't have this issue? It sounds like it is just an Ivory Coast specific problem - in combination with the migration of payment types that happened. Willing to drop it if you aren't getting the problem.

![Screen Shot 2020-06-10 at 4 48 12 PM](https://user-images.githubusercontent.com/9192912/84228129-473f3900-ab3a-11ea-9238-42d9a822dbb1.png)

Side note: tested on tablet and emulator. same issue on both.

**Comment by wlthomson** [comment]
> But I saw the `placeholderDescription` when I deleted some of the `payment type` in desktop then sync again. Which I don't think is the right thing to do, just did this for troubleshooting purposes.

@JonnaQuismundo I think this is OK (at least from mobile perspective), as is expected behaviour from mobile end when receiving a transaction which references a payment type which isn't known (e.g. has been deleted before synced).

> The payment types have descriptions. Are you saying that you don't have this issue? It sounds like it is just an Ivory Coast specific problem - in combination with the migration of payment types that happened. Willing to drop it if you aren't getting the problem.

Hm, I think the original theory still holds for this:

1. transaction is made with reference to payment type, e.g. `payment_type.ID = 33B5...`.
2. payment type record is deleted using footrunner or migration code.
3. mobile initialises/syncs.
4. mobile processes transaction on incoming sync, creates a placeholder payment type: `{ ID: 33B5, description: placeholderDescription`.

So, unless I'm missing something/mistaken, this looks like a data file or desktop problem (maybe migration bug?) as opposed to anything broken mobile end.

@joshxg Sound about right?

**Comment by wlthomson** [comment]
> But I saw the `placeholderDescription` when I deleted some of the `payment type` in desktop then sync again. Which I don't think is the right thing to do, just did this for troubleshooting purposes.

@JonnaQuismundo I think this is OK (at least from mobile perspective), as is expected behaviour from mobile end when receiving a transaction which references a payment type which isn't known (e.g. has been deleted before synced).

> The payment types have descriptions. Are you saying that you don't have this issue? It sounds like it is just an Ivory Coast specific problem - in combination with the migration of payment types that happened. Willing to drop it if you aren't getting the problem.

Hm, I think the original theory still holds for this:

1. transaction is made with reference to payment type, e.g. `transaction.payment_type_ID = 33B5...`.
2. payment type record is deleted using footrunner or migration code.
3. mobile initialises/syncs.
4. mobile processes transaction on incoming sync, creates a placeholder payment type for `transaction.payment_type_ID` as can't find the record, e.g.`{ ID: 33B5..., description: placeholderDescription`.

So, unless I'm missing something/mistaken, this looks like a data file or desktop problem (maybe migration bug?) as opposed to anything broken mobile end.

@joshxg Sound about right?

**Comment by joshxg** [comment]
Looks like this should be closed 🤷
