### ISSUE TITLE
Sync error on lookup patient with insurance policy

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2916]
## Describe the bug

When a patient with one or more insurance policies is added via the lookup modal, the following sync error occurs:

### To reproduce

1. Create a patient on desktop with an associated insurance policy.
2. Add the patient on mobile using the lookup modal. 
3. See error.

### Expected behaviour

No error should occur.

### Proposed Solution

Looks like a bug in `InsuranceActions.update` (reminder to self that this logic pretty badly needs to be refactored!).

Quick fix is to add a `getOrCreate('InsuranceProvider', `policyDetails.insuranceProviderId`).

### Version and device info

- App version: v5.0.2.
- Tablet model: Android emulator (Nexus 10).
- OS version: API 28.

### Additional context

Raised by @JonnaQuismundo.

**Comment by wlthomson** [comment]
Fixed by #2917.

**Comment by nishaSussol** [comment]
## Testing
Tested in mobile v5.0.3

Steps to reproduce or otherwise test the changes of this PR:

- [x] No sync error occurs when adding a new patient with one or more insurance policies.
    - [x] Above error does not occur if the policy provider already exists on mobile. **No Sync Error** ,but the insurance policies show as inactive. See #3064 
![Screenshot_20200803-171242_mSupply Mobile](https://user-images.githubusercontent.com/59193490/89178608-b6229680-d5ad-11ea-86bf-2a5772ed41e4.jpg)

    - [x] Above error does not occur if the policy provider does not exist on mobile.  **Pass** ,but **APP CRASHES** in v6.0RC3. See #3065
