### ISSUE TITLE
Reason modal pops up to quick on a supplier requisition

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#2940]
## Describe the bug

Can't enter more than 1 digit on supplier requisition quantity column

### To reproduce

1. Ivory coast data file
1. Go to 'supplier requisition'
2. Tap on 'requested quantity'
3. Try to put the requested quantity with >1 digits
4. You will be prompted to choose the reason

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.1
- Tablet model: Samsung 8'
- OS version: Android 9

### Additional context

see video
https://www.dropbox.com/s/ni35fcwx8im8wdw/supplierrequisition-1.mp4?dl=0

**Comment by wlthomson** [comment]
Unless I'm missing something, I think the issue title/description here needs updating to clarify a bit more about what behaviour is occurring and what the desired behaviour is!

From replicating, I think the issue here is that the reason modal is being triggered when the requested quantity is first set. As far as I can tell, there is nothing that actually prevents entering more than a single digit once the modal is closed. 

@bijaySussol To clarify, is the issue here is that the user does not want the modal popping up before they have entered the full amount? 

My thinking at this stage:

- It is intentional that the reason modal is displayed `onChangeText`, so this seems to be more of a UX thing rather than a bug.
- As this doesn't break any functionality, I don't think this would be something to prioritise unless a client is strongly pushing for it.
- If we did want to go ahead with this, my initial thoughts are a couple of possible solutions:
  - Debounce the reason modal: this wouldn't be too much work, but I'm not sure how much it would help (and could potentially cause unexpected behaviour due to race conditions)
 - Enforce reason `onSubmitEditing`: this would require changing some internal data table stuff, so would be a bit more work (and more risk for regressions etc.)

@joshxg Thoughts? Please correct if anything above is wrong!

**Comment by bijaySussol** [comment]
> My understanding is that the user can enter more than one digit, but does not want the modal popping up before they have entered the full amount. Is that correct?

This is correct and what i was trying to address from issue
Say quantity to enter is 50
Now, As soon as quantity is enter > type first digit say 5 and try for enter 0 - It asked to choose the option and you will see 5 is set not 50 but the actual quantity to enter is 50 - so to type 50 will have to revisit again.
But the strange thing is - It works well after you finish editing that line and try to re-enter the quantity on a same line, just doesn't allow on first time - so something tweaky needed when changing fresh lines and editing the same line - I think as behaviour wise

**Comment by joshxg** [comment]
@wlthomson 

Sorry late. Yup, not breaking functionality, but definitely *very* annoying.

Fixes:
- `debounce`: yup this'll be pretty weird and convoluted although a good idea. I'm thinking of things like: the modal poping up at odd times (edit row -> tab to next row -> modal comes up), navigating back after editing (need to cancel the debounce?), going to edit the comment right after editing a quantity etc - in general not solving the issue of "weird UX problem"
- `onSubmitEditing`: If we use this, then navigating "back", or trying to finalise or things like that will make the `onSubmitEditing` functionality odd also - so again, not fixing the core "weird UX thing"


I thought we had decided (with mark) a few months ago (before 5.0) to remove the enforcement of the reason - this would mean you click the button in the cell to open the model to assign a reason. This was because 

1. it's nicer than the modal poping up! 
2. The enforcement of a reason seems to have been a constraint that we put on the clients, rather than something that was a requirement (from my interpretation of the requirements doc)

**Comment by wlthomson** [comment]
> I thought we had decided (with mark) a few months ago (before 5.0) to remove the enforcement of the reason - this would mean you click the button in the cell to open the model to assign a reason. This was because
> 
> 1. it's nicer than the modal poping up!
> 2. The enforcement of a reason seems to have been a constraint that we put on the clients, rather than something that was a requirement (from my interpretation of the requirements doc)

AFAIK, we agreed to remove from stocktakes, not sure about requisitions? If that's the case, would definitely be the tidiest solution!
