### ISSUE TITLE
Stocktake> single/double tapping new batch to enter on line > Keyboard disappear

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#2941]
## Describe the bug

Stocktake> single/double tapping new batch to enter on line > Keyboard disappear

### To reproduce

1. Go to 'Stock take'
2. Create new stock take > Add 2 new batch line to the given stock take
3. Select 1st batch line > Single/double tap or put the cursor at the end > No disappear of keyboard
4. Follow the same steps mention on Point 2 - > Keyboard disappear

### Expected behaviour

No keyboard disappear

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.1
- Tablet model: Samsung tablet 8'
- OS version: Android 9

### Additional context

See video
https://www.dropbox.com/s/xt0nfn6l6i3zlu4/stocktake-part2.mp4?dl=0

**Comment by bijaySussol** [comment]
This also happened on Emulator:
http://g.recordit.co/ceawL7ZY4G.gif

**Comment by joshxg** [comment]
@bijaySussol 


It looks like it might have something to do with the scrolling behaviour of the `DataTable` component, or just generally having insuffient room.

The code here is where I would start - add some more room for the modal by making the modal full screen:

https://github.com/openmsupply/mobile/blob/442a8a7e3d065c107c808b7bd715edf894bffd97/src/widgets/modals/DataTablePageModal.js#L47-L48

I would probably also check this function `adjustToTop`. This is what is called when we focus a cell - I would double check the logic here so that it is scrolling to the correct place and maybe see if there can be any adjustments made:

https://github.com/openmsupply/mobile/blob/442a8a7e3d065c107c808b7bd715edf894bffd97/src/widgets/DataTable/DataTable.js#L92-L94

**Comment by joshxg** [comment]
Also just noticed a bug which might prevent you from making `StocktakeBatchModal` fullScreen.

https://github.com/openmsupply/mobile/blob/442a8a7e3d065c107c808b7bd715edf894bffd97/src/widgets/modals/ModalContainer.js#L58-L63

These arrays should both be: `[backgroundColor, fullScreen]`

**Comment by ujwalSussol** [comment]
@sworup  :  This is issue that our client will raise again and again, so great if we had a fix.

**Comment by sworup** [comment]
@joshxg @bijaySussol @ujwalSussol 

I did get a virtual keyboard disappearing issue in emulator mode but it wasn't a lot prominent. Happened say, 1 out of 10 times but on cases of last 2 rows of a very long list.

 I ran the code in our Samsung tab and one more device in our office and strangely in these devices the problem does not persist.

In case of the emulator edited `src/widgets/DataTablePageView.js` adding a wrapper `KeyboardAvoidingView` component to `TouchableWithoutFeedback` component.  

```
const Container = captureUncaughtGestures ? TouchableWithoutFeedback : Fragment;

  return (
    <KeyboardAvoidingView behavior="height" style={styles.container}>
      <Container {...containerProps}>
        <View style={[pageContentContainer, styles.inner]}>
          <View style={container}>{children}</View>
        </View>
      </Container>
    </KeyboardAvoidingView>
  );
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  inner: {
    flex: 1,
    justifyContent: 'space-around',
  },
});
```

This improved the keyboard disappearing problem on an emulator but unfortunately, I have not been able to try it in physical tablet since the functionality is working with or without the fix on them.

**Comment by joshxg** [comment]
@sworup 

So sorry! I just remembered about this issue this morning :(

I think I remember putting a keyboard avoiding view at some point, but it didn't make much of a difference. I don't believe it had any other side effects, though, so- if you think it will make for a better ux, I suppose we just add it! 🤷

**Comment by Chris-Petty** [comment]
Oblivious me, but just now I saw some [old commits I made](https://github.com/openmsupply/mobile/pull/604/files#diff-63272c98a6330850888e633b43ba4c9decee6431a115e0d2731564838eaa1d1dL22-R23) that might be relevant. Quite possibly need to revisit the android manifest!

**Comment by sworup** [comment]
> Oblivious me, but just now I saw some [old commits I made](https://github.com/openmsupply/mobile/pull/604/files#diff-63272c98a6330850888e633b43ba4c9decee6431a115e0d2731564838eaa1d1dL22-R23) that might be relevant. Quite possibly need to revisit the android manifest!

That code ```android:windowSoftInputMode="adjustResize"``` should be ok.
