### ISSUE TITLE
Patient created on mobile store remains editable after home store is updated

### ISSUE THREAD

**Issue by nishaSussol** [openmsupply/mobile#2943]
## Describe the bug
Patient created in mobile store, even after changing their home store in cloud, is still editable in the mobile store

### To reproduce
Setup: Sync a mobile store to the cloud.
1. Create a patient in mobile store, and sync.
2. Then, on cloud, change that patient's home store to another.
3. Now in mobile store, try editing that patient details.
4. See error, you can still edit them.

### Expected behaviour
Patient of one home store should not be editable in another mobile store.

### Version
- App version: v5.0.3

### Additional context
https://github.com/sussol/msupply/pull/6236#issuecomment-643059615

**Comment by nmadruga** [comment]
Just something to consider, Adrian wrote on the description of the issue to add the new `transferring patients` on Desktop (https://github.com/sussol/msupply/issues/5082):
> "Note also that (AFAIK) mobile doesn't support processing of incoming messages => we need to sync the whole modified record from the central server. Otherwise just sending the message would do the trick, and that would guarantee that we don't accidentally overwrite any recent record changes on the current home store site. When a desktop site processes a message to update a record, that will then sync the entire record back to the central server."

**Comment by joshxg** [comment]
I haven't had a good look at the solution but that reads to me as: When transferring, send a full updated `[name]` record to satellites. If that's the case, then the mobile site should just be receiving a new `[name]` record. As long as the normal logic is correct for "non-local" patients, then the patient should just be updated and not be editable (possible problems with re-rendering after a sync)?

Possibly actually easier to use postman to check the incoming records (to mobile)

**Comment by nmadruga** [comment]
Well, for now it seems as the central server will always send only a `[message]` sync_out record with `[message]type="requestFieldChange"` to indicate a change on the **home store** of the patients `[name]` which should be processed on the patient **previous home store**.

**Comment by joshxg** [comment]
@nmadruga so it seems to be the feature is not finished? Or, the solution having been implemented is not the agreed upon solution

**Comment by adrianwb** [comment]
Because mobile doesn't process incoming message records (or if it does, then please correct me), the only option that would work when transferring patient home stores was to send the complete patient record, and that's what it does (or at least what it's meant to do!).

While it would be nice for mobile to process incoming messages (at least for updating a single field), that's not really the issue here. The root problem, as far as I can tell, is that mobile doesn't appear to enforce any restrictions on editing patients (or prescribers) regardless of their home store? It just so happens that transferring patients has highlighted the problem. If not addressed, then any mobile site can edit any patient and cause havoc!

I don't see any reasonable way for the server to bubble-wrap mobile so that it never gets any patients/prescribers with a home store different from their default. In any case, AFAIK, mobile already has the feature to issue prescriptions to patients from other stores, so I don't see any other option but for it to apply the same home store restrictions to editing patients/prescribers as desktop?

**Comment by joshxg** [comment]
It does have code to prevent editing - the problem (what I can tell), appears to be the record is not having it's home store updated.

From nicoles comment above, it implied that mobile is receiving the message record and not the updated name record - buuuuut, having a quick look, this would be my bet: https://github.com/openmsupply/mobile/blob/f157817228856f9b595ac420f438d77ba02d54a3/src/sync/incomingSyncUtils.js#L470

This is an artifact (is that how you use this word?) of defensive code from the first implementation to prevent the wrong patients being used on mobile. At a guess: We are not updating the name record, because it is being sent with a new home store - so we ignore it, rather than update it. Because the patient logic appears to be complete, I suspect that just removing this line will fix the problem!

**Comment by nmadruga** [comment]
Yes, I had the assumption it was going to be the same kind of `[sync_out]` record to Desktop or Mobile, but that's not correct. Like @adrianwb said: it will sync the `[name]` record with the new **home store** and the `[message]` record to mobile. 

@joshxg Removing that line fix the problem. I'll make a PR now. Thank you.

**Comment by joshxg** [comment]
@nmadruga 🎉 🎉

**Comment by wlthomson** [comment]
Fixed by #2970.

**Comment by nishaSussol** [comment]
## Testing
Tested in mobile v5.1.0

### Important note: The Desktop version to use as your local Central server to test this PR needs to have this PR merged in: [msupply/#5082](https://github.com/sussol/msupply/pull/6236) Which should be part of the v4.12 release.

Steps to reproduce or otherwise test the changes of this PR:
- Patient created on Mobile:
  - [x] On the mobile site, create a patient: Dispensary > New patient. Save. It is showing on the list with an `edit` icon. Sync with the Central server. **-PASS-**
  - [x] On the Central server, open the patient window. The **home store** selected is the Mobile store and the patient can't be edited. **-PASS-**
  - [x] On the Central server, change the patient's **home store** to another one (Active on the central server). Close the window. Go to the mobile site and sync. Wait a few seconds after to refresh the page. The patient is now showing on the list with a `read` icon. **-PASS-**
  - [x] On the Central server, when you open this patient window, it is now editable. And the **home store** selected is the other store that is Active in the central server. **-PASS-**
  - [x] On the mobile site, when you click on the `read` icon on this patient line you can't edit it. **-PASS-**

- Patient created on Central server:
  - [x] On the Central server, create a patient while logged in a store that is Active on the central server. Select the Mobile store as visible to this patient. **-PASS-**
  - [x] On the mobile site, sync with the Central server. Then check that the patient is showing on the Dispensary list. The patient has a `read` icon showing. And when you click on the `read` icon on this patient line you can't edit it.  **-PASS-**
  - [x] On the Central server, change the patient's **home store** to the Mobile store. Close the window. Go to the mobile site and sync. Wait a few seconds after to refresh the page. The patient is now showing on the list with an `edit` icon. **-PASS-**
  - [x] On the Central server, when you open this patient window, it can't be edited (only the **home store** can be changed). And the **home store** selected is the mobile store. **-PASS-**
  - [x] On the mobile site, when you click on the `edit` icon on this patient line you can edit it. **-PASS-**
