### ISSUE TITLE
Dates are synced to desktop without timezone offset

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2946]
## Describe the bug

When syncing a transaction from mobile to desktop, the `entry_date` (and other date fields) are incorrectly offset if the mobile device and server are not on the same timezones. Unlikely configuration in practice, but something that could occur (and occur often in testing).

### To reproduce

1. Setup mobile device/emulator on different timezone to server (such that the current day differs).
2. Create and finalise a customer invoice (or other record with date fields).
3. Sync to desktop.
4. View the transaction in desktop. Note that the date has been incorrectly offset. 

### Expected behaviour

Dates should be sent to desktop in ISO format (including timezone offset). 

Dates are synced as strings and parsed on incoming sync using the 4D date constructor. 4D documentation recommends formatting dates in ISO with timezone offset: 

> Note : Starting with 4D v14, it is recommended to use the "YYYY-MM-DDTHH:MM:SSZ" format, compliant with the ISO standard and allowing to express the time zone.

See https://doc.4d.com/4Dv16/4D/16.6/Date.301-4444819.en.html

### Proposed Solution

Update outgoing sync helpers to format dates in ISO format. 

### Version and device info

- App version: v5.0.3
- Tablet model: Android emulator (Nexus 10)
- OS version: API28.

### Additional context

Bug raised by @JonnaQuismundo.

**Comment by wlthomson** [comment]
Fixed by #2948.

**Comment by ArpitaSussol** [comment]
Tested in v5.1.0


## Testing

### Setup

- [ ] Setup mobile and desktop devices on different timezones such that the current day of the week differs. - **PASS**
- [ ] Create a new customer invoice on mobile, finalise and sync to desktop. - **PASS**

### Test cases

Steps to reproduce or otherwise test the changes of this PR:

- [ ] When the invoice is viewed on desktop, the dates are correct (from desktops point of view). I.e. if the transaction was made a few minutes ago on mobile, the transaction `entry_date` should be only a few minutes ago in desktop time (not a day ahead/behind).  - **PASS**
