### ISSUE TITLE
Insurance form incorrectly enforces personal number instead of family number

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#3018]
## Describe the bug

The insurance form config incorrectly specifies personal number as required instead of family number. 

### To reproduce

1. Create a new insurance policy in the dispensing window.
2. See error

### Expected behaviour

Family policy number should be enforced as required (personal as optional).

### Proposed Solution

Update `formInputConfigs`.

### Version and device info

- App version: v5.1.1.
- Tablet model: Nexus 10 (Android emulator).
- OS version: API 28.

### Additional context

N/A.

**Comment by wlthomson** [comment]
Fixed by #3028.

**Comment by nishaSussol** [comment]
## Testing
Tested in mobile v6.0RC3

Steps to reproduce or otherwise test the changes of this PR:
- [x] Can create insurance policies without a personal policy number. **-PASS-**
- [x] Cannot create insurance polices without a family policy number. **-FAILED-**

@wlthomson 
Insurance policies can be created without a family policy number. It's confusing here if the Family policy number is really a required field or not
