### ISSUE TITLE
Items: adding items from master list while creating req crashes apps.

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#3086]
## Describe the bug

If master list has large number of items I think more than 6 or 7 hundred it crashed the mobile app. I am testing for "All items" from the master list of Myanmar which has more than 1000 items.

### To reproduce

1. Create supplier req.
2. Add items from master list.
3. Make sure to choose the master list which has large number of items.

### Expected behaviour

Should not crash.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:5.1.1
- Tablet model: lenovo

**Comment by joshxg** [comment]
hi @anildahalsussol 

I have taken the altest MAM data file today - and used the hydrochlo master list to create a new requisition. This did take a couple of seconds, which isn't a nice user experience, but the app did not crash.

I believe this master list has all items for MAM (518) - maybe I need to use your data file?

**Comment by anildahalsussol** [comment]
@joshxg : Sorry it's for Myanmar ghsc. You can try from there demo server I can give you credentials.

**Comment by bijaySussol** [comment]
Guys, do not trust on Myanmar demo server datafile.
lately, demo datafile had been too much exposed from me obviously only after permission granted from Aung Oo.
So, Do not trust the demo Myanmar cloud server data - better test with there live cloud server.

**Comment by joshxg** [comment]
@bijaySussol I am to scared to touch anything now!!! I will just create a data file with a lot of items hahaha

**Comment by joshxg** [comment]
Hi 

I have tested this a lot now using a master list with 1500 items. It is quite slow to add the items, but it does not crash the app..

We should implement #2294 to solve the slow to load issue, but otherwise without being able to recreate I can't do anything..!

@anildahalsussol only other thing I can think of is that there was something wrong with the masterlist and items being added.. I know this is a long time since reporting the issue, but if you are still able to recreate this, let me know!
