### ISSUE TITLE
Customer program requisition: Keyboard disappear when entering number

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3188]
## Describe the bug

When entering the number against the editable field > The Keyboard disappear.

### To reproduce

1. Create a customer programme requisition
2. Once that is create > View its details > Must have more than 15 lines [ I used IC datafile ]
3. Try to enter the number of editable field from last 10 lines
4. See error > Keyboard disappear

### Expected behaviour

Keyboard should not disappear

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: mSupplyMobile-6_0_0-rc9-universal-release.apk
- Tablet model: SM-T515
- OS version: Android 9

### Additional context

See video: https://www.dropbox.com/s/1tzr20yajwygxoy/vid_20201104_145055.mp4?dl=0

**Comment by joshxg** [comment]
So.. I guess this is the same as the one you have reported before. So I googled  your tablet - it is 1920 x 1200 resolution?

I wonder - the keyboard on your screen looks very big compared to the samsung we have.. i wonder if that can be reduced in size in the OS settings on the tablet, or if we can do that programmatically from within the app.. something to look at.. because even if the keyboard was there, you can only see 3 rows, and that is not ideal

**Comment by joshxg** [comment]
Going to use #2941 issue
