### ISSUE TITLE
Customer program order: Modal to show the selected lines does not always stick at bottom

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#3189]
## Describe the bug

Selecting a line to show the info into the modal > It does not always stick at bottom

### To reproduce

1. Create a customer programme requisition
2. tap to enter the quantity against any enterable field
3. Select that row

### Expected behaviour

Over to @joshxg - But as far as is seen: Modal should always be on bottom

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: mSupplyMobile-6_0_0-rc9-universal-release.apk
- Tablet model: SM-T515 
- OS version: Android 9

### Additional context

See video: https://www.dropbox.com/s/qrjw3wwuqq6gtuz/vid_20201104_145521.mp4?dl=0

**Comment by joshxg** [comment]
Thanks @bijaySussol - Great find. This is a problem with the modal component.. it is too slow to update and doesn't know what's going on when the keyboard is up. 

I think it is a good one to fix but to do that, it needs to be fixed in a few different places, so I will look into that but don't want it to block the feature - thanks!!

**Comment by joshxg** [comment]
Linking to #3213
