### ISSUE TITLE
Add cumulative breach calculation logic to BreachManager

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#3474]
## Is your feature request related to a problem? Please describe.
Add cumulative breach calculation logic to mobile app

## Describe the solution you'd like
- Add methods to BreachManager to calculate cumulative duration above/below configured thresholds
- When consecutive breach calculation is performed, call above method to also do cumulative breach calculation

## Implementation
N/A 

## Describe alternatives you've considered
Not sure, CCE app has this calculation done in SQL Lite query but think we would want it to be DB agnostic?

## Additional context
N/A

**Comment by joshxg** [comment]
Cumulative breaches can be calculated really easily through db queries - for realm: `UIDatabase.objects("TemperatureLog").filtered("sensor.id = {for a specific sensor} && temperature > {temperature of breach threshold}").sum("logInterval") > {duration in the cumulative breach config}`

but you need to do this for some "period" - really a cumulative breach is "how much time spent over some X temperature during some period" - you can't really create a temperature breach record for this - What is the period? When do you create new ones? etc

Breaches in general are calculated/derived from the temperature logs - the actual temperature breach records are an optimization because consecutive breaches are pretty calculation heavy - cumulative breaches aren't

**Comment by katherine-sussol** [comment]
Oh, interesting - I just noticed the logic is already basically in the fridge detail page haha, so... this isn't needed?

**Comment by joshxg** [comment]
well:

- I do think it's weird we have a breach manager that only does half the breaches - but if we were to add anything in to `BreachManager` it would be so db specific that it would just be to `set` some function to calculate it. Bad? Good? I dunno?
- It's evidently confusing that there aren't records for them
- I dunno what I'm doing

Basically, no this isn't 'needed' except to fix the above issues which if you think they need fixing and you have a solution, i'm happy to go with it? 🤷

**Comment by katherine-sussol** [comment]
Hmm, yeah I think the fact we have a class called `BreachManager` that doesn't actually manage all breaches is the most confusing (easy not-really-a-fix could be a simple rename to `ConsecutiveBreachManager`). I kind of like the idea of having a function (externally settable) available in `BreachManager` to also calculate cumulative breaches, that way someone who wanted to find out how breaches are calculated kind of has a centralised place to go to (`BreachManager`) to start? 

I don't necessarily think cumulative breaches need records (probably would end up just being a subset of temperature logs anyway?) - maybe it's just another case of naming, `TemperatureBreach` at a first glance would make me think I can go in to find all the breaches haha. Anyway not a huge deal imo.

Dunno about the third point, I don't think I do either.

**Comment by katherine-sussol** [comment]
I'm going to close this - I originally opened it because I thought we were missing the logic as the cards weren't updating. Turns out it was there, just needed a small fix (which was done with #3488).
