### ISSUE TITLE
Adding additional fields to the name form

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3619]
## Is your feature request related to a problem? Please describe.

We need to add some additional fields to a name record which require input widgets to be added to the patient form.

## Describe the solution you'd like

For all of the fields here: https://github.com/openmsupply/mobile/issues/3614
- Add a `FormInputConfig` here: https://github.com/openmsupply/mobile/blob/471c1e79f1d2aec239401e9e45c6ee8eea2295c3/src/utilities/formInputConfigs.js#L64
- Add the input configs to the patient form config: https://github.com/openmsupply/mobile/blob/471c1e79f1d2aec239401e9e45c6ee8eea2295c3/src/utilities/formInputConfigs.js#L313-L323

?

## Implementation

As above

## Describe alternatives you've considered

Doing the patient form the same as the new patient survey form 🤷 

## Additional context

Depending on how the form survey is implemented, the patient form might look funny!

**Comment by joshxg** [comment]
@mark-prins 

If we are to make the `Form` component and put it side by side this patient form (Or, in another tab), then do we make the `Form` component look bad like the patient form or change the patient form to look nice at the same time as making the `Form` component look nice?

🙄 😕 ❓ 

I am thinking that if we use tabs, maybe we don't need to make them look the same (in the patient modal thing), and maybe we make it a 4 step process when dispensing..? Then hopefully we can 

1. Make the new `Form` component + widget look not as terrible
2. Seperate out the current forms from the new survey forms, so it's not SO jarring when they look different.
3. Hopefully afterward we can go back and convert the older forms to use this new form thing
4. When someone else uses the vaccine dispensing thing and they dont have a survey form we just revert to 3 steps

🤷

**Comment by mark-prins** [comment]
the current patient form doesn't look that bad!

Preferred option:
1. make the new form look like the current one
2. show them both side by side on the same page
3. then, in an upcoming phase, make the both look better

that'd be the quickest for now, and keep the user flow as a three step process. 

I think though, that filling out a `name` form and then clicking next and going on to a second form of patient details isn't that bad. The type of information on each form is a little different, so would be ok to use. Having both forms look very different isn't great and I'd make the new one crappy rather than having both very different.

Ideally, yes. make the `name` form use the new JSONschema idea and make is look better. we can schedule that in..?

**Comment by joshxg** [comment]
OK that all sounds like a good plan to me

**Comment by joshxg** [comment]
This one will be waiting for #3612
