### ISSUE TITLE
Supplier Invoice: Location option icon get enabled for non vaccine item

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3664]
## Describe the bug

In Supplier Invoice, Location option icon get enabled for non vaccine item

### To reproduce

1. Go to Supplier Invoice -> Create a new Supplier Invoice
2. Add non-vaccine item. Location and VVM columns is hidden
3. Add vaccine item. Location and VVM column is shown
4. See error. For non vaccine item, Location option icon is not disabled

https://user-images.githubusercontent.com/58979436/109918655-72c50d80-7cdf-11eb-8cd4-bb47a8159a49.mp4

### Expected behaviour

For non vaccine item, Location option should be disabled

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0 rc8
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #3648

**Comment by katherine-sussol** [comment]
Hmm I can repro this - I'm unsure if this is expected or not. My guess is since the column is hidden by default if there are no vaccine items it probably isn't intentional to be able to add a location to them? @joshxg is this a fair assumption?

**Comment by joshxg** [comment]
Ah yeah this is left over - since we were allowing locations to be created as well as sensors we allowed for any item to be assigned to a location. Now since we only allow sensors to be created (and have a 'shadow' location linked to it), it doesn't make sense that we can assign normal items.

This should just require a change here: https://github.com/openmsupply/mobile/blob/471c1e79f1d2aec239401e9e45c6ee8eea2295c3/src/widgets/DataTable/DataTableRow.js#L337-L359

Just like VVM status column is disabled for non vaccine items, we can do the same for the column key which matches a location (I'm guessing is this [one](https://github.com/openmsupply/mobile/blob/471c1e79f1d2aec239401e9e45c6ee8eea2295c3/src/pages/dataTableUtilities/constants.js#L32) but not 100%)

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0 rc9 

- [x] For non vaccine item, Location option should be disabled
