### ISSUE TITLE
Record site of vaccination and vaccinator

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#3682]
## Is your feature request related to a problem? Please describe.

`Are we able to include information on the vaccinator e.g. vaccinator ID? And site of vaccination?`

## Describe the solution you'd like

Add text fields to the final step of the process
Retain the values entered and pre-populate if the user chooses to save and vaccinate another patient ( see #3681 )

## Implementation

~~Add two text fields to step three, below the batch list.~~
~~Save these to `user_1` and `user_2` of the prescription ( `[transact]` )~~

- Create a table in desktop `[name_to_be_decided]` (`vaccinator` / `administrator` ??)
- Add a field to `[trans_line]` for the ID of the administrator/vaccinator/dispensinator
- sync the table to mobile
- Allow selection of the vaccinator in step three
- Record against the `[trans_line]`

## Additional context

Originally decided to use `[trans_line]` as this allows for the possibility of different vaccinators and sites - now that site refers to a geographic rather than personal location, it is probably more relevant to have the data on the prescription rather than repeated for each line ( although in the current workflow there is only one line per transact anyway 🤷‍♂️  )

**Comment by joshxg** [comment]
- Think these are pretty valid data points to collect when dispensing a vaccine and should be standard options on a vaccine prescription, just like a comment?
- Agree there's no point using trans line anymore.
- Could be ideal to have some sort of table for `vaccinator`..? (Clinician?)
- Agree site needs to be a text field - otherwise were can we get the list of locations/villages from?

**Comment by craigdrown** [comment]
I think there is a rare case where there can be both a prescriber and a vaccinator. Usually not- vaccination is part of a scheduled process, so the schedule determines eligibility, not a prescriber
In NZ now some pharmacies are doing vaccinations, so you could imagine this spreading to countries we work in.
In my new-found desire to not overload existing meanings, can we make a new "vaccinator" table? (There are spare tables- e.g. [regimen_line] - I've just checked and gary hasn't used them for his new asset work ;-)  )

**Comment by joshxg** [comment]
I forgot I got a flu vaccine last year at a pharmacy in Henderson. I was lead into the store room/office where they left me alone for 15 minutes surrounded by a lot of drugs. The prescriber was also the vaccinator though!

OK..

- Primarily wanted to use a table because I don't know where the choice of vaccinators will be, otherwise.
- By using the clinician/prescriber table we have most of the sync/setup for it done (Would need to add a `vaccinator_ID` on `transact` rather than the `prescriber_ID`) (who was the silly goose who named it `Prescriber` in mobile, anyway?)
- I am concerned `Vaccinator` might be a little specific- it seems as if it is for a rare case which could be used in the future which for me are signs of potentially prematurely normalising- Are there other use cases where we record who 'gives' a medicine such that we could have a "`giver_of_the_medicine`" table rather than "`vaccinator`"? (I think I am sick - I am questioning a new table?? 🙄 ). If you are happy this is more of a 'when' over 'if' then 🤷 
- Is there more metadata of the vaccinator other than their name? `[options]` would be a good choice, if not.
- With a `vaccinator_ID` on `transact` we can migrate to a `vaccinator` table when it proves necessary, whatever we use?

Anyway, if we are to go with a `vaccinator` table, we need to do it quickly, so proposed table:

![image](https://user-images.githubusercontent.com/35858975/110201894-5b964380-7eca-11eb-81d8-d938339b2093.png)

**Comment by mark-prins** [comment]
Decided to not implement the site of vaccination, we'll use external metadata to create reports of this. The user flow is neater this way. Note that the vaccinator will use a table, as noted above.

**Comment by joshxg** [comment]
- Desktop issue for the table : https://github.com/sussol/msupply/issues/8200
