### ISSUE TITLE
Create automatic order creates zero quantity lines

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3738]
## Is your feature request related to a problem? Please describe.

When creating an automatic supplier requisition order, lines are not pruned.

## Describe the solution you'd like

Ensure no zero quantity lines are created with a supplier requisition automatic order

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by wlthomson** [comment]
Fixed by #3752.

**Comment by ArpitaSussol** [comment]
Tested in V7.0.0 RC11

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Create a new supplier requisition. Press `"Create Automatic Order"`. No items with a requested quantity of `0` are added to the requisition.
- [x] Finalise a supplier requisition with at least one item with a requested quantity of `0` (and one with a requested quantity of more than `0`). Finalise the requisition. All items with requested quantities of `0` are pruned from the requisition.
- [x] Finalise a customer requisition with at least one item with a requested quantity of `0` (and one with a requested quantity of more than `0`). Finalise the requisition. Toggle `"Customer data"`. All items with requested quantities of `0` are pruned from the requisition.
- [x] Finalise a customer requisition with at least one item with a requested quantity of `0` (and one with a requested quantity of more than `0`). Finalise the requisition. Toggle `"Supplier data"`. All items with requested quantities of `0` are pruned from the requisition.
