### ISSUE TITLE
When temperatures of logs cross both breach boundaries, no breach is created

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3757]
## Describe the bug

Crossing over breach boundaries causes incorrect behaviour.

The way breaches are calculated, logs are continually put into a stack until a breach is created. A breach is created when all the logs in the stack exceed a breach config threshold and the duration of all the logs exceed the config duration.

If there is a log which does not exceed the temperature threshold, the stack is reset.

This means if you have configs for less than `2` and greater than `8`, then if you have one log of `1` degree and then all the other logs are above `8`, then no breach is every created. For example and array of temperatures:

`[1,9,9,9,9,9,9,9,9]` - the stack is never reset, but no breaches are made, even though the sensor is in a hot breach.

### To reproduce

as above

### Expected behaviour

a breach should be created

### Proposed Solution

TBD

### Version and device info

- App version: 
- Tablet model:
- OS version:

### Additional context

Think this is very unlikely to occur. However, if it does, then no breaches would ever be created for the sensor which is quite bad.

**Comment by katherine-sussol** [comment]
Hmm seems tricky 🤔 . It sounds like maybe before pushing a log onto the stack, we could try 'resetting' it if the breach config that caused the log to be pushed onto the stack in the first place is different to the config causing the current log to be pushed on? (could perhaps tweak the `couldBeInBreach` method to return the actual config rather than just a bool)

I think (if the input validation is correct) a log in breach would usually only be in breach of one config (either `HOT_CONSECUTIVE` or `COLD_CONSECUTIVE`, but not both)? 

@joshxg any thoughts/breach expertise 😆 ?

**Comment by joshxg** [comment]
Yeah, the range of temperatures for a breach should be exclusive, so we can assume the log can only belong to a single breach.

I haven't looked to deeply, but I think what you're saying sounds right. Essentially we just need to check that when adding a new log into the stack for creating a breach, it is for the same config.

Maybe having some reference to the config for which a breach is being created for (the current stack of temperature logs) and we instead pass the config and the log to determine if the log will continue that breach or not?

**Comment by katherine-sussol** [comment]
Closed with #3949
