### ISSUE TITLE
Vaccination: The form is not fully PREPOPULATED with the ANSWERS from the LAST survey, shows only Last Items but not Batch

### ISSUE THREAD

**Issue by ArpitaSussol** [openmsupply/mobile#3809]
## Describe the bug

The form is not fully PREPOPULATED with the ANSWERS from the LAST survey, shows only Last Items but not last saved Batch

### To reproduce

1. Go to Vaccination -> Create a prescription -> Select an Item(with many batches)
2. Choose any random batch, not first listed batch
3. Confirm it. Create another Prescription -> Go to Item page(step 3)
4. See error. Item is prepopulated based on last answers but first listing of batch is selected every time

https://user-images.githubusercontent.com/58979436/111748460-aa73ae00-88b8-11eb-9f44-f6d48a023a60.mp4

### Expected behaviour

Batch should be prepopulated based on last answer

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: V8.0.0 RC2
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #3801 for the testcase
**"The form is PREPOPULATED with the ANSWERS from the LAST survey"**

**Comment by joshxg** [comment]
@ArpitaSussol 

Thanks- will make sure that we are only selecting batches with stock, but it is intentional that we select the batch with the most recent expiry, and if we have any batches with a decimal amount of quantity- for example, if a batch has 11.5 doses, then it means there is a vial which is open, so we will suggest using that vial first.

Also- you have a negative amount for doses.. ! that is interesting and very bad! I created this issue on desktop: https://github.com/sussol/msupply/issues/8311

**Comment by joshxg** [comment]
@ArpitaSussol 

When we test on RC5 are we able to check if you are still able to get negative doses quantity? We don't want that!! 🤣

**Comment by ArpitaSussol** [comment]
> @ArpitaSussol
> 
> When we test on RC5 are we able to check if you are still able to get negative doses quantity? We don't want that!! 🤣

sure will test that part ASAP :)

**Comment by ArpitaSussol** [comment]
No Negative doses could be seen in latest apk but i found some other issue

Created an issue #3854
