### ISSUE TITLE
Sync details get wiped while click back button of tablet

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#3926]
## Is your feature request related to a problem? Please describe.

Once I have entered sync details, username, and password. And if we click the back button and get back to the same screen all the details get wiped. But if we switch apps and return to mSupply sync details remain same as it is.

## Describe the solution you'd like
It would be nice if sync details don't get wiped out.

**Comment by joshxg** [comment]
Not sure why this is ocurring! Bit weird, but something to do with `back` handling and the `state` persistance of `FirstLoginPage`

**Comment by joshxg** [comment]
Turns out this is the desired behaviour. When pressing `back` on the last page of the app, the app is more or less closed, except .. it's not, so it can be reopened easily. But, all the UI is unmounted and we are unable to save the state here.

This would take significant work to keep these details here which I think is not worthwhile
