### ISSUE TITLE
Add QR scanning component to vaccine dispensing page

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4070]
Child of #4066

## Is your feature request related to a problem? Please describe.

As a user, I would like to be able to press a button on the vaccine dispensing page, so that I can scan a patient's QR code.

## Describe the solution you'd like
- There should be a button on the vaccine dispensing page to access QR scanning
- When the button is pressed, a modal should open to scan a QR code 
- The modal should present a viewfinder to capture the QR code and record the code if found
- The user is able to close the modal at any time and go back to a manual patient search/entry

## Implementation

TBD

## Describe alternatives you've considered

N/A 

## Additional context

Not sure about this issue format, just trying it out.

**Comment by katherine-sussol** [comment]
Not really sure what this should look like... open to any suggestions 🤔 

Patient select screen:
![image](https://user-images.githubusercontent.com/65875762/120735102-196ab580-c53e-11eb-8142-8403f6acaca0.png)
Too many buttons in one row? 

QR Modal (with emulated camera):
![image](https://user-images.githubusercontent.com/65875762/120735996-9b0f1300-c53f-11eb-8855-e2de4dea0ab4.png)

**Comment by katherine-sussol** [comment]
Closed with #4083

**Comment by ArpitaSussol** [comment]
Tested in V8.1.1 rc3

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Login to a store that is a dispensary that has some vaccine stock
- [x] Navigate to vaccine dispensing and select 'Scan QR Code'
![image](https://user-images.githubusercontent.com/65875762/121269761-80a8b100-c914-11eb-8bbb-a7f57ccf79e2.png)
- [x] If a QR code is detected, the modal will close and display a toast with the data in the QR code.
