### ISSUE TITLE
Local patient searching via QR Code

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4071]
Child of #4066
Prerequisite: https://github.com/openmsupply/mobile/issues/4068 

## Is your feature request related to a problem? Please describe.

As a user, I would like to be able to use a scanned QR code to search against all patients stored on the device, so that I don't need to manually enter search criteria into the app when dispensing a vaccine.

## Describe the solution you'd like
- Given the app has successfully retrieved a QR code:
  - A search should be performed using the QR code against all patients stored locally in the app
  - If there is a match, the user should be taken to Step 2 of the vaccine dispensing flow, with the relevant patient details prepopulated
  - If there is no match, the user should be told to wait longer while an online search is done (?)

## Implementation

TBD

## Describe alternatives you've considered

N/A

**Comment by katherine-sussol** [comment]
Closed by #4117

**Comment by ArpitaSussol** [comment]
Tested in mSupply V8-2-0-rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Scan a QR code that contains a matching barcode for a patient. 

Some test codes (needs to exist in mobile for lookup to work):
`placeHolderBarcode`:
![placeholderBarcode](https://user-images.githubusercontent.com/65875762/121824649-cfce5780-cd01-11eb-8cfc-2a272d149556.png)

`*asdasdasd*` (matches Jose Abad):
![_asdasdasd_](https://user-images.githubusercontent.com/65875762/121824676-0906c780-cd02-11eb-8afc-3c939a98d12b.png)
