### ISSUE TITLE
Enable the settings button from within the app

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#4088]
## Is your feature request related to a problem? Please describe.

mSupply mobile allows to change the Sync URL and the Sync password from its setting page.
But ATM setting page is control by mSupply preference > We probably also need a way to enable setting page within from the app itself.

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

@joshxg said this:
Josh g, [09.06.21 13:11]
Also we need to.. return the settings button when holding mSupply man

**Comment by bijaySussol** [comment]
@joshxg : 

I would like to take a challenge to do this.
But still stand?

**Comment by joshxg** [comment]
Yup!

**Comment by joshxg** [comment]
Oh.. I realised we have actually removed the functionality for long pressing the mSupply man 🤔 

I realise that we also have a LOT more functionality in the settings page now which can really mess with the app if used incorrectly. 

I am not sure how we can implement this feature securely enough so that only acceptable users are using the settings page....

**Comment by joshxg** [comment]
We can add the long press back to the mSupply man.. but now that we have features like: import data and factory reset that can if used incorrectly, cause some serious issues, I am not sure if that is OK

**Comment by bijaySussol** [comment]
Stick with the preference and make sure it is always tick
