### ISSUE TITLE
Sorting current stock can make app unresponsive

### ISSUE THREAD

**Issue by andrew-d-uk** [openmsupply/mobile#412]
Build Number: 30

Description: Title doesn't really explain it - but if you have a long list of stock in 'Current Stock' and you sort it, it may take a few seconds to sort (which is fine). But if your user is impatient and thinks it hasn't worked they may click it multiple times. And mSupply will sort it multiple times before allowing the user to make any other commands such as moving back a page. (And your user may keep clicking it as it sorts, and you end up waiting for it to sort the list 100 times!)

Reproducible: Yes

Reproduction Steps: Go to a long stock list, click to sort by quantity and keep clicking.

Comments:
Not a major issue as we can tell people not to do it, and even if they do they can terminate the app and restart (not sure whether this may have a negative impact on any processed data in the app though?)

**Comment by Chris-Petty** [comment]
Thanks Andrew,

You are right, if someone gets carried away and spams the sorting (as many would given delay) it'll make jam up the app. There are a few approaches and optimisations that could fix this.

- Debounce the sort function so it doesn't stack up calls when spammed
- Cheeky hack/optimisation, if the sort direction (isAscending) is just being switched on the same column, the array of records being displayed should just be reversed rather than bothering with other sorting/filtering going on.

**Comment by Chris-Petty** [comment]
I think I erroneously tagged this as fixed in a commit

**Comment by joshxg** [comment]
I think this is related to the data table performance issues which has enough issues currently and has a rewrite coming in hot. Closing this issue
