### ISSUE TITLE
When saving vaccination site data - store in [transact]custom_data as an object

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4198]
Child of #4176 
 
## Is your feature request related to a problem? Please describe.
Tonga (and Kiribati??) want #4176 and this is a step required to achieve it.

## Describe the solution you'd like
See #4176

## Implementation
- When '`Confirm`' (or '`OK & Next`') are selected at the end of the vaccine dispensing flow (currently the screen where the vaccine is selected), ensure that the data entered in the form is stored in `[transact]custom_data as an object`

## Describe alternatives you've considered
Making someone unhappy? Maybe this didn't even need to be a sub-issue 🤔  can close two issues with one PR if needed though.

## Additional context
N/A

**Comment by katherine-sussol** [comment]
Closed by #4209

**Comment by ArpitaSussol** [comment]
Tested in mSupply V8.2.3 with Tonga-vax datafile

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Create a prescription with siteData (needs FormSchema with type `VaccineSite`), check Realm Explorer (and/or export and check the contents that way) and verify that the siteData is saved to the transaction
- [x] Sync to Desktop - check via record browser that [transact].custom_data contains the site data for the vaccine prescription just created
