### ISSUE TITLE
Patient Middle Name

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4233]
## Is your feature request related to a problem? Please describe.

Kiribati want a patients middle name

## Describe the solution you'd like

Be able to add a patients middle name.

## Implementation

- There is a `middle` field on `[name]` on desktop. We need to sync it to and from.
- Add a new field `middle` into the patient form config.

## Describe alternatives you've considered

- Just using a `,` on the first name 🤷 

## Additional context

N/A

**Comment by katherine-sussol** [comment]
How much middle name is needed? 🤔 

I think searching locally makes sense...what about remote lookup? (don't think API currently lets us search by middleName nor returns middleName)

Patient screen is also getting a bit crowded 😆 
![image](https://user-images.githubusercontent.com/65875762/125547983-72f2b31d-f2bf-404d-92ec-6d68c9bba0ac.png)

**Comment by joshxg** [comment]
uhhhhhhhh.... 

@mark-prins @adamdewey 

Do we need to put this anywhere other than the patient form..?

**Comment by adamdewey** [comment]
I don't think we need to show on the Patient Screen or to be able to search by it, at least not initially. 

The main use case is just to be able to capture it, so having a field in the Patient Detail screen: 

![image](https://user-images.githubusercontent.com/19318937/125556351-a4910dbf-a98a-4005-a855-f6177d3ef5e3.png)

**Comment by katherine-sussol** [comment]
@adamdewey Cool thanks 😄  - gonna leave it off the lookup screen!

Just thought a bit more about the remote lookup...If a patient was created in another store with a middle name and someone looks them up remotely, it's going to come up with an empty middle name on the edit form unless we update the Desktop API - I think that might be a bit weird/unexpected?

**Comment by joshxg** [comment]
True that. Will need to make the change to desktop 😢

**Comment by joshxg** [comment]
https://github.com/sussol/msupply/issues/9188

**Comment by mark-prins** [comment]
agree - doesn't need to show anywhere except the patient form and then maybe the dashboard.
Another question: should it be used in the `name` ( I think not, btw ) currently `name` is `[last], [first]`

**Comment by adamdewey** [comment]
ah thanks Kat, hadn't twigged they were stored separately for each store. 

Yeah would be better to be able to retrieve via the API

**Comment by ArpitaSussol** [comment]
Tested in mSupply V8.2.0 rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Try to add a new patient with middle name (then lookup and verify it was saved)
- [x] Try to edit a patient's middle name (then lookup and verify it was saved)

@katherine-sussol In server side a bit confusing, hoping in future there will be fixes for it in server side?
![Screen Shot 2021-07-26 at 5 25 07 PM](https://user-images.githubusercontent.com/58979436/126983045-a232e127-2af6-4874-b8a7-9fda28842034.png)
![Screen Shot 2021-07-26 at 5 24 55 PM](https://user-images.githubusercontent.com/58979436/126983063-5eaade52-840b-4e9a-8281-34cfb0d39868.png)
