### ISSUE TITLE
AEFI : select from vaccination history

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/mobile#4238]
## Is your feature request related to a problem? Please describe.

As per [patient hub issue #108](https://github.com/openmsupply/patient-hub/issues/108); we have a client who would like to show all patient vaccinations inside a JSON schema AEFI form, and allow the AEFI entry person to select any number of them.

## Describe the solution you'd like

If there is a JSON schema element in the correct format then update the `enum` within it with vaccinations for the selected patient. Show these as a multi-select list to the user.

## Implementation

- After patient selection, perform an online patient history check. 
- Filter these by vaccination
- populate the JSON form element

**Comment by joshxg** [comment]
Maybe adding a `transact_ID` to `[adverse_drug_effect]` and adding a selectable option outside of the `JSONForm`, unrelated to the json schema?

**Comment by mark-prins** [comment]
it's another one that needs to be multi select unfortunately, otherwise that would be a much better idea.

**Comment by joshxg** [comment]
join table? 🤷 

Seems to be somewhat reasonable to bake in to the ADR implementation

**Comment by joshxg** [comment]
Or a ADR fk on transact maybe more suitable..?

**Comment by ArpitaSussol** [comment]
@mark-prins i am not sure about the testing steps.

I have [AdverseEffect.txt](https://github.com/openmsupply/mobile/files/7044166/AdverseEffect.txt) file.

DO i need to add 

 "causes": {
      "title": "Possible causes",
      "description": "Select which vaccinations you think may have caused this reaction",
      "type": "array",
      "items": { "type": "string", "enum": ["No vaccination history"] },
      "uniqueItems": true
    },

this block of json data into existing ADR txt file and run it into FC to reflect changes???

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc0

Steps to reproduce or otherwise test the changes of this PR:

- [x] Add an ADR without the schema change: behaves as normal, with no search
- [x] Add an ADR for a patient with no history: will show the checkbox 'No vaccination history'
- [x] Add an ADR for a patient with history: searches, shows options
- [x] Only shows vaccinations, not other dispensed items in the history
- [x] Add when the server is offline: still lets you create an ADR after a short lookup time
- [x] When the server is offline you can see local patient history
