### ISSUE TITLE
Mobile crash (version 8.2)

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4259]
## Describe the bug

Have consistently experienced random crashes on 2 different tablets now, and on 2 different datafiles. 

Just had another one - happened while sitting on the Patient Registration screen. 

May be relevant that both tablets are also failing to show ColdChain sensors? Thought it was due to upgrading to Android 10 but Nick's tablet seems ok on 10. Will ask him to try my datafiles. 

### To reproduce

Hard to reproduce unfortunately. Seems to happen randomly, will try to add any relevant info here if I manage to narrow it down. 

Last crash happened after: 
1. Start app
2. Open Patient Registration
3. Make change to JSON schema on server
4. Sync Mobile to pull new schema
5. Exit Patient Registration
6. Go back into Patient Registration
7. Add new Patient
8. Scroll down a bit, open a few dropdowns
9. Sit for a while
10. Crash

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.2 rc1
- Tablet model: Lenovo TB-X505F
- OS version: Android 10
- Datafile: https://kiribati-vax-training.msupply.org:2048
- Sync site: tablet2/tablet2
- User: user2/user2

**Comment by joshxg** [comment]
Thanks @adamdewey  - how frequently are these crashes occurring? (Hard question to answer 🤣 )

@mark-prins @katherine-sussol 

I think we have started to get a lot of crashes since adding the component to render JSON Schema forms?

Coincidentally this is the same time as having upgraded realm and a whole bunch of other deps (incl RN) and also, when a whole bunch of new users started using mobile more frequently (So the bugs could have existed on an older version, we just weren't seeing them as much!).

I've seen reports of people saying to use Hermes (which we can't, right now) - hopefully the new realm version will be available soon for us to enable it..

**Comment by adamdewey** [comment]
>Thanks @adamdewey - how frequently are these crashes occurring? (Hard question to answer 🤣 )

Hmm, maybe 2 or 3 times a day?

**Comment by adamdewey** [comment]
So, not sure how helpful this is, but I accidentally captured a crash (at 1:08) while trying to record something else. 

https://www.screencast.com/t/qGEuFhqIk7Q6

**Comment by joshxg** [comment]
It's really useful - thanks.

I think this crash was this captured one here: https://github.com/openmsupply/mobile/issues/4324

I know they're random so it's hard to say, but anecdotally at least, do you think it's usually while navigating/switching between screens/tabs?

**Comment by adamdewey** [comment]
Hmm, yes I'd say usually I'm performing some navigation action.

**Comment by katherine-sussol** [comment]
So far this is looking promising in 8.3.0-rc0 🤞  (after #4321)
Haven't seen any new bugsnags created for this version yet (but also might just mean not enough testing 😆 ).

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0 & 8.4.0.

Replicated steps as mentioned in https://www.screencast.com/t/qGEuFhqIk7Q6. NO crash happens.
