### ISSUE TITLE
Create a vaccination name note when creating a vaccination prescription

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4296]
## Is your feature request related to a problem? Please describe.

- Want to track vaccinations of patients without having their transactions

## Describe the solution you'd like

- When creating a prescription, create a name_note with the patient event ' 🤷  ' which has the vaccination event details

## Implementation

Unsureee!

## Describe alternatives you've considered

- Add an asterix to the patients name

## Additional context

- https://github.com/sussol/msupply/issues/9253

**Comment by joshxg** [comment]
Realising that maybe we should integrate this more with the refused vaccination name note.

- Rather than an `RV` patient event- just a `vaccination` event
- Rather than creating a separate `RV` name note, create the name note for a `vaccination` event
- The name note for a `vaccination` patient event type has the shape
```
{
    refused: bool,
    vaccine: item name,
    vaccinator name: name of vaccinator
    date,
    batch name,
}
```

🤔  

Would again need to change tonga data..

**Comment by joshxg** [comment]
@katherine-sussol @mark-prins think it's worth changing the `RV` event? 🤷

**Comment by joshxg** [comment]
Just spoke to Nick and I I thought they were on a break but .. not anymore!

Not sure if we'd have to migrate their data though.. but the dashboards would have to be updated to handle both ways if Tonga upgraded 🤔

**Comment by katherine-sussol** [comment]
Does seems neater to have it all nicely wrapped up in one vaccination event but I'm not 100% sure how the data migration works and how much of a headache it'd be... 
Would we do something like rename the `RV` event (to...idk...`VAX`??) and possibly change the data for all existing refusals to something like
```
{ 
  refused : true,
  vaccine: null,
  vaccinator: null
  batch name: null
}
```
? (is `entryDate` is equivalent to `date`?)
I guess no one would really ever refuse a specific vaccinator or batch either so I'm not sure if the shape is confusing 🤔 , usually it's just 'don't want jab'?

**Comment by mark-prins** [comment]
re migration: there are only 3 `RV` name notes in the Tonga database, so migrating them won't take long.

I'm thinking that we don't have to migrate the transactions - as the `[transact]` will still be created, so the existing dashboard logic will be fine without migration. It's only the refusals ( not used in the dashboard ) which are changing. the other part of the name note is an addition rather than a change and we don't need to use it.

The other discussion we've had recently was with the WHO consultants who prefer 'consent given' - I argued that consent and refusal were just different sides of the same coin, and that there's no need to ask for consent as a lack of refusal is the same as consent. They are asking both questions; I think we stay with refusal.

```
{ 
  refused : false,
  vaccine: 'name of vaccine - do we need code? I think no',
  vaccinator: 'name of vaccinator'
  batch: 'batch number'
}
```

and

```
{ 
  refused : true,
}
```

I'm thinking batch is often batch number rather than name. Do we also include expiry? 
Another requirement added recently was the batch number. I'm thinking not to include in this - though perhaps that would be a useful item to add in the UI and is therefore good to include here?

**Comment by joshxg** [comment]
Great, thanks. I think I might go ahead with the consolidated event, then (I haven't made any progress, yet- having fun with 4d sync 🙃 )

I was thinking to go broader on the details saved.. just incase....

```
{
  refused : false,
  vaccine: 'name of vaccine - do we need code? I think no',
  vaccinator: 'name of vaccinator'
  batch: 'batch number'
  transaction: *full stringify of the transaction and trans line 🤣 *
}
```

**Comment by ArpitaSussol** [comment]
Tested in V8.2.1

@mark-prins 
- [ ]  Create a vaccine prescription where everything is standard. Sync and view the name note on desktop (Through record browser :)) - Couldn't see any record in Name_note table.

https://user-images.githubusercontent.com/58979436/127647324-b8f69381-ec3e-480b-a3d8-b5b293dcc7c2.mp4

https://recordit.co/T7CNQbK1Mj

anything i am doing wrong in following steps???

**Comment by joshxg** [comment]
@ArpitaSussol sorry we need a `patient_event` with the `code` `"vaccination"`
