### ISSUE TITLE
Handle the display of remote vaccinations when no internet available

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4347]
## Is your feature request related to a problem? Please describe.

Title sounds a bit nonsensical but bear with me..

As part of the work for the Kiribati COVID-19 rollout we did a couple of things: 
- allowed the download of all global patients and their medical history to each tablet's local storage. 
- added a patient medical history button to the patient selection list in the vaccination module.

The idea is that a patient's medical history is available to view even if there is no internet connection (as it has been stored locally) .

This new patient medical history button correctly displays the medical history. 

However, there are also 3 other places where patient medical history can be accessed, and **these 3 other places do not display the patient's medical history correctly when there is no internet available**. 

The 3 other places are: 
- The Dispensing module patient medical history button
- The Dispensing module vaccination lookup in the ADR form
- The patient medical history button in the final step of the Vaccination module. 

For each of the above places local vaccinations are displayed correctly but remote vaccinations (i.e. vaccinations administered to the patient in a different store) do not appear if there is no internet available. The lookup appears to be attempting to retrieve from the server rather than looking in the local storage. 

See screenshots: 

1. New patient medical history button in Vaccine module

<img width="1280" alt="2021-08-10_11-37-29" src="https://user-images.githubusercontent.com/19318937/128788696-db0f04f0-5e1e-44a2-8b99-19d705d4431e.png">

2. Internet off. Local and remote vaccinations correctly displayed: 

![image](https://user-images.githubusercontent.com/19318937/128792398-eaa999e4-e3d8-4d03-85a5-f4c0c522888e.png)

3. Dispensing module patient medical history button: 

![image](https://user-images.githubusercontent.com/19318937/128792434-dd67525e-b2ac-4acc-95c4-64a2c6207e00.png)

4. Internet off. Only local vaccinations show. 

![image](https://user-images.githubusercontent.com/19318937/128792453-5d807e3d-4750-4523-b1dd-71ab8fac68b7.png)

5. Dispensing module ADR vaccination lookup: 

![image](https://user-images.githubusercontent.com/19318937/128792468-9cabd973-9857-4e7e-9a50-74e7ced8d309.png)

6. Internet off. Only local vaccinations show: 

![image](https://user-images.githubusercontent.com/19318937/128792479-b97b53ad-54d7-46bb-be61-621642fb7da6.png)

7. Vaccination module final step patient medical history button: 

![image](https://user-images.githubusercontent.com/19318937/128792496-9abb9954-6054-4268-b1a6-fcf5f4e82d7d.png)

8. Internet off. Only local vaccinations show: 

![image](https://user-images.githubusercontent.com/19318937/128792505-fb2df11a-41e5-4620-9c4b-ce7272fcf81e.png)

## Describe the solution you'd like

The 3 other places to display a patient's medical history in a similar fashion to the new Vaccine module patient medical history (i.e. to retrieve remote vaccinations from local storage if available). 

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

Screenshots taken from 8.2.2

**Comment by katherine-sussol** [comment]
Had a brief look at this - 
It seems the new vaccination history button in the vaccine module is looking at `name_note` records that get created whenever a patient is vaccinated (added for the Kiribati offline support feature).

I'm guessing for Tonga (is anyone else using this feature?) historical vaccinations won't have `name_note` records created for vaccinations, so probably need to keep the existing logic of these 3 pages looking at transaction records rather than name_note records...(otherwise historical users will lose visibility of their vaccination history)

Wondering if appending vaccination name_note records to the local history, and filtering out local transactions that... match the vaccineDate and item code(??) of any vaccination name_notes would work? 
@joshxg @mark-prins any thoughts?

**Comment by joshxg** [comment]
@katherine-sussol ! Thanks for looking at this, I'd forgotten.

Since @npendergrast has made this issue here for Tonga to essentially have the same setup as Kiribati (from my understanding) https://github.com/openmsupply/mobile/issues/4369 I think we can coordinate an upgrade with some record creation to consolidate on a single solution.

What if we just made the vaccination dispensing use these name notes (and coordinate creating all the name notes on the tonga server with an upgrade), then we need less conditional logic.

For normal dispensing, we could either (In order of difficulty/effort..)
- Append the name notes (and remove the duplicate trans lines, if any)
- Something like: two tabs: Normal history and vaccination history, where the normal history filters out trans lines with vaccines, and the vaccination history uses the name notes..?
- Create name notes for all prescriptions for patients, then we can just use these name notes for a patients history (We can then have a patients history show everywhere, rather than only vaccination history.. and we can remove the lookup request for the history..)😁

**Comment by adamdewey** [comment]
Oh, interesting about Tonga!

My 2 cents: I feel it's fair enough to treat vaccinations and other dispensing reasonably separately.

>Something like: two tabs: Normal history and vaccination history, where the normal history filters out trans lines with vaccines, and the vaccination history uses the name notes..?

It does seem to happen that way in GP surgeries - one is more concerned about your near term body/medicine status (normal dispensing) and the other is more about your longer term body/medicine status (vaccines).

I don't know how hard it would be to implement, and potentially outside the scope of this discussion, but what about if we had a filter at the top of the history page where you could select the type of history item you'd like displayed.

E.g. 

- [ ] All
- [ ] Prescriptions
- [ ] Vaccines

And if we made vaccine item lines a different colour to stand out, that would be the icing on the historical cake!

**Comment by joshxg** [comment]
Fun fact: I asked my GP about my vaccination history. She took two weeks to get back to me.

**Comment by adamdewey** [comment]
Having written that comment I'm a bit worried I'll cause undue stress by derailing the original issue into an open-ended re-write of Mobile haha. 

Me and Richard had a discussion about streamlining the vaccine UX before, I wonder if it's worth getting together for a chat about this?

(I'm also still a tad unclear whether Mobile is going to survive post-omSupply?)

Thoughts @joshxg , @katherine-sussol ?

**Comment by mark-prins** [comment]
We don't want to turn the pref on for Tonga, as they have a large number of patients now and enabling would flood the network with sync traffic. And would require some retraining of staff - given that the vaccination is nearly through the second dose, we thought not to go down that path.

I thought that we could check the pref to see whether to lookup online or not. If the pref is enabled, then expect that vaccine history is available via name notes and doesn't require an online lookup.

**Comment by katherine-sussol** [comment]
_Should_ be fixed (for Kiribati or later users) with #4397
Tonga's vaccination history will disappear in 8.3.0 (until their data is migrated)

**Comment by ArpitaSussol** [comment]
Tested in V8.4.0-rc2

## Testing

Steps to reproduce or otherwise test the changes of this PR:

Needs PatientEvent with code 'vaccination' set up in mSupply Desktop
- [x] ADR vaccine history, vaccine dispensing history and regular dispensing history should all display both local and remote vaccinations if pref to view all patients history is set 
- [x] If 'Patients sync everywhere' is enabled the remote vaccinations should show up offline (assuming version of mSupply >= Kiribati version)
- [x] Dispensing history should also still fetch both local and remote regular dispensing history records.
- [x] There should be no duplicates when doing a remote fetch
