### ISSUE TITLE
Option to prevent future date selection in date pickers

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4367]
## Is your feature request related to a problem? Please describe.

A user would like to prevent their users from selecting a future date when recording the date of vaccination for a patient. 

![image](https://user-images.githubusercontent.com/19318937/129824014-902c280a-d5d5-48d2-8efd-375313b7bc39.png)

## Describe the solution you'd like

Can we add this as a configurable option to the JSON DateWidget?

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by katherine-sussol** [comment]
Thinking of something like two different options to disable past/future dates?  (defaulting to just allowing all)
e.g. UI Schema
 `"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "past" } },`
 `"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "future" } },`

And then making the date widget disable past or future dates depending on the config?
![image](https://user-images.githubusercontent.com/65875762/130010899-a53133ea-1dd5-4485-8237-db1531b71db5.png)

**Comment by joshxg** [comment]
thats good

**Comment by joshxg** [comment]
another worse idea is to define a `format: 'PastDate'` etc in the jsonSchema

**Comment by katherine-sussol** [comment]
Not available in 8.3.0-rc0 (but should be available in the next 8.3.0 rc and/or official release)

**Comment by ArpitaSussol** [comment]
@katherine-sussol not sure how to go through this test cases. I checked into Patient DOB registration section and additional info and future date is disabled but don't know how to test past scenario. 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] This uiSchema config should only allow past dates (and today's date):
 `"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "past" } },`
- [ ] This uiSchema config should only allow future dates (and today's date):
`"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "future" } },`
- [ ] This uiSchema config should allow any dates:
`"date": { "ui:widget": "DateWidget" },`

**Comment by katherine-sussol** [comment]
@ArpitaSussol It will need to be tested on a form that uses a JSON Schema for its data (e.g. the 'date of presentation' on the ADR form):
![image](https://user-images.githubusercontent.com/65875762/133958157-6665eec3-8d49-4905-947b-5a6b31269236.png)

I've found the easiest way to test is to edit the UI schema in the record browser (need to find the highest version number schema with type=ADR):
![image](https://user-images.githubusercontent.com/65875762/133958188-505dc42e-52fb-45ca-9339-fd188c9503b1.png)

Or can also edit the footrunner used to create tonga's adr form and re-run:
```
$obUiSchema.reporter.date:=New object()
$obUiSchema.reporter.date["ui:widget"]:="DateWidget"
$obUiSchema.reporter.date["ui:options"]:=New object()
$obUiSchema.reporter.date["ui:options"].dateRange:="past"
```

**Comment by ArpitaSussol** [comment]
> @ArpitaSussol It will need to be tested on a form that uses a JSON Schema for its data (e.g. the 'date of presentation' on the ADR form):
> ![image](https://user-images.githubusercontent.com/65875762/133958157-6665eec3-8d49-4905-947b-5a6b31269236.png)
> 
> I've found the easiest way to test is to edit the UI schema in the record browser (need to find the highest version number schema with type=ADR):
> ![image](https://user-images.githubusercontent.com/65875762/133958188-505dc42e-52fb-45ca-9339-fd188c9503b1.png)
> 
> Or can also edit the footrunner used to create tonga's adr form and re-run:
> 
> ```
> $obUiSchema.reporter.date:=New object()
> $obUiSchema.reporter.date["ui:widget"]:="DateWidget"
> $obUiSchema.reporter.date["ui:options"]:=New object()
> $obUiSchema.reporter.date["ui:options"].dateRange:="past" (replace with "future" or remove to test other use case)
> ```

ohh thanks @katherine-sussol :) . This is helpful

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc1

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] This uiSchema config should only allow past dates (and today's date):
 `"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "past" } },`
- [x] This uiSchema config should only allow future dates (and today's date):
`"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "future" } },`
- [x] This uiSchema config should allow any dates:
`"date": { "ui:widget": "DateWidget" },`
