### ISSUE TITLE
Kiribati training server log-in screen appears on freshly installed app??

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/mobile#4395]
## Describe the bug

After a fresh install of 8.3.0-rc0 the user is taken to a log-in page for the Kiribati training server?!

This seems very weird..

![image1](https://user-images.githubusercontent.com/19318937/131651813-18008514-f9b9-4bab-917f-3869a1bf7235.png)

![image](https://user-images.githubusercontent.com/19318937/131651829-962f0966-d648-41f2-988b-a302580ec762.png)

### To reproduce

Steps to reproduce the behaviour:

1. Uninstall all existing instances of the app
2. Download 8.3.0-rc0 universal apk from github
3. Install app
4. Open app

### Expected behaviour

Expect to be taken to the screen where you enter server sync site details. 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.3.0-rc0
- Tablet model: Lenovo TB-X505N
- OS version: Android 10

**Comment by adamdewey** [comment]
Ooh, just encountered the same thing are uninstalled 8.3.0 and installing 8.2.3

![image](https://user-images.githubusercontent.com/19318937/131746335-7f35b626-cfc9-4a6c-9818-4eac61e5982b.png)

**Comment by joshxg** [comment]
_Assumption city below_

When the app loads we scan for an existing database file within the application data for mSupply mobile. If it exists, then we've initialised, and everything's OK! 

Uninstalling the app is generally what we do to clear the app data. An alternative to be able to reinitialise is to go to `mSupply mobile` specific settings and clear `app data`.

I suspect your `app data` is not being cleared. I'm unsure if this is because maybe your device has backups setup, something has changed in android 10 where the data isn't deleted (sometimes?) or some other reason.

I'm going to assume clearing app data explicitly will cause this to go away. If that's the case, i'm unsure if this is really to much of a problem, a backup of a previously initialised site has loaded up.. a different point of view is that it's kinda cool 🤣  - although the seemingly randomness of it makes it not so cool.

Some info here: https://developer.android.com/guide/topics/data/autobackup where if we decide that backing up is no good we can explicitly can it. We currently have `android:allowBackup="true"` set.

**Comment by adamdewey** [comment]
Thanks Josh, yeah clearing app data does work. 

And I do have my Google account set up on tablet so I guess backups are happening too. 

As long as no-one else is getting the Kiribati login details appearing then happy to close this - was worried something weird had been accidentally included in the build!

**Comment by katherine-sussol** [comment]
Sometimes it _is_ tempting to hardcode login details into the app to avoid typing them in all the time...so a legit concern!
I can confirm I haven't seen any Kiribati login details when I've used 8.3.0-rc0 (if you trust developer testing 😜 )

**Comment by adamdewey** [comment]
Thanks @katherine-sussol  - I always trust dev testing 😄 

I'll close this 😉
