### ISSUE TITLE
ADRInput should look at name_notes for vaccine history

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4414]
## Describe the bug

Missed from #4347 - failed my own test case.
Local vaccinations are being skipped from the ADR vaccination history.
Happens only in the current develop branch, not in any released app versions.

### To reproduce

Steps to reproduce the behaviour:

1. Create a vaccination transaction (don't sync)
2. Ensure the form schema for ADR has a vaccine history element
3. Create an ADR and try to add the vaccination as a possible cause
4. See missing vaccination

### Expected behaviour

Should see the local vaccination

### Version and device info

- App version: develop branch
- Tablet model: Emulator
- OS version: 8.1

### Additional context

N/A

**Comment by ArpitaSussol** [comment]
Tested in V8.3.0-rc1


## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Create a vaccination transaction (don't sync)
- [x] Ensure the form schema for ADR has a vaccine history element
- [x] Create an ADR and try to add the vaccination as a possible cause
- [x] vaccination history should be there
