### ISSUE TITLE
Kiribati (1.7.a) View vaccination events in Mobile

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#4623]
## Is your feature request related to a problem? Please describe.
Update mSupply Mobile to allow the user to view previously captured vaccination event data on a per-patient basis.

## Describe the solution you'd like

There's currently a vaccine history modal but it is quite sparse and can't be opened to view details.
Need to figure out a suitable UI to display detailed view with option to later edit/delete.

This ticket will add the ability to view data for vaccination events created from this point onwards. 

#4638  will cover the work needed to update existing older data to make it compatible with this new functionality. 

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Comment by katherine-sussol** [comment]
Confirmed today that this means displaying (somehow) all 3 of the following:
- Vaccination Event name notes
- [transact]custom_data name notes (somehow)
- PCD Name Note from time of vaccination

**Comment by adamdewey** [comment]
From discussions between myself and Kat, the rough plan is to: 

- Keep the vaccination event rows in the vaccination history
- Have a button that will allow the user to dig deeper and view the detailed event data for each row (possibly combine all data into a vertically scrollable splitscreen?)
- Have a preference flag that will use the JSON vaccination date instead of the system entry date on the event row view

**Comment by adamdewey** [comment]
Ooh, just had another thought.

While we're switching the JSON date in the list view, it would be great if we could also use the JSON dose in that column instead of the system one - that's another thing that Kiribati are very keen on. 

<img width="1280" alt="2022-04-05_12-11-31 (1)" src="https://user-images.githubusercontent.com/19318937/161654862-708b2676-078c-4747-a174-6054ac6e1231.png">

**Comment by katherine-sussol** [comment]
> Ooh, just had another thought.
> 
> While we're switching the JSON date in the list view, it would be great if we could also use the JSON dose in that column instead of the system one - that's another thing that Kiribati are very keen on.
> 
> <img alt="2022-04-05_12-11-31 (1)" width="1280" src="https://user-images.githubusercontent.com/19318937/161655200-bf45bd74-2a96-4403-a568-19e3b4a6c074.png">

Yeah the doses column is always '1' at the moment which is ... not very useful 😆 . But Tonga also don't have a JSON dose field. Are we ok to leave it as '1' if there's no JSON dose, but if there is one, then we'll chuck it in here?

... I feel like relying on dodgy json fields for the summary view isn't amazing 😓  but I'm happy to roll with it given we're not expecting other countries to use it either

**Comment by adamdewey** [comment]
Yeah agree, relying on JSON schema definitely not ideal - but without funding for an architectural re-think I think it might be our only option to give Kiribati a decent useable system? 

But yes, I think it would be great to leave it as '1' if the field isn't present in the JSON schema :)

**Comment by adamdewey** [comment]
Maybe we can have it only use the JSON schema (for both Vax dates and Dose) if a preference flag is set on the Store or something?

**Comment by adamdewey** [comment]
Or fallback if the field doesn't exist like you suggest, I don't think there's much in it - whichever you find easiest to work with :)

**Comment by katherine-sussol** [comment]
> Or fallback if the field doesn't exist like you suggest, I don't think there's much in it - whichever you find easiest to work with :)

Thanks, went with a fallback, could see having too many dependent settings getting really annoying to manage. 
E.g. it would be possible to set a preference to use supplementalData VaxDate and Dose but if the supplementalData schema didn't actually have a VaxDate and Dose the UI would just break without some kind of fallback anyway 😱

**Comment by adamdewey** [comment]
Thanks Kat - sounds great :)

**Comment by katherine-sussol** [comment]
Nearly there - just have to link the correct PCD (will go by ID if present, otherwise use date comparison I think).

A little bit crude...but I think this is all the needed info?
https://user-images.githubusercontent.com/65875762/164370002-83023138-b4c2-4a98-8a24-5eea1c87faa1.mp4

**Comment by adamdewey** [comment]
This is awesome! Not crude at all! Nice work @katherine-sussol  :))

**Comment by adamdewey** [comment]
Looking great at a first glance!

Need to give the display ordering some TLC (guessing this can be done with the JSON schema), but other than that this looks really good. 

Also need to think about coordinating [#4638](https://github.com/openmsupply/mobile/issues/4638) with the release of this as the old data doesn't display very well at all. Might need some fairly decent testing against the existing Kiribati datafile.

**Comment by katherine-sussol** [comment]
Closed by #4668 (8.5.0-rc1)

**Comment by adamdewey** [comment]
Just tested against live data - looks awesome but couple of tweaks needed: 

1. Update the first 'Date of vaccination' field to be 'Date of entry' 
2. Fix the 'Invalid date' that are appearing for a lot of patients. 

The invalid dates are due to the dates not appearing in the format that Mobile expects. 

1. 
![image](https://user-images.githubusercontent.com/19318937/169723189-552ba99f-a9f8-4c78-9f05-f7cd012110ef.png)

2. 
![image](https://user-images.githubusercontent.com/19318937/169723242-5198b11c-1a28-4206-9771-8e78c844a2da.png)

![image](https://user-images.githubusercontent.com/19318937/169723328-db5b84b5-a2b7-4b65-80d0-85474921969f.png)

**Comment by katherine-sussol** [comment]
🎉   getting there! 

> * Update the first 'Date of vaccination' field to be 'Date of entry'

- Done here: https://github.com/sussol/client-JSON-schemas/blob/main/Kiribati/COVID-19-vaccination-rollout/VaccinationEvent.JSON

> * Fix the 'Invalid date' that are appearing for a lot of patients.

- Next steps: Confirm if it's consistently incorrect (i.e. yyyy-mm-dd) - if so we might be able to just hac...tweak the parsing logic in mobile to first try to parse as DD/MM/YYYY, otherwise try YYYY-MM-DD. If it's not then some data cleanup is likely required...
