### ISSUE TITLE
Showing invalid date

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4640]
## Describe the bug

Mobile expects a single date format example "01/01/2021" if we send a date in any other format that gives the wrong output like "1/1/2021" which gives an invalid date.

![image](https://user-images.githubusercontent.com/19318937/160726647-f8746173-fa4b-4b68-b6ef-594b17947469.png)

### To reproduce

Steps to reproduce the behaviour:

1. Go to mSupply and send any data with the date of format "1/1/2021"
2. Check-in tablet and it will show you an invalid date.

### Expected behaviour
It should show the correct date.

### Proposed Solution

export const convertMobileDateToISO = dateString => {
  if (!dateString) return undefined;

  const separators = ['/', '-'];
  const splitDate = dateString.split(new RegExp(separators.join('|'), 'g'));

  if (splitDate.length !== 3) return undefined;
  const dayOfMonth = splitDate[0].padStart(2, '0');
  const month = splitDate[1].padStart(2, '0');
  const year = splitDate[2].padStart(4, '0');

  return `${year}-${month}-${dayOfMonth}`;
};

### Version and device info

- App version:8.4.1
- Tablet model: In physical device Lenovo, and Emulator as well.
- OS version:

### Additional context

n/a

**Comment by ujwalSussol** [comment]
@katherine-sussol , @DhanyaHerath   :    @anildahalsussol  demonstrated how the mobile could format the date in expected format and save it....  I am happy to proceed in this manner.

**Comment by katherine-sussol** [comment]
After some investigation it's looking like this is only occurring for the `vaccineDate` field in NameNotes. Other dates from mSupply are expected to be in ISO format, i.e. `yyyy-mm-ddThh:mm:ss` and handled by https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/database/utilities/parsers.js#L20-L37 before being saved into mobile's database.

I think the issue with this field is that it's just a random JSON string in a free form text field rather than a proper date typed field and isn't converted to/from a standard date format when being sent/received from Desktop.

**Comments on Proposed Fix**
Agree with the general approach of adjusting the format before trying to display in mobile, however, when the input string is missing a leading 0 (e.g. 28/3/2022), the suggested method `moment(dateString).format('MM/DD/YYYY');` unfortunately isn't working as expected and returns 'Invalid Date' also. Example here: https://jsfiddle.net/fop03thr/

This is because the input (dateString) needs to match the format specified:
https://momentjs.com/docs/#/parsing/string-format/

The correct format string for the example would be 'MM/D/YYYY' (but as examples have shown, we can't guarantee this).

I think what we might be able to do instead is split the string by delimiters (`-` or `/`) and 0 pad day/month if shorter than 2 digits, or 0 pad year if it is less than 4 digits... this will at least account for our most common cause of errors which is missing leading zeros. Unfortunately, as it's just a string, it's possible to enter something completely invalid, and we wouldn't be able to cater to every possible permutation (this is why having some kind of type specifier/schema would be useful here longer term!)

**Comment by adamdewey** [comment]
Adding screenshot to issue description for clarity

**Comment by katherine-sussol** [comment]
Closed by #4643
