### ISSUE TITLE
Some info are not displayed on the customer invoice of a vaccination synced to the server

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/mobile#4742]
## Describe the bug

The name notes description are not displayed in an invoice of a vaccination. Also the name of the vaccinator is displayed as empty while there was a vaccinator but maybe the vaccinator is not consider the same as a Prescriber

![image](https://user-images.githubusercontent.com/11624516/170877904-d1ebeae7-a8c7-49c5-830e-1b5b8cc9b11c.png)

![image](https://user-images.githubusercontent.com/11624516/170876667-3e2e52b5-47c7-4944-85e8-42fd8bfccc92.png)

 This patient has name notes

![image](https://user-images.githubusercontent.com/11624516/170880359-5c37c5c0-48b5-48ed-9579-4c8d11d46130.png)

### To reproduce

Steps to reproduce the behaviour:

1. Go to mobile create a vaccination
2. Go through the vaccination process. Add a vaccinator
3. Sync and check the customer invoice on the server

### Expected behaviour

I suppose the name note description should be displayed as well as the vaccinator name as the prescriber ?

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v8/05-rc1
- Tablet model: Galaxy tab A8
- OS version: Android 11

**Comment by DhanyaHerath** [comment]
@katherine-sussol I think you're 100% correct on those points - prescriptions and vaccinations are different; it would be possible to add "Vaccinator" to desktop UI, and the name_notes are not displayed well (I could have __sworn__ we have an issue for that already but I can't see it now...).

However, I don't think we will prioritise this for desktop and I'm not sure whether it's even worth making an issue for :( , firstly for the reason you said: vaccine dispensing is unlikely to be extended beyond Tonga/Kiribati, and secondly because even if they were to continue, they're mostly only using mobile. (Plus we have no funding for it 😄)

**Comment by katherine-sussol** [comment]
Thanks @DhanyaHerath! That's fair, sounds like we can close this - it'll be here in the mobile issue history in case it does come up in the future or in any discussions :).
