### ISSUE TITLE
A script for converting localisation files into csv and back to js

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#484]
It would be very handy to have a script that parses all files under /localisation and converts them to csv files, one per language. 
Csv file can then be converted to excel, and sent for translation, once translated a script should be able to do the reverse.

**Comment by Chris-Petty** [comment]
It'd be very worthwhile making sure that whatever format exported/imported conforms to popular localisation editing tool format(s)

**Comment by joshxg** [comment]
I think this should be done soon! 

Idea: Keep strings in `.json` files, import them to use as the parameter for the localization singletons.

Then use a package such as https://www.npmjs.com/package/json2csv (first one I googled) to convert. simple!

**Comment by diegoevangelisti** [comment]
I agree with the idea of keeping the data in `.json` files to can easily export it to csv and import it later. Based on Andrei’s thoughts of having one file per language, this can be a probable flow:

New `.json` files, one for each language:
gb.json, fr.json, gil.json, fl.json, la.json

Example of file structure for gb.json

```
{
	“authStrings": {
		“loggin_in”: “Loggin in ...”,
		“username”: ”Login”,
		…
		},
	“buttonStrings”: {
		…
		}
	…
}
```
So each file contains all the information related with one language and the data is organized by localization files.
(authStrings, buttonStrings, etc)

All files can be imported in localisation/index.js and exported like this:

`const gb = JSON.parse(fs.readFileSync(‘./gb.json’)`
`const fr = JSON.parse(fs.readFileSync(‘./fr.json’)`
And so on for the rest.

`export { gb, fr, gil, fl, la }`

After that all files in /localization can have access to corresponding string:

Example for authStrings.js

```
Import { gb, fr, gil, tl, la } from ‘./index.js'

export const authStrings = new LocalizedStrings({

gb: {
    logging_in: gb.authStrings.loggin_in,
    login: gb.authStrings.login,
    password: gb.authStrings.password,
    repeat_password: gb.authStrings.repeat_password,
    user_name: gb.authStrings.user_name,
    email: gb.authStrings.email,
    warning_sync_edit: gb.authStrings.warning_sync_edit,
},
fr: {
    logging_in: fr.authStrings.loggin_in
    login: gb.authStrings.login,
    password: gb.authStrings.password,
    user_name: gb.authStrings.user_name,
},
gil: {
    logging_in:  gil.authStrings.loggin_in,
    login: gil.authStrings.login,
    password: gil.authStrings.password
    user_name: gil.authStrings.user_name,
},
tl: {
    logging_in: tl.authStrings.loggin_in
    login: tl.authStrings.login,
    password: tl.authStrings.password,
    user_name: tl.authStrings.user_name,
},
la: {
    logging_in: la.authStrings.loggin_in,
    login: la.authStrings.login,
    password: la.authStrings.password,
    user_name: la.authStrings.user_name,
},
});
```

I just started creating the script, using this package jsonexport (https://www.npmjs.com/package/jsonexport) the csv is generated and working well. 
Before to continue, what do you think about the overall idea?

**Comment by joshxg** [comment]
this is great and pretty much exactly what I was thinking.

Couple of things to think about:
(I will use `section` for some object of strings e.g. `buttonStrings`, `authStrings`)

- What happens with missing translations? For example, if `gb` has one translation for example `buttonString.patient` - but the `fr` file does not - it would be ideal if the exported file has for `fr`, a line `buttonString,patient,''` or something of the like, so the translator can see there is no translation and one needs to be added.
- And related: When developers add a string, we want to make this as easy as possible, so that no one is put off by adding translations, even if it is just in english/spanish at first. So that means: easy to find the section to put it. What file to put it in and what section in that file. Also, how many files do you have to open to add it?

In an ideal world, it would be great if I can just open one file, and add the translation there. I'm not sure if it is easiest to do all this with `language` based files, or `section` based files.


-----

If we have `section` based files, we could use 

```
Import { authJson } from ‘./index.js'

export const authStrings = new LocalizedStrings({
gb: {
    ...authJson.gb
},
fr: {
    ...authJson.fr
},
...
});
```

(And maybe we don't actually need the `authStrings.js` file anymore)

But, then the script for exporting will have to be more complex.

Possibly you can put in `index.js` 

```
export const localizedStrings = [authStrings, ... , buttonStrings];
```

And then in the script, just iterate over each `localizedString` and create the csv for each language, that way.

-----

Not sure if language json or section json is more difficult or better.. but great start go with whatever is easiest and simplest!

**Comment by Chris-Petty** [comment]
If you look at `validationStrings.js` you'll see you can actually nest the translation `sections` in the object. Food for thought:
```javascript
export const validationStrings = new LocalizedStrings({
  gb: {
    general: {},
    username: {
      required: 'Enter the username',
    },
    email: {
      required: 'Enter the E-mail',
      valid: 'Enter a valid E-mail',
    },
    password: {
      required: 'Enter the password',
      matchRepeat: 'Password & repeat password must match',
      lengthInvalid: 'Password must be 8-32 characters long',
      containsSpaces: 'Password cannot contain spaces.',
    },
    repeatPassword: {
      required: 'Enter the repeat password',
    },
  },
  fr: {},
  gil: {},
  tl: {},
});
```

**That said, research actual format that localisation tools use!**

There are some [opensource tools](https://omegat.org/) and plenty of commercial tools for doing translations. If we can support doing our translations in at least one such tool I think it'll open the opportunity to get translations faster and of better quality! So please aim for the exported file format and structure of content to be usable by localisation tools.

**Comment by diegoevangelisti** [comment]
@joshxg @Chris-Petty thanks, I'll keep on updating about the progress based on your suggestions.

**Comment by Rebecca367** [comment]
## Testing on version 3.1.1

Steps to reproduce or otherwise test the changes of this PR:

Log in page:
- [x] Check `Password` and `User name` placeholders
- [x] Enter a valid user name and password and check the `Logging in...` message
- [x] Enter an invalid username or password and check text `Invalid username or password`
