### ISSUE TITLE
Kiribati Vax: Is deceased true is overwritten from the server which allowed it to create vaccination

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#4843]
## Describe the bug

Is deceased true is overwritten from the server which allowed it to create vaccination.

When you make an edit to the patient record, do not sync it, and then go and search for the same patient, it pulls the patient's record from cloud, clicking it downloads and syncs the cloud data into the database. If the sync has not happened properly this will override the last change you had made locally. 

### To reproduce

Steps to reproduce the behaviour:

1. Create a name and create an event and sync to the server from tablet A.
2. Sync tablet B and that name must be visible.
3. That patient is editable in tablet B which is weird actually I think only Homestore must be allowed to edit.
4. And now sync and now search online for that name.
5. And see the Is deceased Boolean.
6. See error.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.4.2.207227
- Tablet model:Samsung
- OS version:

**Comment by sworup** [comment]
## Issue detail:

To clarify, when you make an edit to the patient record, do not sync it, and then go and search for the same patient, it pulls the patient's record from cloud, clicking it downloads and syncs the cloud data into the database. If the sync has not happened properly this will override the last change you had made. 

This is not only `isDeceased` case, this will happen for all of the fields. 

Right @anildahalsussol?

**Comment by sworup** [comment]
Now patient is only editable from home store as per a footrunner code I left in telegram. So that multi-tab update problem would be taken care of by this footrunner code. https://github.com/openmsupply/mobile/issues/4876#issuecomment-1212762457
However, the patient override from lookup button still is overriding the data. #4841  will fix that. After which I am expecting this issue to be fixed too.
Can we come back to test this when #4841 gets merged please @nisha-dangol.
For now I am closing this adding it to ready for testing. Is that ok @@anildahalsussol ?

**Comment by nisha-dangol** [comment]
This seems fixed since the deceased patient is not allowed to proceed to vaccination event as long as the stores are in sync.
