### ISSUE TITLE
App crashes before syncing records when searching online

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/mobile#4890]
## Describe the bug
It seems that when patient(which is visible in both stores) details are edited (like DoB or anything else) in one store1 and searched online from store2 before pulling records, it causes app to crash!

### To reproduce
Steps to reproduce the behaviour:
1. Create a patient in Store 1 and sync
2. In Store2, lookup that patient so it is visible there now as well.
3. Back in Store1, edit some patient details and sync.
4. Now, in Store2, don't manual sync and go straight to vaccinations>Search online
5. Click that patient and See error: app crashes!

### Expected behaviour
No app crash whatsoever!

### Proposed Solution
Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info
- App version: latest

**Comment by sworup** [comment]
@nisha-dangol As I talked to @anildahalsussol about this issue. The culprit is isDeceased field. What is happening is the server has isDeseased filed and the app does to. When syncing properly through sync button or automatic, this isDeseased field is getting populated by default value. But when we search online through a fetch api call, and try to put the data in database, for some reason, this isDeceased field tries to set as null and the app crashes as Boolean cannot have null value. At least that seems to be the issue from the bug report. 

**Fix:** We need to see if isDeceased is null and set false default value.

I am of-course presuming here, have to look when trying to fix the bug to see if that is indeed the case.

**Comment by sworup** [comment]
@anildahalsussol check it yesterday and today I checked it too. This one is a issue anymore. Could not be replicated. Closing.

**Comment by nisha-dangol** [comment]
No more crashing like before!
