### ISSUE TITLE
Patients: Not able to create a patients

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#5044]
## Describe the bug

Not able to create a new patient.

### To reproduce

Steps to reproduce the behaviour:

1. Go to  Dispensing.
2. Click on New patients.
3. Fill all mandatory field.

### Expected behaviour

Must allow creation of new patients.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.6.2 rc03
- Tablet model: lenovo
- OS version:

**Comment by sworup** [comment]
![SCR-20230106-g4k](https://user-images.githubusercontent.com/683452/210939045-044c4245-2ce0-4964-9611-51ea22196765.png)

**Comment by sworup** [comment]
Resloved by #5057

**Comment by AnushaUp** [comment]
## Testing
Tested in `V8.6.2-rc04`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Go to Dispensing. 
- [ ] Click on New patients.
- [ ] Fill in all mandatory fields.
- [ ] Previously the Save button remained disabled, now it should be enabled and you should be able to save the patient.

### Regression testing

- [ ] Vaccine module for Kiribati has added surveySchema && surveyForm && nameNoteIsValid checks. So maybe check there to see if the patient creates feature still works.
