### ISSUE TITLE
In supplier requistion while viewing indicators app crashes

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#5061]
## Describe the bug

- While creating or viewing supplier requisition with program that has indicators.
- If you click on indicators button to see the indicator tab the app crashes

![screen1](https://user-images.githubusercontent.com/683452/210973865-9f5cb102-6684-4465-82cb-8c383dbd41dc.png)
![screen2](https://user-images.githubusercontent.com/683452/210973897-a40c163c-eafe-440e-90a3-f3a20bb2e2fa.png)

### To reproduce

Steps to reproduce the behaviour:

1. While creating or viewing supplier requisition with program that has indicators.
2. If you click on indicators button to see the indicator tab the app crashes

### Expected behaviour

The indicators should show and not crash the app

### Proposed Solution

database is actually injected in the createIndicatorValue method, despite that UIDatabase is used to get the current store. We can use database object here and the issue goes away.

### Version and device info

- App version:
- Tablet model: 8.6.2 rc2
- OS version:

**Comment by sworup** [comment]
Resolved with #5062

**Comment by santoshkhanal12** [comment]
Tested on mobile version: v8.6.2-rc04

## Change summary

While creating or viewing supplier requisition with program that has indicators.
If you click on indicators button to see the indicator tab the app crashes

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] While creating or viewing supplier requisition with program that has indicators. **-PASS-**
- [ ] If you click on the indicators button to see the indicator tab the app should show indicators and not crash **-PASS-**
  The app did not get crashed
