### ISSUE TITLE
Reason column should be visible to all items if reason is enabled

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/mobile#5086]
## Describe the bug

Make reason column visible to all items if enabled

### To reproduce

Steps to reproduce the behaviour:
Take datafile where reasoning is enabled.
1. In mSupply desktop, enable positive and negative reason, and disable `Open vial wastage`
2. Create a stock take for the vaccine item
3. The reason column is invisible to this vaccine item
4. Enter quantity and see if the difference is not 0.
5. Try to finalize and it will not because reason must be set.

### Expected behaviour

Make reason visible to all items if positive/negative reasons are enabled, include `Open vial wastage` reason if enabled to vaccine items only

### Proposed Solution

First check if both positive and negative reasons are enabled then make reason column visible to all items.
If `Open vial wastage`  reason is enabled then include it along with negative reason as existing for vaccine item, otherwise just show positive/negative reason to vaccine items too as similar to normal item.
After that check stock take reason validation on finalization.

### Version and device info

- App version:Develop
- Tablet model:Emulator
- OS version:

**Comment by arjunSussol** [comment]
@anildahalsussol I noticed that if `Open vial wastage`  reason is disabled in desktop side then the reason column is invisible in mobile side even both negative and positive reasons are active. So, after discussion with @sworup @anildahalsussol @ujwalSussol we decided to make reason column visible for vaccine item too even the respective reason is disabled.

So, the agreed solution would be:
First check if both positive and negative reasons are enabled then make reason column visible to all items.
If `Open vial wastage`  reason is enabled then include it along with negative reason as existing for vaccine item, otherwise just show positive/negative reason to vaccine items too as similar to normal item.
After that check stock take reason validation on finalization.

**Comment by ujwalSussol** [comment]
> So, the agreed solution would be:
> First check if both positive and negative reasons are enabled then make reason column visible to all items.
> If `Open vial wastage` reason is enabled then include it along with negative reason as existing for vaccine item, otherwise just show positive/negative reason to vaccine items too as similar to normal item.
> After that check stock take reason validation on finalization.

@arjunSussol :  thanks agreed with the above.

**Comment by sworup** [comment]
Resolved with https://github.com/openmsupply/mobile/pull/5087

**Comment by AnushaUp** [comment]
Tested in: V8.6.2-rc05
Test passed
