### ISSUE TITLE
Request requisition: Keep requisition lines with zero requested quantity on finalise

### ISSUE THREAD

**Issue by JonnaQuismundo** [openmsupply/mobile#5090]
## Is your feature request related to a problem? Please describe.

Some stores in Ivory Coast need to create request requisition lines even if the requested quantity is zero so we can push item data values to eSigl.

We will add a store pref [Store pref](https://github.com/sussol/msupply/issues/12273): "Keep requisition lines with zero requested quantity on finalise" to allow the creation of requisition lines with 0 quantity after finalise

this is not applicable for emergency orders

## Describe the solution you'd like

**A clear and concise description of what you want to happen.**

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

Dead line for PR : 10th Friday 2023

## Job code
[NFM_ESIGL] CI NFM3 : ESIGL Integration

**Comment by DhanyaHerath** [comment]
Can this issue be closed @arjunSussol?

**Comment by AnushaUp** [comment]
## Testing
Tested in mobile `mSupply v8.6.5` with mSupply `Server 705` 

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Enable the  store preference `Keep requisition lines with zero requested quantity on finalise` in desktop
- [ ] In mobile, create a general requisition with many lines
- [ ] Enter `requested quantity` value to some of the lines and keep zero for remaining.
- [ ] Click finalize button, all lines should be kept in the requisition.
- [ ] Repeat same by disabling the above preference, zero lines will be deleted from requisition.
- [ ] Create an emergency order type program requisition by enabling above preference.
- [ ] It should delete all lines having zero requested quantity.
- [ ] Repeat same for ordinary program requisition by enabling preference, zero lines will be shown.
- [ ] Repeat same by disabling preference with emergency and ordinary program requisition, delete all zero lines
