### ISSUE TITLE
Kiribati Vaccine module - Patient survey demographic data does not load in Prescription edit patient window

### ISSUE THREAD

**Issue by sworup** [openmsupply/mobile#5101]
## Describe the bug

In the prescriber select window or other dispensing windows, if you click the edit patient button, the survey data does not load.

### To reproduce

1. Go to the 'Dispensing' page
2. Select a patient to dispense vaccine to
3. In the patient prescriber select window or any other window other then patient select window, click on patient edit button
4. You can see that the patient demographic data beside the patient detail section does not load any data and has default values set. Also save button is disabled as there is no demographic data.
5. This does not happen if you click the patient edit button in the root patient selection table column. Click this button first would load the data for any window coming afterward so to test the bug you have to avoid clicking the button here.

### Expected behavior

The survey data should also be loaded and available in the patient edit window.

### Proposed Solution

Survey data needs to be loaded for it to show up in the edit patient window. It is loaded on the edit button click. The button at the front patient select table in dispensing page does load survey data. The button inside does not. Make sure the button inside loads it too.

### Version and device info

- App version:
- Tablet model:
- OS version:

### Additional context

None

**Comment by sworup** [comment]
Resolved with https://github.com/openmsupply/mobile/pull/5102

**Comment by AnushaUp** [comment]
## Testing
Tested in `v8.6.2-rc05`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Load kiribati vax data file
- [ ] Go to the 'Dispensing' page, Select a patient to dispense vaccine to. 
- [ ] This does not happen if you click the patient edit button in the root patient selection table column. Click this button first would load the data for any window coming afterward so to test the bug you have to avoid clicking the button here.
- [ ] In the patient prescriber select window or any other window other then patient select window, click on patient edit button, You can see that the patient demographic data beside the patient detail section load all data loaded. Also save button is not disabled.
