### ISSUE TITLE
Patient > DoB > Allow a valid date entry by typing

### ISSUE THREAD

**Issue by arjunSussol** [openmsupply/mobile#5157]
## Describe the bug

Patient > DoB field, the DoB reset in `completedForm` in back-end code if you try to enter a date by typing instead of using date picker. As this cause issue in #5132, I just disabled the date entry by typing.

In future we have to make it functional. One should allow to enter a valid date by typing and datePicker.

### To reproduce

Steps to reproduce the behaviour:

### Proposed Solution

In future we have to make it functional. One should allow to enter a valid date by typing and datePicker.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by AnushaUp** [comment]
## Testing
Tested in `v8.6.6-rc02`
Steps to reproduce or otherwise test the changes of this PR:

- [ ]  Store must be a dispensary.
- [ ] Navigate to dispensing and click on `New Patient`.
- [ ] Enter the required field and enter the date and hit enter.
- [ ] Even after hitting the enter, the `Save` button shouldn't be disabled.
- [ ] OR enter the age and hit enter, again the `Save`  button shouldn't be disabled.

**Comment by AnushaUp** [comment]
@arjunSussol Tested and passed👍
