### ISSUE TITLE
Stock take line: editing batch > keyboard disappear

### ISSUE THREAD

**Issue by bijaySussol** [openmsupply/mobile#5190]
## Describe the bug

When have a long stock take line > Editing the batch (Probably all i would say), The keyboard get disappear automatically.
It probably may also depends on the tablet screen size, Some would fit 4 some may have 8 after adding next batch and editing the Keyboard disappear.

### To reproduce

Steps to reproduce the behaviour:

1. Create a new stock take
2. Add many lines
3. Try editing the batch on the last one

### Expected behaviour

It should not.

### Proposed Solution

TDB

### Version and device info

- App version: 8.6.3
- Tablet model: Emulator
- OS version: Android

### Additional context

Raised from client. read here: https://support.msupply.org.nz/cerb6/profiles/ticket/KS-2514-KM
Video: see here: https://github.com/openmsupply/open-msupply-internal/issues/28

**Comment by arjunSussol** [comment]
@bijaySussol I am already reserved by GRS work next week.
So, if it is urgent then another guy can over take and fix this issue.

**Comment by AnushaUp** [comment]
## Testing
Tested in mobile `mSupply v8.6.5` with `mSupply Server 705`
### Setup
Steps to reproduce or otherwise test the changes of this PR:

- Create a stocktake with many lines so that you have to scroll to view/edit last batch line record
- Try editing any line with scrolling back and forth

### Tests
- [ ] No keyboard disappearing
