### ISSUE TITLE
case sensitive should not be checked during creating name

### ISSUE THREAD

**Issue by arjunSussol** [openmsupply/mobile#5237]
## Describe the bug

Patient duplicity alert is not generated if the duplicate name created with the different case.
For e.g. `Arjun` is not equal to `arjun` and duplicate name confirmation alert failed.

### To reproduce

https://github.com/openmsupply/mobile/assets/13060254/cbcba9d3-6d32-4552-b1d0-a1e33351c573

Steps to reproduce the behaviour:

1. Go to Vaccination
2. Look for an existing name
3. Try create duplicate name as above but with different case
4. No duplicity check alert generated

### Expected behaviour

`Arjun = arjun` in the case of username/name, but not valid for password.
Duplicity check should be performed without caring about the case of the firstName and lastName

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by arjunSussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate patient check not case insensitive](https://trello.com/c/l2Jb12ZG/110-duplicate-patient-check-not-case-insensitive)

**Comment by AnushaUp** [comment]
## Testing
Tested in` v8.6.6-rc02`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Create a new name e.g. `arjun sah` and enter dob and other mandatory fields.
- [ ] Again try to create same name with Caps On e.g. `ARJUN SAH`, enter dob as above and mandatory fields in the dispensing form and just first, last, and dob in the vaccination form.
- [ ] There should be an alert `Are you sure you want to duplicate this patient? A patient with name: ARJUN SAH and date of birth: {1} already exist.`
- [ ] Click either Cancel or Save/Next to create duplicate patient.

**Comment by AnushaUp** [comment]
@arjunSussol Tested and passed👍
