### ISSUE TITLE
Keyboard pops up then disappears when selecting field

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#624]
Build Number: 2.1.0-rc8

Description:
When editing a stocktake it can be frustrating when selecting a field to have the keyboard briefly come up and immediately dismiss.

Reproducible: Yes, usually

Reproduction Steps:

1. Make a stocktake with 20+ items
2. Tap the editable quantity field of the item at the very bottom of screen
3. You enter a number and tap "Next" on device keyboard
4. Cursor advances to next cell, but keyboard closes
5. Tap on the cell: the keyboard opens and immediately closes again.
6. Tap again on the cell and now the keyboard stays open and you can enter the next value. Ick.

**Comment by arjunSussol** [comment]
@Chris-Petty This issue affecting the First setup page and Login page too.
There would be some more input form affected by this keyboard issue.

Anyway, same fix would work for all as mentioned here:
https://github.com/APSL/react-native-keyboard-aware-scroll-view

I have tested, and going to submit the same pull request for all affected form.

**Comment by Chris-Petty** [comment]
@arjunSussol seems like a simple enough improvement for initialisation page and for login page. Though I wonder if the issue you have more in mind that the keyboard can cover the field you're entering on those interfaces. That is the problem the react-native-keyboard-aware-scroll-view component aims to resolve.

For the tables we have a (crude) way of scrolling the table up so on cell focus events. Something to do with this seems to dismiss the keyboard completely (i.e. no keyboard) when you press "Done"/"Next" to focus the next cell. To get keyboard visible you have have to tap that just came into focus.

**Comment by andreievg** [comment]
Hi @arjunSussol, i've looked at https://github.com/sussol/mobile/pull/777, it looks like the pages to generic page keyboard issue need to be fixed in: https://github.com/sussol/react-native-generic-table-page:
![screen shot 2019-01-15 at 4 37 42 pm](https://user-images.githubusercontent.com/26194949/51157275-fe9f3400-18e3-11e9-941e-75adfb7e8bb4.png)

For this you need to work on the repository locally:

* Clone that repo
* Make changes in that repo (including `yarn add react-native-keyboard-aware-scroll-view`
* In mobile package.json remove `react-native-generic-table-page`
* In terminal (in mobile repository), type `yarn add file:../react-native-generic-table-page` (note after `file:` you need to point to location of cloned repo
* Remove `node_modules` directory in mobile repo
* `yarn install`
* `react-native run-android`
* test your changes

Once you are happy with changes make a pr in `https://github.com/sussol/react-native-generic-table-page`

* Once that PR is merged, we will need to push the latest `react-native-generic-table-page` to npm
* When latest `react-native-generic-table-page` is pushed, we can do this in mobile `yarn upgrade react-native-generic-table-page`
* Then make a PR with newest package.json

related: #625

**Comment by arjunSussol** [comment]
Thanks @andreievg for guidance and hints.
I have submitted pull request as:
https://github.com/sussol/react-native-generic-table-page/pull/15

**Comment by arjunSussol** [comment]
This issue is fixed by https://github.com/sussol/react-native-generic-table-page/pull/15
So, can be closed.

**Comment by andreievg** [comment]
Still needs build testing after merging:  https://github.com/openmsupply/mobile/pull/799

**Comment by joshxg** [comment]
# Testing
- [x] Advancing to the next cell on a stocktake doesn't make the keyboard go whacko
