### ISSUE TITLE
Mobile fails to make customer requisition from primary server

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#640]
Build Number: 2.1.0-rc8

Description:
If you make a PO to a mobile site from your primary store (perhaps desktop in general?) it appears to fail to make the requisition, just showing a customer invoice with -1

![image](https://user-images.githubusercontent.com/7684221/37941369-64e1b73a-31ca-11e8-8a02-c3fa6fce790e.png)

![image](https://user-images.githubusercontent.com/7684221/37941402-8442a7b0-31ca-11e8-835c-e359e7152cf6.png)

Reproducible: yes

Reproduction Steps:
Make a PO to mobile from desktop. Check it on mobile.

Comments: High priority, looks pretty bad if anyone on desktop attempts purchase ordering from a mobile supplier.

**Comment by Chris-Petty** [comment]
![image](https://user-images.githubusercontent.com/7684221/37941391-7908a782-31ca-11e8-9620-d1ac8b5a02b0.png)

**Comment by Chris-Petty** [comment]
This isn't actually that surprising - mSupply desktop doesn't use requisitions for ordering between sites. But it's still broken because mobile wasn't built to handle them. We could just get mobile to sort out generating an invoice number. That should actually be sufficient.

**Comment by sworup** [comment]
@Chris-Petty This set of code introduces the above behavior

https://github.com/sussol/msupply/blob/56cd84c8cbb9d88d584042579d3ad8b705df15d1/vc_methods/purchaseOrderCreateLinkedReq.txt#L107-L113

- It checks if the store that created the PO has the store that PO is made to as the supplying store. Otherwise it just sets the serial_number as -1 and user_id as blank.
- I have checked and if the supplying store condition is fulfilled, the PO does get proper serial number.

**Comment by Chris-Petty** [comment]
There is a chance that because mSupply desktop actually uses requisitions for internal orders now, this may be fixed. Are you still able to replicate the issue @sworup ?

**Comment by sworup** [comment]
@Chris-Petty yes, if I try to add a requisition to a store that is not the supplier store for the particular store. I still get the -1 serial number.

**Comment by andreievg** [comment]
@sworup -1 serial numbers are set on records that are created on primary server but belong to satellite (mobile/desktop) sites. When the record arrives to satellite (mobile/desktop) site it should be set to the next available serial number. Did the serial number change when it was synced to mobile ?

**Comment by sworup** [comment]
@andreievg If the requisition is not made to a supplier store then the requisition that comes to mobile or desktop, both have -1 as serial number. If the condition in the snippet of code above passes, then it gets a serial number.

**Comment by andreievg** [comment]
@sworup it doesn't matter where the requisition goes, the response requisition (created from request requisition) get's assigned -1 as serial number if it the store it is for does not belong to the primary server.

In this case, finalising purchase order creates response requisition, with serial number -1. When it arrived on satellite/mobile site the serial number is assigned.

Primary server cannot set serial number because it is not allowed (in our sync system, only store/site that a record belongs to can change it's properties <- primary server can only create a record for that site, but can't change it)

I've checked, this works as expected, closing.

**Comment by Chris-Petty** [comment]
Little followup, I've re-read the original issue description. The problem isn't that the requisition was getting -1 as a serial number, it was that no customer requisition was being made _at all_. Only a customer invoice with serial number -1. I'd try and replicate but I think `develop` is bork anyway

**Comment by andreievg** [comment]
@Chris-Petty 
> I've checked, this works as expected, closing.

You can trust me I've checked the original issue, PO made correct customerRequisition
