### ISSUE TITLE
[Ivory Coast] Stock takes by program

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#816]
Epic:  sussol/org-issues#18
Related: #815  - Base design for this will be similar to requisitions. Use that issue for design, any stock take specific alterations can be in here?

### Description:
Require functionality to create a stock take linked to a program

### Requirements:
- Creating a stock take should have the option to create a "program" stock take
- When these are linked, a user should not be able to add or remove items.
- All the items in the program will be linked to the stock take

### Comments:

I think essentially we are looking at the same thing as in requisitions in #815 - Difference being there aren't periods or order types for stock takes (???)

**Comment by joshxg** [comment]
The way this has been implemented on desktop, there is no relation between the stock take and program. This is as if you add or remove items from the stock take, the relation is essentially ruined.

If we were to implement this with a link, a relation should be made in 4d?

An idea of @Chris-Petty was to have the same 'process' of creating a stock take by program as a requisition, but no real relation between the stock take and masterlist is made, the process is just to pre-populate a stocktake, and potentially limit the use of adding and deleting on mobile(?)

**Comment by joshxg** [comment]
have started discussion on requisition by program here : #815 - I imagine stock takes will/might use a very similar/same approach for design

**Comment by andreievg** [comment]
> An idea of @Chris-Petty was to have the same 'process' of creating a stock take by program as a requisition, but no real relation between the stock take and masterlist is made, the process is just to pre-populate a stocktake, and potentially limit the use of adding and deleting on mobile(?)

I think program will have to be linked to stocktake, one for reporting purposes, two when your re-open the stock take.

I believe item list will be on lock down

**Comment by Chris-Petty** [comment]
@andreievg I'm not sure what specific reports we should be considering, but I presume that most program based reporting would just use the program master list as a filter. That way reports would include other sources of stock movement, say if they just did an inventory adjustment to add some random stock (that may or may not be part of a program masterList). Reason based reports could still be restricted to a master list in this same way.

**Comment by andreievg** [comment]
@Chris-Petty 

In terms of reporting, I was thinking if stocktake was associated with program, it maybe easier and quicker (performance wise) to query by programID on stocktake. But you are correct, to fully capture all adjustments for a program in mSupply desktop, filtering by items from master list would be more inclusive. By the way, we should try and restrict IC from using inventory adjustment without stocktake, otherwise they would ask use to add reasons to them.

The main point why I insist that stocktake is linked to program, is if our interface changes for stocktakes that are a program in mobile, then we have to store the association.
