### ISSUE TITLE
[Vaccine Module][Temperature Breach] - Helper methods to extract breach information.

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#843]
As per epic: https://github.com/sussol/org-issues/issues/23

### NOTE

After breaking this down, and writing pseudo logic for breaches, it seems it's better as a DataBase entity. Should be quicker for users, and cleaner for developers too. Please ignore any logic written here for calculating breaches, there will be a Realm Table called `TemperatureBreach`. Also all of the helper methods should be named with `TemperatureBreach` not just breach as described below. (`link to TemperatureBreach, creation and updates issue here`)

#### Description

This issue should probably be broken down into smaller issues, here I will try to summarise all requirements for calculating breach.

##### What is a breach ?

Temperature breach occurs when temperature (sensorLog) for a particular fridge is breached for a certain time period.

LocationType.customData holds the setting for identifying a breach, in this format:

```
{
    breaches: [{
      upperBound: 1000,
      lowerBound: 8,
      duration: 60,
    }, {
      lowerBound: -10000,
      upperBound: 2,
      duration: 15
    }]
}
```

There are a number of places where breach calculation needs to be done, in summary:
* In some cases just need to display the ⚠️ in a row, for item or batch
  * .hasBreach() should be sufficient in this case
* Another case is to display ⚠️ on the graph at particular point, here we need more fine grained information (min/max temperature, and from, to time/date)
* Lastly, even more info is needed in the Breach Modal, and Breach Modal
  * Here we need a list of breaches with item/batches associated with them

#####  Breach for Vaccine Module Page

Need to find breaches for particular fridge, fromDate and toDate. Breaches need to be displayed in the graph as a ⚠️ (red one of those)
`Proposing`
* Fridge.getBreaches(fromDate, toDate) 
  * Just need min or max temperature and fromDate, toDate

##### Breach for Vaccine Manage Item Page

In this page, non-zero batches for a particular Vaccine Item are shown.
Display ⚠️ in a batch row
`Proposing`
* ItemBatch.hasBreaches
  * Return true on first match

##### Breach for Customer Invoice/Manage Vaccine Stock Page

In this page, non-zero batches for a particular Vaccine Item are shown.
Display ⚠️ in a batch row
`Proposing`
* Item.hasBreaches
  * Goes through each non-zero batch for item 
  * Return true on first match

##### Breach Modal

This is the Modal that pops when whenever ⚠️ is clicked, it need more fine grained information that is calculated as part of the modal logic. See designs below. 

`Proposing`
* Calculate all of the data for the Modal (apart from graph related data, graph points can be calculated when row is expanded)
  * I think utility method is in order here, `utilities.getTemperatureBreaches(fromDate, toDate, itemID = null, batchID = null)` ?
* Graph Data 
  * Since each breach has fromDate, toDate and Fridge info, it should be easy enough to extract required data from `SensorLog`

![VM - Breach Hepatitis B-1](https://user-images.githubusercontent.com/26194949/55366082-b1764a00-5543-11e9-8abd-abede613914d.png)
![VM - Breach (Specific Breach)-1](https://user-images.githubusercontent.com/26194949/55366085-b1764a00-5543-11e9-9b88-12f8cf4e195a.png)

#### Calculating ItemBatch.hasBreach

* Have to find which fridge this batch has been assigned to, look transactionBatches for this batch (from supplier invoice or inventory adjustment), and see which fridge this batch was in at what time `TransactionBatch.location`
* Check `SensorLog.location` records associated with a fridge this batch was in in the period it was in the fridge. And use `location.locationType.customData.breaches` to figure out a breach.
* If at least one breach is identified, don't search further, return true.

#### Calculating utilities.getTemperatureBreaches
utilities.getTemperatureBreaches(`fromDate, toDate, itemID = null, batchID = null`)

##### Output

```
[ { 
  fromDate: 'datetime',
  toDate: 'datetime', 
  duration: 'hours/mins etc', 
  fridge: 'location record', 
  temperatureExposure: 'from to to', 
  items: [ {
    item: 'item record',
    batches: [ {
      batch: 'batch record'
     }
    ]
   }
  ]
}]
```

**Comment by joshxg** [comment]
There are a number of places where breach calculation needs to be done, in summary:

#### In some cases just need to display the ⚠️ in a row, for item or batch .hasBreach() should be sufficient in this case. 

I think this is done everywhere it needs to be, correct me if I'm wrong.

#### Another case is to display ⚠️ on the graph at particular point, here we need more fine grained information (min/max temperature, and from, to time/date)

Generic method in `src/utilities` - `extractBreaches(arrayOfSensorLogs)`
Pass an array of `sensorLogs` - method returns a 2D array:
`[ [ sensorLog1, sensorLog2 ], [sensorLog1, sensorLog2, sensorLog3 ] ]` where each element is a 'breach'.

- From Andrei:
    - `aggregateLogs({ data, minOrMax, numberOfDataPoints, startDate, endDate })`, data is an array (Realm) of sensorLogs (may not be sorted), 
    - `numberOfData` points is how many data points to produce, 
    - `startDate` and `endDate` are optional defaults to earliest and oldest `sensorLog` record otherwise use them to divide data into data points 

I'd say `startDate` and `endDate` are relatively pointless? Also may as well return { min: [], max: [] } ? Since we're iterating anyway, I'm not sure if it would be much less performant doing both and saves two calls when needed. Unless I don't understand this properly. Essentially this is creating chart data? `createVaccineChartData` or something?

- [ ] Lastly, even more info is needed in the Breach Modal, and Breach Modal Here we need a list of breaches with item/batches associated with them

BreachModal is opened through clicking on a 'breach icon' specific to an `Item`, `ItemBatch` or `Fridge` - #870 

Finding Breaches: 

- `Item.breaches` - `get breaches`, group all distinct `sensorLogs` for each `ItemBatch` by `Location` - call above `extractBreach` method on each set of `sensorLogs`.
- `Location.breaches` - call above `extractBreach` method on `Location.sensorLogs`
- `ItemBatch.breaches` - call above `extractBreach` method on `ItemBatch.sensorLogs`

Extracting data:

For a breach:
- For Breach itself - `Date`, `Duration`, `ExposureRange`, `QuantityAffected`, `NumberOfBatchesAffected`
    - `Date`: First `sensorLog` date
    - `Duration`: Difference between first `sensorLog` date and last. (`Date.getDifference = (date1, date2) => {}`? I'm not sure if we create class methods like this though)
    -  `ExposureRange` - min and max for `sensorLog` for the breach
    - `QuantityAffected` - sum of first `sensorLog.batches.totalQuantity`

- For Chart of sensorLogs during the breach

Depending on what context the breach is opened: If fridge, get item data. If ITem, get batch data, if ItemBatch - nothing?
- Items: All `ItemBatches`: `{ code, quantity, expiry, arrived, time in breach }` for each item
- Batch: Get the above for each `ItemBatch` for the one `Item`

Use the above method for getting chart data.

Use a method

```
extractBreachData = ({breaches, [items]}) => { 
iterate through batches, storing each distinct batch related to an item in [items]
store `{ code, quantity, expiry, arrived, time in breach }`
each new encounter of a batch, increment time in breach by the difference between this log and last. Maybe just leave other fields alone after first encounter
```

- What is the behaviour for having just one sensorLog as a breach (I imagine there would be a lot of these) - what would the `timeInBreach` be? N/A? What about capturing an item being in one `sensorLog` - N/A?

**Comment by joshxg** [comment]
I think/what I want/ideal imo data passed to `BreachModal` :

```
{
    primary/breach: { location, dateTime, quantityAffected, duration, noBatchesAffected }
    secondary: { items: 
            [ 
                        { 
                        itemName: HepB, 
                          batches: [
                                                { code, expiry, quantity, dateArrived }
                                         ]
                         }
            ]
    chart: { maxLine, hazards } 
    ....
}
```

for each breach

**Comment by joshxg** [comment]
## Three methods

### Aggregator [ @wlthomson ]

`aggregateLogs({sensorLogs, maxOrMin, toDate, fromDate, numberOfPoints })` 

Takes an array/`Realm.results` of `sensorLog` objects. Returns an array of `numberOfPoints` * data points/datum.

```
{
    date,
    temp
}
```

### Breach extracting [ @joshxg ]

`getBreaches(sensorLogs)`

Takes an array/`Realm.results` of `sensorLog` objects. Returns a 2D array. Each element is a `sensorLog` array - we are calling this array a 'breach'. This 'breach' contains sequential `sensorLog` objects, each with a temperature above the 'breachThreshold' *aswell* as the surrounding `sensorLogs` (The `sensorLog` before AND after the 'breach').

### Hazard point generation

`getBreachPoints(sensorLogs)`

Takes an array of `sensorLog` objects - will call `getBreaches` to group the `sensorLogs` into 'breaches' and maps each breach into an object:

```
{
    date/x,
    maxTempDuringBreach/y
    breaches: [sensorLogs]
}
```

Will return an array of the above objects for each breach. **Not sure on property names for this**

### Extracting Item Information

`sensorLogsExtractBatches({sensorLogs, itemBatch, item})`

Takes an array or `Realm.results` of `sensorLog` objects. Iterates through each `SensorLog` and finds the `ItemBatches` for that log. If an Item has been supplied, filter by that item. If an `ItemBatch` has been supplied, filter by that `ItemBatch`. Will create an object:

```
{
    code,
    expiryDate,
    quantity,
    dateArrived,
    durationInBreach
}
```

`durationInBreach` will be updated on every new encounter when iterating through `SensorLogs`.

return object in the form

```
{
    itemId:   [ { aboveObjectForEachBatchForThisItem } .. , ]    
    itemId2: [ { aboveObjectForEachBatchForThisItem } .. , ]
}
```

**Comment by andreievg** [comment]
@joshxg, for that last method: sensorLogsExtractBatches, would it also call getBreaches. And i think we wanted it to produce ready made prop for breach modal, so i would assume it would return something like:
```
[
  breach: [sensorLogs],
  items: [
    item: fullItem ?
    batches: [{
      code,
      expiryDate,
      quantity,
      dateArrived,
      durationInBreach
   }]
  ]
]

```

also should only look at isInBreach on sensorLogs, to not count surrounding sensorLogs returned by getBreaches. 

Also can we put this methods somewhere as utility methods for vaccine module ?

**Comment by joshxg** [comment]
I think it doesn't need to return breaches, but add it to be safe for now, why not. 

Your return object is basically the same as what I've listed, just a different shape. An array of objects v an object with itemID's as keys.


-- 

I think the way `VaccineChart` handles `onPress` should change. A generic `onPress` for the whole chart, just the values passed will be a breach object

-- 

sure `src/utilities/modules/vaccine` - or to deep?

**Comment by andreievg** [comment]
@joshxg @wlthomson also the getBreachPoints takes and array returned by aggregateLogs as well as sensor logs and return should be:
```
[{
    date,
    temp,
    breach: [sensorLogs]
}]
```

**Comment by andreievg** [comment]
@joshxg 
> I think the way VaccineChart handles onPress should change. A generic onPress for the whole chart, just the values passed will be a breach object

Yeah that thought just crossed my mind

**Comment by andreievg** [comment]
@joshxg 

> I think it doesn't need to return breaches, but add it to be safe for now, why not.

If it doesn't return breaches alongside item/batches, how are we going to link breaches with batches (say for multi breaches in a particular item with different batches affected by different breaches)

**Comment by joshxg** [comment]
@andreievg 

> for that last method: sensorLogsExtractBatches, would it also call getBreaches.

Is there a use case for wanting this data for all `sensorLogs`? It seems to constrain the functionality, where you can just call it manually beforehand

**Comment by joshxg** [comment]
@andreievg 

Just thinking about `durationInBreach`

Since we are calculating time in the breach, it might be good to also add to more properties:
- `timestampEnteredBreach` - the first time the batch was encountered - `sensorLog.timestamp` ?? 
- `durationLeftBreach` - the first time the batch isn't seen??

The problem with these are.. if the `ItemBatch` enters and exits within the same breach things can get complicated. I imagine we will just count the first time, but if we wanted to count each time - array of objects `[ { enteredTimestamp, existTimestamp} ]`
