### ISSUE TITLE
[Vaccine Module][Manage Vaccine Item] - Manage Vaccine Item Page

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#851]
As per epic: https://github.com/sussol/org-issues/issues/23

#### Description

This page is opened when item is selected from 'Manage Vaccine Stock Page'. Realm.Item is passed with navigator.

![VM - Manage Vaccine Item (1)-1](https://user-images.githubusercontent.com/26194949/55919428-17e91f80-5c4a-11e9-86bf-d1f923680fb7.png)

* Table displays all ItemBatches (quantity > 0) for the item
* `Last VVM Pass` column is not needed
* Arrived is from first TB-> transaction date for the ItemBatch
* Table is array of objects (not realm object)
* Apply changes to move to top right and similar style to finalise button (current/historic not needed at this stage)
* Fridge assignment and VVM pass/fail similar to SI
* Breach column can be empty for now
* Create IA when apply changes is pressed
  * If fridge has changed, record in IA
  * Record toggled VVMs in fridge IA and reduce stock for fails
* Ignore dispose button for now

**Comment by joshxg** [comment]
@andreievg 

> If fridge has changed, record in IA

What is this for? I think we can find when the batch was swapped to a different location from the `sensorLog` for that `itemBatch` easier? 

Also just to note, you probably have though of this: I think we are assuming a particular `itemBatch` will always be in the same fridge as a group. I'd imagine this might not always be the case so may need to provide a way to manually split `itemBatch`

### Design

- I think the navigator likes to use the page name for the top right button - could make it not be but might be better to be consistent.
- Could use `PageInfo` at the top like the other data pages - could put the name there if going with the above note.
    - From `Item` : Item Code, Item Name, Total Stock, Doses per vial, Total doses available,  description

- Should this be made in a way such that it can be used for regular items, not just vaccines? e.g. in the future navigate to this page from current stock rather than using the expansion?

**Comment by joshxg** [comment]
VVM Status default to true rather than null?

**Comment by joshxg** [comment]
I think it might be better to have a 'split' column, which will manually open the modal to split the batch into two, rather than automatically after the VVM status is set to failed (could be both but probably over kill). 

This gives more control for fridge management, disposing and vvm status updating without introducing quantity changes.

Disabled after disposing or with vvm status = fail

**Comment by andreievg** [comment]
@joshxg
> VVM Status default to true rather than null?

I think null, kinda like stocktake. Plus we don't actually know if it's been set to true previously.

> What is this for? I think we can find when the batch was swapped to a different location from the sensorLog for that itemBatch easier?

IA in desktop records location in adjustments. Sensor logs may not be downloaded yet, if that's the case what if the fridge was noticed to be in breach and vacs relocated before logs are synced, it would appear that itembatch is in different fridge for that breach, does that make sense?

> I think it might be better to have a 'split' column, which will manually open the modal to split the batch into two, rather than automatically after the VVM status is set to failed (could be both but probably over kill).

I think thats a great point. My only concern is overloading interface, chat tomorrow about it (there is still a way to split without it, but its crude)

Let me know if there is anything else I've missed in this reply

**Comment by joshxg** [comment]
The stock would have come in through a supplier invoice and had it's VVM status set to pass. Any that had a status of fail would have had an inventory adjustment and not be counted in the quantity shown in this page. Unless some vaccines don't use a vvm, in which case we can't enforce the status in supplier invoice and null it is!

If all vaccines do use a vvm status - It seems correct to have vaccines that are currently in stock have a vvm status of passed. When they have failed, you navigate to this page to set it to fail.

Otherwise a user navigates to this page, sets them all to passed, and then next time they visit they are all set to blank again, seems odd?

**Comment by andreievg** [comment]
> The stock would have come in through a supplier invoice and had it's VVM status set to pass. Any that had a status of fail would have had an inventory adjustment and not be counted in the quantity shown in this page. Unless some vaccines don't use a vvm, in which case we can't enforce the status in supplier invoice and null it is!

Sorry forgot to mention we are not enforcing vvm status to be set before finalising si. Have a chat about this tomorrow btw

**Comment by andreievg** [comment]
> The stock would have come in through a supplier invoice and had it's VVM status set to pass. Any that had a status of fail would have had an inventory adjustment and not be counted in the quantity shown in this page. Unless some vaccines don't use a vvm, in which case we can't enforce the status in supplier invoice and null it is!

Sorry forgot to mention we are not enforcing vvm status to be set before finalising si. Have a chat about this tomorrow btw
