### ISSUE TITLE
Localise 'Pushing changes to the server' 

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#879]
Build Number: 2.2.0

Description: 
When manually syncing, 'Pushing changes to the server' isn't translated

Reproducible: Yes

Reproduction Steps:
Manually sync when viewing a language that isn't English

Comments:

**Comment by diegoevangelisti** [comment]
@Chris-Petty @joshxg I found where to make the needed changes to have 'Pushing changes to the server' properly translated to each language. Should I keep it like this anyway based on the changes that will be taking place on solving issue [#484](https://github.com/openmsupply/mobile/issues/484)?

**Comment by joshxg** [comment]
Closed by #1563

**Comment by joshxg** [comment]
## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] Go to Initialise page
- [x] Connect to the server
- [x] Check messages: `Initialising ...` and ` Pulling changes from the server`

Then:
- [x] Go to Log in page
- [x] Select a language 
- [x] Create/Edit/Delete records to push changes to the server
- [x] Perform a Manual Sync
- [x] Check the message: `Pushing changes to server`
