### ISSUE TITLE
[Store CustomData] - how to best deal with store Custom Data in mobile

### ISSUE THREAD

**Issue by andreievg** [openmsupply/mobile#880]
For vaccine module store.custom_data (on current mobile store) can have a field usesVaccineModule, which enables different interface in mobile app with optional modules

https://github.com/openmsupply/mobile/pull/868 introduces this change where custom_data for current store is saved in settings and is parsed and access later when needed. 

Some comment links
https://github.com/openmsupply/mobile/pull/868#discussion_r275176486
https://github.com/openmsupply/mobile/pull/868#discussion_r275176554

Figure out a better way to store modules.

**Comment by joshxg** [comment]
@andreievg @Chris-Petty @wlthomson @mark-prins 

- `Settings` is a table in realm, where each object is a `key-value` pair.
- Each `value` is a string.

Currently, on incoming `[Store]` records, if the store is the mobile store, we store the `custom_data` in `Settings`, under the key `THIS_STORE_CUSTOM_DATA` with the value as a stringified JSON object.

In order to utilize some of this `customData` during ivory coast, we had to use node `global`s in order to customize logic, instead we can just use msupply `global` `Settings` 🤣 

Instead of storing all of `[Store]custom_data`, lets extract what we need and put them as their own key:value pairs in `Settings`. 

I propose simply adding some `Setting`s key value pairs (note that value is a string atm :():

```
THIS_STORE_MODULES: {
    *all modules listed here with true/false*
}
```
alternatively single key value pairs:

```
THIS_STORE_VACCINED_UP: false
THIS_STORE_DISPENSED_UP: false
```

We could also have a..

```
THIS_STORE_CUSTOMIZATIONS: {
    lookbackForSomeAMCThing: xx
}
```

When methods are being extended to utilize some different functionality, we can extract the current logic, and make different functions quite easily. Making sure there would be no regressions with current logic, but extending functionality with new logic.

I think this idea needs fleshing out and some polish, but I think it is a good option. Would require a few things, migration code, documenting settings well and changing some (small) existing code. (Also can remove `Store.customData`

**Comment by joshxg** [comment]
Also will just add that described above is currently on the Vaccines branch, NOT in develop.

**Comment by joshxg** [comment]
Also with the new `DataTable`, we can customise routes, without effecting other pages

i.e.

```
const gotoMenuPage(){
    const menuPageCustomizations = Settings.get(THIS_STORE_MENU_PAGE_CUSOMIZATIONS);
    switch (menuPageCustomizations){
        // Each different route is the same base component (MenuPage.js) with a different config
        // i.e. { buttons: xx }
        case(MENU_PAGE.VACCINE)
            return {routeName: 'vaccineMenuPage'}
        case(MENU_PAGE.DISPENSING)
            return {routeName: 'dispensingMenuPage'}
    }
}
```

Just need thought into having both vaccines and dispensing enabled
